In [1]:
#%run ./LLM/OpenAIClient ⇒ DataBricksで必要
from AzureOpenAIClient import *

In [2]:
# %run ./DocumentIntelligence #⇒ DataBricksで必要

In [3]:
from DocumentIntelligence import *

In [4]:
def extract_image_data(image_path):
    remainder_prompt = '''画像データを見て、以下の定義している項目を抽出し、その結果をJSON形式で返してください。
    画像やグラフ等で説明がある場合はそれの意味を説明してください。抽出した文字はもれなく出力してください。漏れがないように注意してください。

    # 抽出すべき項目
    1. 題名
    2. No
    3. 表題
    4. 設計名
    5. 故障モード
    6. 部品名
    7. 材料分類
    8. 材料名
    9. 内容
    10. 要因
    11. 対策
    12. 備考

    # 抽出されるべき項目
    "題名": "表題の内容から抽出されたテキストをここに入力",
    "No": "Noの内容から抽出されたテキストをここに入力",
    "表題": "表題の内容から抽出されたテキストをここに入力",
    "設計名": "設計名の内容から抽出されたテキストをここに入力",
    "故障モード": "故障モードの内容から抽出されたテキストをここに入力",
    "部品名": "部品名の内容から抽出されたテキストをここに入力",
    "材料分類": "材料分類の内容から抽出されたテキストをここに入力",
    "材料名": "材料名の内容から抽出されたテキストをここに入力",
    "内容": "内容の内容から抽出されたテキストをここに入力",
    "要因": "要因の内容から抽出されたテキストをここに入力",
    "対策": "対策の内容から抽出されたテキストをここに入力",
    "備考": "備考の内容から抽出されたテキストをここに入力"

    # 制約事項
    ・OCRの結果はできるだけもれなくやってください。
    ・画像やグラフ等の説明を用いて説明されている場合は、その中身をできるだけ自然言語として説明してください。
    ・あなたが間違えると多大な損失が発生するので、慎重に判断してください。
    '''

    # Azure OpenAIクライアントを初期化
    aoai = AzureOpenAIClient()
    def _merge_paragraphs(self, paragraph_numbers, content_data):
        merged_content = []
        if paragraph_numbers:
            for paragraph_num in paragraph_numbers:
                for index, content in enumerate(content_data):
                    if f'/paragraphs/{index + 1}' == f'/paragraphs/{paragraph_num}':
                        merged_content.append(content['content'])
        return ' '.join(merged_content)
    
    # 画像データから情報を抽出
    result = aoai.create_image_prompt('gpt-4o', image_path, remainder_prompt, response_format={ "type": "json_object" })

    return result

In [5]:
# import json
# 
# english_judgment_prompt = lambda content: f'''下記のデータを見て、その言語が英語かどうか判定してください。英語の場合はTrue、それ以外の場合はFalseでJson形式で返して下さい。スキーマはresultとしてその中にBoolを返してください。
# 
# データ：
# 
# 「{content}」
# 
# 制約事項
# ・文章が英語で書かれている場合はTrueを返す事。英語以外の言語で書かれている場合のみFalseで返して下さい。
# ・「Japanese」という単語が入っていても英語の場合は英語として判定してください！
# ・あなたが間違えると多大な損失が発生するので、慎重に判断してください。
# 
# '''
# 
# aoai = AzureOpenAIClient()
# def english_judgment(content):
# 
#     messages =  [
#         {"role": "system", "content": "あなたは従業員の創意工夫データを整形し、綺麗にまとめる役割である。"},
#         {"role": "user", "content": english_judgment_prompt(content) }
#     ]
#     try:
#         # JSON Modeの場合は以下を使用
#         # 注意点：プロンプトにJSONスキーマとJSONで返す指示を書くこと。
#         result = aoai.get_completion('gpt-4o', messages,response_format={ "type": "json_object" })
#         return bool(json.loads(result)['result'])
#     except Exception as e:
#         print(e)
#         return e
# 「{content}」
# 
# 制約事項
# ・文章が英語で書かれている場合はTrueを返す事。英語以外の言語で書かれている場合のみFalseで返して下さい。
# ・「Japanese」という単語が入っていても英語の場合は英語として判定してください！
# ・あなたが間違えると多大な損失が発生するので、慎重に判断してください。
# 
# '''
# 
# aoai = AzureOpenAIClient()
# def english_judgment(content):
# 
    # messages =  [
        # {"role": "system", "content": "あなたは従業員の創意工夫データを整形し、綺麗にまとめる役割である。"},
        # {"role": "user", "content": english_judgment_prompt(content) }
    # ]
    # try:
        # JSON Modeの場合は以下を使用
        # 注意点：プロンプトにJSONスキーマとJSONで返す指示を書くこと。
        # result = aoai.get_completion('gpt-4o', messages,response_format={ "type": "json_object" })
        # return bool(json.loads(result)['result'])
    # except Exception as e:
        # print(e)
        # return e

In [6]:
# 変換したいフォルダのパスを指定
doc_folder_path = r"C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009"
# 変換したいファイルのパスを指定
# doc_file_path = r"C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\gis_rag_test_2009_1.jpg"
# 変換したいファイルのパスを指定
# doc_file_path = r"C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\gis_rag_test_2009_1.jpg"

In [7]:
# 所定のフォルダ以下のdocをdocxに変換

import os
from doc2docx import convert

def convert_doc_to_docx(folder_path):
    converted_files = []
    errors = []

    for root, dirs, files in os.walk(folder_path):
        for file in files:
            if file.lower().endswith('.doc'):
                doc_path = os.path.join(root, file)
                docx_path = os.path.splitext(doc_path)[0] + '.docx'
                
                try:
                    convert(doc_path, docx_path)
                    converted_files.append(docx_path)
                    print(f"変換成功: {doc_path} -> {docx_path}")
                except Exception as e:
                    errors.append((doc_path, str(e)))
                    print(f"変換失敗: {doc_path} - エラー: {str(e)}")

    return converted_files, errors

# 変換を実行
converted, errors = convert_doc_to_docx(doc_folder_path)

print(f"\n変換されたファイル数: {len(converted)}")
print(f"エラーが発生したファイル数: {len(errors)}")

if errors:
    print("\nエラーが発生したファイル:")
    for doc_path, error_msg in errors:
        print(f"{doc_path}: {error_msg}")

c:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
100%|██████████| 1/1 [00:04<00:00,  4.32s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\オーストラリアシドニー.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\オーストラリアシドニー.docx

100%|██████████| 1/1 [00:05<00:00,  5.65s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\コンベンション市場実態調査20100224-①.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\コンベンション市場実態調査20100224-①.docx

100%|██████████| 1/1 [00:05<00:00,  5.15s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\シンガポール.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\シンガポール.docx

100%|██████████| 1/1 [00:05<00:00,  5.27s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\シンガポールコンベンション実態調査100309.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\シンガポールコンベンション実態調査100309.docx

100%|██████████| 1/1 [00:05<00:00,  5.26s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\上海におけるコンベンション市場実態調査（確認事項）100111.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\上海におけるコンベンション市場実態調査（確認事項）100111.docx

100%|██████████| 1/1 [00:05<00:00,  5.68s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\韓国済州島コンベンション調査最終報告100318.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\韓国済州島コンベンション調査最終報告100318.docx

100%|██████████| 1/1 [00:06<00:00,  6.14s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\香港コンベンション実態調査最終報告100318.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\香港コンベンション実態調査最終報告100318.docx

100%|██████████| 1/1 [00:04<00:00,  4.95s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\RENOLDS\CHAIN PROJECT Yamana.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\RENOLDS\CHAIN PROJECT Yamana.docx

100%|██████████| 1/1 [00:02<00:00,  2.83s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\RENOLDS\CHAIN PROJECT.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\RENOLDS\CHAIN PROJECT.docx

100%|██████████| 1/1 [00:05<00:00,  5.28s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\STREET SPACE RESERCH P20100310.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\STREET SPACE RESERCH P20100310.docx

100%|██████████| 1/1 [00:05<00:00,  5.13s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\海外事例調査100310たのうち.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\海外事例調査100310たのうち.docx

100%|██████████| 1/1 [00:06<00:00,  6.31s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\セムサ調査レポート FINAL.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\セムサ調査レポート FINAL.docx

100%|██████████| 1/1 [00:05<00:00,  5.33s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\調査書Wall AG.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\調査書Wall AG.docx

100%|██████████| 1/1 [00:05<00:00,  5.27s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\道路占用_企業事例調査_報告書20100319.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\道路占用_企業事例調査_報告書20100319.docx

100%|██████████| 1/1 [00:05<00:00,  5.29s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\CEMUSA LOPES 社.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\CEMUSA LOPES 社.docx

100%|██████████| 1/1 [00:04<00:00,  4.97s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\WALL AG_Kamiya-20100315.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\WALL AG_Kamiya-20100315.docx

100%|██████████| 1/1 [00:07<00:00,  7.40s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\【中間】道路活用事例20100316.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\【中間】道路活用事例20100316.docx

100%|██████████| 1/1 [00:06<00:00,  6.30s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\【中間】道路活用事例Clear Channel社（後藤）.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\【中間】道路活用事例Clear Channel社（後藤）.docx

100%|██████████| 1/1 [00:06<00:00,  6.16s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\セムサ調査レポート Hasegawa.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\セムサ調査レポート Hasegawa.docx

100%|██████████| 1/1 [00:06<00:00,  6.14s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\セムサ調査レポート Hasegawa20100317.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\セムサ調査レポート Hasegawa20100317.docx

100%|██████████| 1/1 [00:05<00:00,  5.29s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\調査書Wall AG.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\調査書Wall AG.docx

100%|██████████| 1/1 [00:05<00:00,  5.11s/it]

変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\道路活用事例中間報告100316 USA.doc -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\道路活用事例中間報告100316 USA.docx

変換されたファイル数: 22
エラーが発生したファイル数: 0

In [8]:
# 所定のフォルダ以下のdocxをpdfに変換

import os
import logging
from docx2pdf import convert

def convert_docx_to_pdf(folder_path):
    converted_files = []
    errors = []

    for root, dirs, files in os.walk(folder_path):
        for file in files:
            if file.lower().endswith('.docx'):
                docx_path = os.path.join(root, file)
                pdf_path = os.path.splitext(docx_path)[0] + '.pdf'
                
                try:
                    logging.info(f"WordファイルをPDFに変換中: {docx_path}")
                    convert(docx_path, pdf_path)
                    converted_files.append(pdf_path)
                    logging.info(f"変換成功: {docx_path} -> {pdf_path}")
                except Exception as e:
                    errors.append((docx_path, str(e)))
                    logging.error(f"{docx_path}のPDF変換中にエラーが発生しました: {str(e)}")

    return converted_files, errors

# ログの設定
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


# 変換を実行
converted, errors = convert_docx_to_pdf(doc_folder_path)

print(f"\n変換されたファイル数: {len(converted)}")
print(f"エラーが発生したファイル数: {len(errors)}")

if errors:
    print("\nエラーが発生したファイル:")
    for docx_path, error_msg in errors:
        print(f"{docx_path}: {error_msg}")

2024-12-22 00:43:59,075 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\オーストラリアシドニー.docx
100%|██████████| 1/1 [00:05<00:00,  5.43s/it]
2024-12-22 00:44:06,376 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\オーストラリアシドニー.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\オーストラリアシドニー.pdf
2024-12-22 00:44:06,379 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\コンベンション市場実態調査20100224-①.docx
100%|██████████| 1/1 [00:08<00:00,  8.35s/it]
2024-12-22 00:44:16,605 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\コンベンション市場実態調査20100224-①.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\コンベンション市場実態調査20100224-①.pdf
2024-12-22 00:44:16,605 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\シンガポール.docx
100%|██████████| 1/1 [00:05<00:00,  5.15s/it]
2024-12-22 00:44:23,633 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\シンガポール.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\シンガポール.pdf
2024-12-22 00:44:23,633 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\シンガポールコンベンション実態調査100309.docx
100%|██████████| 1/1 [00:05<00:00,  5.72s/it]
2024-12-22 00:44:31,232 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\シンガポールコンベンション実態調査100309.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\シンガポールコンベンション実態調査100309.pdf
2024-12-22 00:44:31,233 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\上海におけるコンベンション市場実態調査（確認事項）100111.docx
100%|██████████| 1/1 [00:06<00:00,  6.56s/it]
2024-12-22 00:44:39,664 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\上海におけるコンベンション市場実態調査（確認事項）100111.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\上海におけるコンベンション市場実態調査（確認事項）100111.pdf
2024-12-22 00:44:39,664 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\韓国済州島コンベンション調査最終報告100318.docx
100%|██████████| 1/1 [00:05<00:00,  5.52s/it]
2024-12-22 00:44:47,042 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\韓国済州島コンベンション調査最終報告100318.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\韓国済州島コンベンション調査最終報告100318.pdf
2024-12-22 00:44:47,043 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\香港コンベンション実態調査最終報告100318.docx
100%|██████████| 1/1 [00:05<00:00,  5.24s/it]
2024-12-22 00:44:54,184 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\香港コンベンション実態調査最終報告100318.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\CONVENTION\香港コンベンション実態調査最終報告100318.pdf
2024-12-22 00:44:54,185 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\RENOLDS\CHAIN PROJECT Yamana.docx
100%|██████████| 1/1 [00:04<00:00,  4.72s/it]
2024-12-22 00:45:00,777 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\RENOLDS\CHAIN PROJECT Yamana.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\RENOLDS\CHAIN PROJECT Yamana.pdf
2024-12-22 00:45:00,777 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\RENOLDS\CHAIN PROJECT.docx
100%|██████████| 1/1 [00:05<00:00,  5.15s/it]
2024-12-22 00:45:07,791 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\RENOLDS\CHAIN PROJECT.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\RENOLDS\CHAIN PROJECT.pdf
2024-12-22 00:45:07,792 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\STREET SPACE RESERCH P20100310.docx
100%|██████████| 1/1 [00:06<00:00,  6.21s/it]
2024-12-22 00:45:15,842 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\STREET SPACE RESERCH P20100310.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\STREET SPACE RESERCH P20100310.pdf
2024-12-22 00:45:15,842 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\海外事例調査100310たのうち.docx
100%|██████████| 1/1 [00:06<00:00,  6.36s/it]
2024-12-22 00:45:24,065 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\海外事例調査100310たのうち.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\海外事例調査100310たのうち.pdf
2024-12-22 00:45:24,067 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\Frau Müller(WALL AG).docx
100%|██████████| 1/1 [00:04<00:00,  4.82s/it]
2024-12-22 00:45:30,742 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\Frau Müller(WALL AG).docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\Frau Müller(WALL AG).pdf
2024-12-22 00:45:30,743 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\セムサ調査レポート FINAL.docx
100%|██████████| 1/1 [00:06<00:00,  6.07s/it]
2024-12-22 00:45:38,655 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\セムサ調査レポート FINAL.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\セムサ調査レポート FINAL.pdf
2024-12-22 00:45:38,656 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\調査書Wall AG.docx
100%|██████████| 1/1 [00:06<00:00,  6.04s/it]
2024-12-22 00:45:46,538 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\調査書Wall AG.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\調査書Wall AG.pdf
2024-12-22 00:45:46,538 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\道路占用_企業事例調査_報告書20100319.docx
100%|██████████| 1/1 [00:05<00:00,  5.91s/it]
2024-12-22 00:45:54,300 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\道路占用_企業事例調査_報告書20100319.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\FINAL\道路占用_企業事例調査_報告書20100319.pdf
2024-12-22 00:45:54,301 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\CEMUSA LOPES 社.docx
100%|██████████| 1/1 [00:05<00:00,  5.14s/it]
2024-12-22 00:46:01,308 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\CEMUSA LOPES 社.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\CEMUSA LOPES 社.pdf
2024-12-22 00:46:01,308 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\WALL AG_Kamiya-20100315.docx
100%|██████████| 1/1 [00:04<00:00,  4.68s/it]
2024-12-22 00:46:07,835 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\WALL AG_Kamiya-20100315.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\WALL AG_Kamiya-20100315.pdf
2024-12-22 00:46:07,835 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\【中間】道路活用事例20100316.docx
100%|██████████| 1/1 [00:06<00:00,  6.43s/it]
2024-12-22 00:46:16,103 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\【中間】道路活用事例20100316.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\【中間】道路活用事例20100316.pdf
2024-12-22 00:46:16,103 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\【中間】道路活用事例Clear Channel社（後藤）.docx
100%|██████████| 1/1 [00:06<00:00,  6.58s/it]
2024-12-22 00:46:24,585 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\【中間】道路活用事例Clear Channel社（後藤）.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\【中間】道路活用事例Clear Channel社（後藤）.pdf
2024-12-22 00:46:24,585 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\セムサ調査レポート Hasegawa.docx
100%|██████████| 1/1 [00:05<00:00,  5.84s/it]
2024-12-22 00:46:32,357 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\セムサ調査レポート Hasegawa.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\セムサ調査レポート Hasegawa.pdf
2024-12-22 00:46:32,357 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\セムサ調査レポート Hasegawa20100317.docx
100%|██████████| 1/1 [00:05<00:00,  5.86s/it]
2024-12-22 00:46:40,082 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\セムサ調査レポート Hasegawa20100317.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\セムサ調査レポート Hasegawa20100317.pdf
2024-12-22 00:46:40,082 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\調査書Wall AG.docx
100%|██████████| 1/1 [00:06<00:00,  6.82s/it]
2024-12-22 00:46:48,763 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\調査書Wall AG.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\調査書Wall AG.pdf
2024-12-22 00:46:48,763 - INFO - WordファイルをPDFに変換中: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\道路活用事例中間報告100316 USA.docx
100%|██████████| 1/1 [00:05<00:00,  5.11s/it]
2024-12-22 00:46:55,764 - INFO - 変換成功: C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\道路活用事例中間報告100316 USA.docx -> C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\gis_rag_test_2009\STREET SPACE\MIDDLE\道路活用事例中間報告100316 USA.pdf

変換されたファイル数: 23
エラーが発生したファイル数: 0

In [9]:
# Blob StorageにPDFをアップロード（フォルダ構造を維持）

import os
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient

def upload_pdfs_to_blob(local_folder_path, connection_string, container_name):
    # Blobサービスクライアントを作成
    blob_service_client = BlobServiceClient.from_connection_string(connection_string)

    # コンテナクライアントを取得
    container_client = blob_service_client.get_container_client(container_name)

    # ローカルフォルダ内のPDFファイルを再帰的に検索してアップロード
    for root, dirs, files in os.walk(local_folder_path):
        for file in files:
            if file.lower().endswith('.pdf'):
                local_file_path = os.path.join(root, file)
                
                # Blob内のパスを作成（フォルダ構造を維持）
                relative_path = os.path.relpath(local_file_path, local_folder_path)
                blob_path = relative_path.replace("\\", "/")  # Windowsパスを修正

                # BlobClientを取得
                blob_client = container_client.get_blob_client(blob_path)

                # ファイルをアップロード
                with open(local_file_path, "rb") as data:
                    blob_client.upload_blob(data, overwrite=True)
                
                print(f"アップロード完了: {local_file_path} -> {blob_path}")

# 実行
connection_string = "DefaultEndpointsProtocol=https;AccountName=kmakicistrage2;AccountKey=a460yXb+uyR0pZNC9ugy5LiLVKV4WvW7mqYxWjikLydKkm2OSJwOn7rR0mDmVKin/IEyd/hLWcir+AStlKazsg==;EndpointSuffix=core.windows.net"
container_name = "20240928-rag-test-container"
# upload_pdfs_to_blob(doc_folder_path, connection_string, container_name) # 本番実行時はコメントアウトを外す

# 副業では以下からスタート

In [10]:
# 特定のAzure Blobコンテナ内のファイルパスを全て取得する関数
# 副業ではココからスタート
import os
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient

def get_all_blob_urls(container_name, connection_string):
    # BlobServiceClientを作成
    blob_service_client = BlobServiceClient.from_connection_string(connection_string)
    
    # コンテナクライアントを取得
    container_client = blob_service_client.get_container_client(container_name)
    
    # Blob URLを格納するリスト
    blob_urls = []
    
    # Blob URLを取得
    for blob in container_client.list_blobs():
        blob_url = f"https://{blob_service_client.account_name}.blob.core.windows.net/{container_name}/{blob.name}"
        blob_urls.append(blob_url)
    
    # .pdfが含まれる要素のみをフィルタリング
    blob_urls = [file for file in blob_urls if '.pdf' in file]
    
    return blob_urls

# 使用例
connection_string = "DefaultEndpointsProtocol=https;AccountName=pdfalldata;AccountKey=1fe1xtPZKmSDxxU0peota+kkWZEUu7hSKBuXrJm8P0WACCcLgr4JbREvJhEJ40m+Za3ozJRZ4bFe+AStN0zXrQ==;EndpointSuffix=core.windows.net"
container_name = "rag-pdf"
blob_urls = get_all_blob_urls(container_name, connection_string)
print(blob_urls)
print(len(blob_urls))

2024-12-22 00:46:55,962 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf?restype=REDACTED&comp=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ce6575bb-bfb2-11ef-aa3d-30894aa4d14c'
    'Authorization': 'REDACTED'
No body was attached to the request
2024-12-22 00:46:57,597 - INFO - Response status: 200
Response headers:
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '1d0aa77e-c01e-00b4-4cbf-535e95000000'
    'x-ms-client-request-id': 'ce6575bb-bfb2-11ef-aa3d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:46:56 GMT'

['https://pdfalldata.blob.core.windows.net/rag-pdf/1_08-39_1章_元.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p1.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p10.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p100.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p101.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p102.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p103.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p104.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p105.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p106.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p107.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p108.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p109.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p11.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p110.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p111.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p112.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p113.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p114.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p115.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p116.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p117.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p118.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p119.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p12.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p120.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p121.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p122.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p123.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p124.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p125.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p126.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p127.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p128.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p129.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p13.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p130.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p131.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p132.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p133.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p134.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p135.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p136.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p14.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p15.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p16.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p17.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p18.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p19.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p2.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p20.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p21.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p22.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p23.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p24.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p25.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p26.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p27.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p28.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p29.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p3.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p30.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p31.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p32.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p33.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p34.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p35.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p36.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p37.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p38.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p39.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p4.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p40.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p41.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p42.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p43.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p44.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p45.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p46.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p47.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p48.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p49.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p5.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p50.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p51.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p52.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p53.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p54.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p55.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p56.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p57.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p58.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p59.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p6.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p60.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p61.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p62.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p63.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p64.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p65.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p66.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p67.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p68.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p69.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p7.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p70.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p71.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p72.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p73.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p74.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p75.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p76.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p77.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p78.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p79.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p8.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p80.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p81.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p82.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p83.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p84.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p85.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p86.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p87.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p88.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p89.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p9.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p90.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p91.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p92.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p93.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p94.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p95.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p96.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p97.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p98.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p99.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p1.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p10.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p100.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p101.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p102.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p103.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p104.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p105.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p106.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p107.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p108.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p109.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p11.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p110.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p111.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p112.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p113.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p114.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p115.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p116.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p117.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p118.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p119.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p12.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p120.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p121.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p122.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p123.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p124.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p125.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p126.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p127.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p128.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p129.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p13.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p130.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p131.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p132.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p133.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p134.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p135.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p136.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p137.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p138.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p139.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p14.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p140.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p141.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p142.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p143.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p144.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p145.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p146.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p147.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p148.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p149.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p15.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p150.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p151.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p152.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p153.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p154.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p16.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p17.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p18.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p19.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p2.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p20.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p21.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p22.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p23.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p24.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p25.

In [12]:
# サンプルのリスト
# file_list = ['1_08-39_1章_元.pdf', 'document.txt', 'presentation.pptx', 'report.pdf', 'image.jpg']

# .pdfが含まれる要素のみをフィルタリング
pdf_urls = [file for file in blob_urls if '.pdf' in file]

# その他のファイルをフィルタリング
not_pdf_urls = [file for file in blob_urls if '.pdf' not in file]

print(f"フィルタリング後のリスト: {pdf_urls}")
print(f"フィルタリング後のリスト: {not_pdf_urls}")
print(len(blob_urls))
print(len(pdf_urls))
print(len(not_pdf_urls))

フィルタリング後のリスト: ['https://pdfalldata.blob.core.windows.net/rag-pdf/1_08-39_1章_元.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p1.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p10.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p100.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p101.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p102.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p103.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p104.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p105.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p106.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p107.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p108.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p109.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p11.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p110.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p111.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p112.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p113.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p114.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p115.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p116.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p117.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p118.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p119.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p12.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p120.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p121.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p122.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p123.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p124.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p125.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p126.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p127.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p128.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p129.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p13.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p130.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p131.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p132.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p133.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p134.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p135.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p136.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p14.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p15.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p16.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p17.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p18.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p19.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p2.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p20.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p21.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p22.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p23.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p24.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p25.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p26.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p27.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p28.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p29.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p3.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p30.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p31.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p32.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p33.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p34.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p35.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p36.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p37.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p38.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p39.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p4.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p40.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p41.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p42.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p43.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p44.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p45.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p46.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p47.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p48.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p49.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p5.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p50.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p51.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p52.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p53.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p54.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p55.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p56.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p57.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p58.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p59.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p6.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p60.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p61.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p62.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p63.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p64.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p65.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p66.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p67.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p68.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p69.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p7.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p70.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p71.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p72.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p73.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p74.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p75.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p76.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p77.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p78.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p79.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p8.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p80.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p81.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p82.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p83.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p84.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p85.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p86.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p87.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p88.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p89.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p9.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p90.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p91.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p92.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p93.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p94.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p95.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p96.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p97.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p98.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p99.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p1.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p10.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p100.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p101.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p102.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p103.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p104.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p105.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p106.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p107.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p108.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p109.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p11.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p110.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p111.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p112.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p113.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p114.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p115.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p116.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p117.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p118.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p119.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p12.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p120.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p121.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p122.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p123.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p124.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p125.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p126.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p127.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p128.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p129.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p13.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p130.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p131.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p132.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p133.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p134.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p135.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p136.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p137.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p138.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p139.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p14.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p140.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p141.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p142.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p143.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p144.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p145.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p146.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p147.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p148.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p149.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p15.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p150.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p151.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p152.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p153.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p154.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p16.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p17.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p18.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p19.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p2.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p20.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p21.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p22.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p23.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p24.pdf', 'https://pdfalldata.blob.core.windows.net/rag-pdf/2年_中学校理科_指導書_板書例_/2年_中学校理

In [13]:
# Blob Storageに保存されたPDFファイルのOCRを実行

import os
import tempfile
from azure.storage.blob import BlobServiceClient
import pypdf

def perform_ocr(blob_url, split_f_path, extract_f_path, chunk_size, extract_keywords, new_file_name):
    """doc string
    blob_url: str OCRを実行するBlobのURL
    split_f_path: str PDFを分割する際の出力ディレクトリのパス
    extract_f_path: str 抽出したテキストを保存する際の出力ディレクトリのパス
    chunk_size: int ページ数ごとにPDFを分割する際のページ数
    extract_keywords: list 抽出するキーワードのリスト
    new_file_name: str 出力ファイル名の接頭辞"""
    # BlobServiceClientの作成
    blob_service_client = BlobServiceClient(account_url="https://pdfalldata.blob.core.windows.net")
    
    # コンテナとBlobの名前を取得
    container_name = blob_url.split('/')[3]
    blob_name = '/'.join(blob_url.split('/')[4:])
    print(f"コンテナ名: {container_name}, Blob名: {blob_name}")
    
    # BlobClientの取得
    blob_client = blob_service_client.get_container_client(container_name).get_blob_client(blob_name)
    
    # 一時ファイルの作成
    with tempfile.NamedTemporaryFile(delete=False, suffix='.pdf') as temp_file:
        temp_file_path = temp_file.name
        
        # Blobのダウンロードと一時ファイルへの書き込み
        blob_data = blob_client.download_blob()
        blob_data.readinto(temp_file)
        print(f"一時ファイル {temp_file_path} を作成しました。")
    
    try:
        # PDFの読み込み（確認用）
        pdf_reader = pypdf.PdfReader(temp_file_path)
        total_pages = len(pdf_reader.pages)
        print(f"Total pages in PDF: {total_pages}")
        
        # ここでOCR処理を行う（DocumentIntelligenceClientを使用）
        client = DocumentIntelligenceClient(endpoint="https://rag-test-di.cognitiveservices.azure.com/",
                                        key="5Bu5fhh7BzoLNl0HjWXmYOeDTCqQ60EJr5fLaMN0LUukhIjoyd7UJQQJ99ALACi0881XJ3w3AAALACOG9O9g",
                                        api_version="2024-07-31-preview")
        client.custom_flag = False # カスタムモデルを使用しない場合はFalse
        result = client.get_processed_result(temp_file_path, split_f_path, extract_f_path, chunk_size, extract_keywords, new_file_name)
        
        return result
    
    finally:
        # 処理が終了したら（エラーが発生しても）一時ファイルを削除
        if os.path.exists(temp_file_path):
            os.remove(temp_file_path)
            print(f"一時ファイル {temp_file_path} を削除しました。")

# OCR処理を実行（1ファイルでテスト）

In [13]:
# 試してみる
# blob_url = "https://kmakicistrage2.blob.core.windows.net/20240928-rag-test-container/CONVENTION/オーストラリアシドニー.pdf"
split_f_path = r"C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\2Q-PoC\output"
extract_f_path = r"C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\2Q-PoC\output"
chunk_size = 1000
extract_keywords = []
new_file_name = "processed_document"

# 出力ディレクトリの作成
os.makedirs(split_f_path, exist_ok=True)
os.makedirs(extract_f_path, exist_ok=True)

print("OCR開始")
result = perform_ocr(pdf_urls[1], split_f_path, extract_f_path, chunk_size, extract_keywords, new_file_name)
print("OCR終了")
for i in result:
    print(i)

OCR開始
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p1.pdf
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpapqnrl7v.pdf を作成しました。
Total pages in PDF: 1
OCR開始
OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpapqnrl7v.pdf を削除しました。
OCR終了
{'id': 1, 'file_name': 'processed_document', 'file_path': 'C:\\Users\\banqu\\AppData\\Local\\Temp\\tmpapqnrl7v.pdf', 'page_number': 1, 'type': '章タイトル', 'figure_table_type': None, 'content': '◆オンライン資料についてく', 'region': [0.5833, 0.7527, 2.2993, 0.7527, 2.2993, 0.9152, 0.5833, 0.9152]}
{'id': 2, 'file_name': 'processed_document', 'file_path': 'C:\\Users\\banqu\\AppData\\Local\\Temp\\tmpapqnrl7v.pdf', 'page_number': 1, 'type': 'その他の文章', 'figure_table_type': None, 'content': '最終ページに記載された登録フォーム https://support.gakuto-plus.jp/db-verif から, 学校名·メールアドレス·クーポンコードなどをご登録いただくと、下記資料をインター ネット経由でご利用いただけます。先生方のワークシートづくりにお役立てください。 なお,更新情報などについては、登録時のメールアドレスへお知らせいたします。', 'region': [0.5615, 1.2052, 6.5765, 1.2052, 6.5765, 2.0526, 0.5615, 2.0526]}
{'id': 3, 'file_name': 'processed_document', 'file_path': 'C:\\Users\\banqu\\AppData\\Local\\Temp\\tmpapqnrl7v.pdf', 'page_number': 1, 'type': '表', 'figure_table_type': 1, 'content': '## Table\n\n|  | コンテンツ名 | 内容 |\n| --- | --- | --- |\n| オンライン | 指導書オンライン版 | 年間指導計画カレンダー,板書例紙面,補充資料などを Web ページとし て閲覧することができます。 |\n|  | 指導書オンライン版 検索機能 (試験運用) | 生成 AI チャットポットを用いて,板書編内容の高度な内容検索ができます。 |\n|  | 基本問題作成機能 (試験運用) | 生成 AI に,教科書記述に基づいた基本的な問いの作成を指示することが できます。 |\n|  | CBT 「GAKCBT(ガクビット)」 | 全国学力·学習状況調査の類似問題を,CBT 形式にて練習することができ ます。問題を教科書ご使用期間中も更新いたします。 |\n|  | デジタル教科書 | 教科書紙面,動画教材などで構成されたデジタル教科書クラウド版をご利 用いただけます。 |\n| ダウンロ ード\n:unselected: | 追加問題素材 (Word 形式) | 評価問題を教科書ご使用期間中も更新いたします。 |\n|  | パワポ教科書 (PowerPoint 形式) | 教科書紙面を PowerPoint 形式で再構成し、動画素材などを埋め込んであ ります。図·写真·テキストは, PowerPoint での改変, Word などへのコピー が可能です。授業導入例などについて教科書ご使用期間中も更新いたしま す。 |\n|  | 指導書紙面 (Word 形式) | 板書例·評価基準·探究ワークシート·単元準備テスト·基本問題·評価問題 · 思考力問題など,基本的にすべての紙面を収録しております。 |\n|  | 図版素材 (png 形式) | 自作プリントなどに使用できる図版素材です。 |\n|  | 動画素材 (mp4 形式) | 実験観察動画の個別ファイルの状態です。 |\n|  | アンケート用問題素材 (専用操作) | Google Class Room や Microsoft Teams のアンケート機能を使い,基 本問題を生徒に出題する際の素材です。 |\n|  | 総ルビ教科書 (PDF 形式) | 教科書紙面を総ルビにした状態です。 |\n', 'region': [0.558, 2.1588, 6.592, 2.1588, 6.592, 8.0848, 0.558, 8.0848]}
{'id': 4, 'file_name': 'processed_document', 'file_path': 'C:\\Users\\banqu\\AppData\\Local\\Temp\\tmpapqnrl7v.pdf', 'page_number': 1, 'type': 'その他の文章', 'figure_table_type': None, 'content': '※内容は変更になる可能性があります。', 'region': [4.6875, 8.1007, 6.5723, 8.1007, 6.5723, 8.2317, 4.6875, 8.2317]}

In [14]:
import pandas as pd

# OCR処理結果を分類してDataFrameに追加する関数
def classify_and_append_to_df(result, df):
    table_data = []
    figure_data = []
    other_texts = []
    title_data = []
    
    for entry in result:
        content_type = entry['type']
        if content_type == '図':
            figure_data.append(str(entry))  # コンテンツの代わりにJSON全体を追加
        elif content_type == '表':
            table_data.append(str(entry))  # コンテンツの代わりにJSON全体を追加
        elif content_type == 'その他の文章':
            other_texts.append(str(entry))  # コンテンツの代わりにJSON全体を追加
        else:
            title_data.append(str(entry))# コンテンツの代わりにJSON全体を追加
    # 内容が空の場合にnote_dataを追加するロジックは削除。必要に応じてここに追加可能。
    
    # DataFrameに追加
    df = pd.concat([df, pd.DataFrame([{
        "filename": result[0]['file_name'] if result else '',
        #"majorcategory": daibunrui,
        #"subcategory": chubunrui,
        "title": title_data,
        "content": other_texts,
        "tableinfo": table_data,
        "graphinfo": figure_data
    }])], ignore_index=True)

    return df

# 全てのPDFに対してOCRを実行し、データフレームにtypeごとに格納する

In [15]:
# DocumentIntelligenceを使ったOCR処理
import os
import pandas as pd
import pprint
from DocumentIntelligence import DocumentIntelligenceClient
from tqdm import tqdm

# マウントしたBlobのパス
# Blob_PATH = "/dbfs/mnt/rag-poc-q2-container/pdfs/"
# Blob_PATH = "/dbfs/FileStore/pdfs"
connection_string = "DefaultEndpointsProtocol=https;AccountName=pdfalldata;AccountKey=1fe1xtPZKmSDxxU0peota+kkWZEUu7hSKBuXrJm8P0WACCcLgr4JbREvJhEJ40m+Za3ozJRZ4bFe+AStN0zXrQ==;EndpointSuffix=core.windows.net"
blob_urls = get_all_blob_urls(container_name, connection_string)

note_data = str({"content": "None", "figure_table_type": "None", "file_name": "None", "file_path": "None", "id": "None", "page_number": "None", "region": "None", "type": "None"})

def process_ocr_results(ocr_results):
    processed_results = []
    
    # ページごとにグループ化
    pages = {}
    for item in ocr_results:
        page_number = item['page_number']
        if page_number not in pages:
            pages[page_number] = []
        pages[page_number].append(item)

    # 各ページを処理
    for page_number, page_content in pages.items():
        # ページ内の最初の「その他の文章」を見つける
        first_text = next((item for item in page_content if item['type'] == 'その他の文章'), None)
        first_text_table = next((item for item in page_content if item['type'] == '表'), None)
        first_text_graph = next((item for item in page_content if item['type'] == '図'), None)
        first_text_title = next((item for item in page_content if item['type'] == '章タイトル'), None)
        
        # 最初の「その他の文章」が英語でない場合のみ、そのページの内容を保持　⇒ 2Q特有の処理のため、コメントアウト
        # if first_text and not english_judgment(first_text['content']):
            # processed_results.extend(page_content)
            # print(f"first_text：{english_judgment(first_text['content'])}")
        # else:
            # if first_text_table and not english_judgment(first_text_table['content']):
                # processed_results.extend(page_content)
                # print(f"first_text_table{english_judgment(first_text_table['content'])}")
        #
        # if first_text and "English" in first_text['content']:
            # processed_results.extend(page_content)

    return processed_results

# 特定のAzure Blobコンテナ内のファイルパスを全て取得する関数
def get_all_blob_paths(container_name, connection_string):
    # BlobServiceClientを作成
    blob_service_client = BlobServiceClient.from_connection_string(connection_string)
    
    # コンテナクライアントを取得
    container_client = blob_service_client.get_container_client(container_name)
    
    # ファイルパスを格納するリスト
    file_paths = []
    
    # ファイルパスを取得
    for blob in container_client.list_blobs():
        file_paths.append(blob.name)
    # .pdfが含まれる要素のみをフィルタリング
    file_paths = [file for file in file_paths if '.pdf' in file]
    
    return file_paths

# フォルダー内のすべてのファイルパスを取得　⇒　ローカルにPDFがある場合に使用する
# def get_all_file_paths(directory):
    # file_paths = []
    # for dirpath, _, filenames in os.walk(directory):
        # for filename in filenames:
            # if filename.endswith(".pdf"):
                # file_paths.append(os.path.join(dirpath, filename))
    # return file_paths

# OCR処理を実行する関数
def perform_ocr_origin(filepath, split_f_path, extract_f_path, chunk_size, extract_keywords, new_file_name):
    client = DocumentIntelligenceClient(endpoint="https://rag-test-di.cognitiveservices.azure.com/",
                                key="5Bu5fhh7BzoLNl0HjWXmYOeDTCqQ60EJr5fLaMN0LUukhIjoyd7UJQQJ99ALACi0881XJ3w3AAALACOG9O9g",
                                api_version="2024-07-31-preview")
    client.custom_flag = False # カスタムモデルを使用しない場合はFalse
    return client.get_processed_result(filepath, split_f_path, extract_f_path, chunk_size, extract_keywords, new_file_name)

# ファイルパスをリストに取得
# all_file_paths = get_all_file_paths(PDF_PATH) ⇒　ローカルにPDFがある場合に使用する
# 設定
split_f_path = r"C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\2Q-PoC\output"
extract_f_path = r"C:\Users\banqu\OneDrive\ドキュメント\勉強\RAG構築\2Q-PoC\output"
chunk_size = 1000
extract_keywords = []
new_file_name = "processed_document"

# 結果を保存するDataFrameを初期化
df = pd.DataFrame(columns=["filename", "title", "content", "tableinfo", "graphinfo"])
# df_for_remainder = pd.DataFrame(columns=["filename", "title", "content", "tableinfo", "graphinfo"])

# blob_urlsからファイル名だけを取り出す
file_names = [os.path.basename(url) for url in blob_urls]

for count, url in enumerate(tqdm(blob_urls, desc="Processing OCR")):  # tqdmでラップ
    print(f"{count+1}/{len(blob_urls)} 処理中")
    # OCR処理を実行
    result = perform_ocr(url, split_f_path=split_f_path,extract_f_path=extract_f_path,
                        chunk_size=1000, extract_keywords=[], new_file_name=os.path.basename(url))
    # 結果を分類しDataFrameに追加
    df = classify_and_append_to_df(result, df)

# dfとdf_for_remainderをマージ
# final_df = pd.concat([df, df_for_remainder], ignore_index=True)

# 最終的なDataFrameを表示
display(df)

2024-12-22 00:50:37,304 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf?restype=REDACTED&comp=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5253bd00-bfb3-11ef-ab24-30894aa4d14c'
    'Authorization': 'REDACTED'
No body was attached to the request
2024-12-22 00:50:38,883 - INFO - Response status: 200
Response headers:
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '69d80e0d-301e-00ee-01c0-535814000000'
    'x-ms-client-request-id': '5253bd00-bfb3-11ef-ab24-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:50:38 GMT'
Processing OCR:   0%|          | 0/445 [00:00<?, ?it/s]2024-12-22 00:50:38,978 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1_08-39_1%E7%AB%A0_%E5%85%83.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '53532d99-bfb3-11ef-975c-30894aa4d14c'
No body was attached to the request

1/445 処理中
コンテナ名: rag-pdf, Blob名: 1_08-39_1章_元.pdf

2024-12-22 00:50:39,750 - INFO - Response status: 206
Response headers:
    'Content-Length': '5451329'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Sat, 07 Dec 2024 14:22:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD16CAA023B01C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'abcf2d96-d01e-00a0-12c0-539df1000000'
    'x-ms-client-request-id': '53532d99-bfb3-11ef-975c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:50:39 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmscsuezn.pdf を作成しました。
Total pages in PDF: 32
OCR開始

Processing OCR:   0%|          | 1/445 [00:20<2:30:02, 20.28s/it]2024-12-22 00:50:59,254 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p1.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5f690cb7-bfb3-11ef-ad3d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
2ページ処理開始
3ページ処理開始
4ページ処理開始
5ページ処理開始
6ページ処理開始
7ページ処理開始
8ページ処理開始
9ページ処理開始
10ページ処理開始
11ページ処理開始
12ページ処理開始
13ページ処理開始
14ページ処理開始
15ページ処理開始
16ページ処理開始
17ページ処理開始
18ページ処理開始
19ページ処理開始
20ページ処理開始
21ページ処理開始
22ページ処理開始
23ページ処理開始
24ページ処理開始
25ページ処理開始
26ページ処理開始
27ページ処理開始
28ページ処理開始
29ページ処理開始
30ページ処理開始
31ページ処理開始
32ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmscsuezn.pdf を削除しました。
2/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p1.pdf

2024-12-22 00:50:59,961 - INFO - Response status: 206
Response headers:
    'Content-Length': '164916'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:07 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BDE75822"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '07d0ef9d-701e-0061-12c0-531648000000'
    'x-ms-client-request-id': '5f690cb7-bfb3-11ef-ad3d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:51:00 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_3dbj4om.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   0%|          | 2/445 [00:26<1:30:38, 12.28s/it]2024-12-22 00:51:05,930 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p10.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6363b08c-bfb3-11ef-a2f9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_3dbj4om.pdf を削除しました。
3/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p10.pdf

2024-12-22 00:51:06,663 - INFO - Response status: 206
Response headers:
    'Content-Length': '488716'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:59 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B92DBFDE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '36da12b2-001e-0080-78c0-53f13d000000'
    'x-ms-client-request-id': '6363b08c-bfb3-11ef-a2f9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:51:06 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpuz4u1o26.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   1%|          | 3/445 [00:34<1:13:12,  9.94s/it]2024-12-22 00:51:13,084 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p100.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '67a758ae-bfb3-11ef-9dc7-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpuz4u1o26.pdf を削除しました。
4/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p100.pdf

2024-12-22 00:51:13,825 - INFO - Response status: 206
Response headers:
    'Content-Length': '527709'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:09 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BF17568A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a0e316b1-901e-0085-24c0-530542000000'
    'x-ms-client-request-id': '67a758ae-bfb3-11ef-9dc7-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:51:13 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp1pbepd7w.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   1%|          | 4/445 [00:41<1:05:02,  8.85s/it]2024-12-22 00:51:20,265 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p101.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6bef10a9-bfb3-11ef-80f7-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp1pbepd7w.pdf を削除しました。
5/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p101.pdf

2024-12-22 00:51:21,003 - INFO - Response status: 206
Response headers:
    'Content-Length': '408339'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:10 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BF7208ED"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '729fdc77-101e-00f9-41c0-539877000000'
    'x-ms-client-request-id': '6bef10a9-bfb3-11ef-80f7-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:51:20 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptuts3r0u.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   1%|          | 5/445 [00:48<1:00:01,  8.19s/it]2024-12-22 00:51:27,273 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p102.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '701c7584-bfb3-11ef-b427-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptuts3r0u.pdf を削除しました。
6/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p102.pdf

2024-12-22 00:51:28,018 - INFO - Response status: 206
Response headers:
    'Content-Length': '501938'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:12 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C082E280"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '3f634edb-701e-00e9-1cc0-53ae91000000'
    'x-ms-client-request-id': '701c7584-bfb3-11ef-b427-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:51:27 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpppbkn0vs.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   1%|▏         | 6/445 [00:55<57:18,  7.83s/it]  2024-12-22 00:51:34,418 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p103.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '745e9fba-bfb3-11ef-9a26-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpppbkn0vs.pdf を削除しました。
7/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p103.pdf

2024-12-22 00:51:35,166 - INFO - Response status: 206
Response headers:
    'Content-Length': '574866'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:12 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C081F93C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4f4c9e54-e01e-0081-06c0-53f0c0000000'
    'x-ms-client-request-id': '745e9fba-bfb3-11ef-9a26-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:51:34 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk6bu8h67.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   2%|▏         | 7/445 [01:02<55:44,  7.64s/it]2024-12-22 00:51:41,652 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p104.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '78ae80e2-bfb3-11ef-a445-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk6bu8h67.pdf を削除しました。
8/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p104.pdf

2024-12-22 00:51:42,426 - INFO - Response status: 206
Response headers:
    'Content-Length': '455387'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:07 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BDA54232"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4345bfc2-301e-004f-70c0-53968f000000'
    'x-ms-client-request-id': '78ae80e2-bfb3-11ef-a445-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:51:42 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmppsbwu7wm.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   2%|▏         | 8/445 [01:09<54:36,  7.50s/it]2024-12-22 00:51:48,851 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p105.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7cf8dddc-bfb3-11ef-a06d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmppsbwu7wm.pdf を削除しました。
9/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p105.pdf

2024-12-22 00:51:49,568 - INFO - Response status: 206
Response headers:
    'Content-Length': '187068'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:06 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BD76EC35"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b21b2214-e01e-0046-07c0-538c01000000'
    'x-ms-client-request-id': '7cf8dddc-bfb3-11ef-a06d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:51:49 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpt5xkf691.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   2%|▏         | 9/445 [01:16<52:31,  7.23s/it]2024-12-22 00:51:55,492 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p106.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '80ee4192-bfb3-11ef-821b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpt5xkf691.pdf を削除しました。
10/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p106.pdf

2024-12-22 00:51:56,223 - INFO - Response status: 206
Response headers:
    'Content-Length': '517656'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:04 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BBF72BA6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9d9bb013-e01e-00ec-2fc0-535aee000000'
    'x-ms-client-request-id': '80ee4192-bfb3-11ef-821b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:51:55 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvh0uiio8.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   2%|▏         | 10/445 [01:23<51:55,  7.16s/it]2024-12-22 00:52:02,502 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p107.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '851bf3b7-bfb3-11ef-84b6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvh0uiio8.pdf を削除しました。
11/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p107.pdf

2024-12-22 00:52:03,215 - INFO - Response status: 206
Response headers:
    'Content-Length': '760032'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:04 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BC1F2025"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fbaa5b93-101e-00f2-1dc0-538003000000'
    'x-ms-client-request-id': '851bf3b7-bfb3-11ef-84b6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:52:02 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwklpbvd4.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   2%|▏         | 11/445 [01:30<51:39,  7.14s/it]2024-12-22 00:52:09,603 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p108.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '895759f6-bfb3-11ef-bebe-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwklpbvd4.pdf を削除しました。
12/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p108.pdf

2024-12-22 00:52:10,332 - INFO - Response status: 206
Response headers:
    'Content-Length': '455206'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:55 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B6D388DC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2e30a8d2-101e-009f-6bc0-532a2d000000'
    'x-ms-client-request-id': '895759f6-bfb3-11ef-bebe-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:52:10 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpek7h6t46.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   3%|▎         | 12/445 [01:37<51:13,  7.10s/it]2024-12-22 00:52:16,598 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p109.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8d82c49e-bfb3-11ef-93de-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpek7h6t46.pdf を削除しました。
13/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p109.pdf

2024-12-22 00:52:17,327 - INFO - Response status: 206
Response headers:
    'Content-Length': '629264'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:55 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B6C8E679"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6dfb86fc-201e-00fa-19c0-539b70000000'
    'x-ms-client-request-id': '8d82c49e-bfb3-11ef-93de-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:52:17 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpburh7wka.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   3%|▎         | 13/445 [01:44<51:21,  7.13s/it]2024-12-22 00:52:23,808 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p11.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '91cef188-bfb3-11ef-a82b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpburh7wka.pdf を削除しました。
14/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p11.pdf

2024-12-22 00:52:24,555 - INFO - Response status: 206
Response headers:
    'Content-Length': '437380'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:59 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B8D8D35B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '04746501-c01e-005a-08c0-535416000000'
    'x-ms-client-request-id': '91cef188-bfb3-11ef-a82b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:52:24 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgsu70vbx.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   3%|▎         | 14/445 [01:51<51:08,  7.12s/it]2024-12-22 00:52:30,895 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p110.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '96086608-bfb3-11ef-b189-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgsu70vbx.pdf を削除しました。
15/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p110.pdf

2024-12-22 00:52:31,625 - INFO - Response status: 206
Response headers:
    'Content-Length': '672846'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:06 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BD836157"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8e4aa292-501e-0010-5ac0-536471000000'
    'x-ms-client-request-id': '96086608-bfb3-11ef-b189-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:52:31 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpkwjhcp_y.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   3%|▎         | 15/445 [02:04<1:02:21,  8.70s/it]2024-12-22 00:52:43,264 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p111.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9d67ada9-bfb3-11ef-ab4c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpkwjhcp_y.pdf を削除しました。
16/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p111.pdf

2024-12-22 00:52:44,020 - INFO - Response status: 206
Response headers:
    'Content-Length': '424912'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:07 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BD8CF37E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e34b1680-301e-00aa-34c0-538478000000'
    'x-ms-client-request-id': '9d67ada9-bfb3-11ef-ab4c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:52:43 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpq_r1tjng.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   4%|▎         | 16/445 [02:11<58:31,  8.19s/it]  2024-12-22 00:52:50,254 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p112.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a1923d42-bfb3-11ef-9f13-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpq_r1tjng.pdf を削除しました。
17/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p112.pdf

2024-12-22 00:52:50,986 - INFO - Response status: 206
Response headers:
    'Content-Length': '850602'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:04 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BBEEA9C6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a93ab22a-501e-00dc-50c0-5300c4000000'
    'x-ms-client-request-id': 'a1923d42-bfb3-11ef-9f13-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:52:50 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3wjbc26h.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   4%|▍         | 17/445 [02:18<56:29,  7.92s/it]2024-12-22 00:52:57,551 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p113.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a5ebb2f8-bfb3-11ef-a96d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3wjbc26h.pdf を削除しました。
18/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p113.pdf

2024-12-22 00:52:58,292 - INFO - Response status: 206
Response headers:
    'Content-Length': '582730'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:04 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BC2DB5CA"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '5f06d211-801e-003b-60c0-5310c9000000'
    'x-ms-client-request-id': 'a5ebb2f8-bfb3-11ef-a96d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:52:57 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpikvse8e0.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   4%|▍         | 18/445 [02:25<54:47,  7.70s/it]2024-12-22 00:53:04,740 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p114.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'aa34a299-bfb3-11ef-abfc-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpikvse8e0.pdf を削除しました。
19/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p114.pdf

2024-12-22 00:53:05,477 - INFO - Response status: 206
Response headers:
    'Content-Length': '515250'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:09 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BEEC5832"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b1a18091-b01e-0099-44c0-53dd55000000'
    'x-ms-client-request-id': 'aa34a299-bfb3-11ef-abfc-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:53:04 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvzeypc4t.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   4%|▍         | 19/445 [02:32<53:33,  7.54s/it]2024-12-22 00:53:11,923 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p115.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ae7cac01-bfb3-11ef-b1fb-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvzeypc4t.pdf を削除しました。
20/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p115.pdf

2024-12-22 00:53:12,665 - INFO - Response status: 206
Response headers:
    'Content-Length': '679557'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:10 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BF537FAB"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9ad56a1f-e01e-006f-7fc0-53fa43000000'
    'x-ms-client-request-id': 'ae7cac01-bfb3-11ef-b1fb-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:53:12 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4oppa6_g.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   4%|▍         | 20/445 [02:40<52:47,  7.45s/it]2024-12-22 00:53:19,162 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p116.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b2cd41a2-bfb3-11ef-8f0c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4oppa6_g.pdf を削除しました。
21/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p116.pdf

2024-12-22 00:53:19,889 - INFO - Response status: 206
Response headers:
    'Content-Length': '616232'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:12 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C08C4DC6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2259f37b-301e-0000-22c0-535297000000'
    'x-ms-client-request-id': 'b2cd41a2-bfb3-11ef-8f0c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:53:19 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmnpfque4.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   5%|▍         | 21/445 [02:47<52:07,  7.38s/it]2024-12-22 00:53:26,357 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p117.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b7172336-bfb3-11ef-9ea4-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmnpfque4.pdf を削除しました。
22/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p117.pdf

2024-12-22 00:53:27,100 - INFO - Response status: 206
Response headers:
    'Content-Length': '669573'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:11 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C065B74B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2494e695-a01e-00e0-15c0-53b41f000000'
    'x-ms-client-request-id': 'b7172336-bfb3-11ef-9ea4-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:53:27 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp78a_lqnr.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   5%|▍         | 22/445 [02:54<51:37,  7.32s/it]2024-12-22 00:53:33,557 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p118.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'bb61d5df-bfb3-11ef-ab7d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp78a_lqnr.pdf を削除しました。
23/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p118.pdf

2024-12-22 00:53:34,308 - INFO - Response status: 206
Response headers:
    'Content-Length': '457116'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B5389690"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cfa799cd-701e-00cb-12c0-53c0a7000000'
    'x-ms-client-request-id': 'bb61d5df-bfb3-11ef-ab7d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:53:34 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpaf3jtp6x.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   5%|▌         | 23/445 [03:01<50:57,  7.25s/it]2024-12-22 00:53:40,624 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p119.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'bf981101-bfb3-11ef-8ad7-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpaf3jtp6x.pdf を削除しました。
24/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p119.pdf

2024-12-22 00:53:41,374 - INFO - Response status: 206
Response headers:
    'Content-Length': '563495'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B5AEC859"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '196489f4-d01e-004e-14c0-539772000000'
    'x-ms-client-request-id': 'bf981101-bfb3-11ef-8ad7-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:53:41 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk9528w7w.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   5%|▌         | 24/445 [03:08<50:53,  7.25s/it]2024-12-22 00:53:47,895 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p12.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c3ed9bd3-bfb3-11ef-8547-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk9528w7w.pdf を削除しました。
25/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p12.pdf

2024-12-22 00:53:48,641 - INFO - Response status: 206
Response headers:
    'Content-Length': '486956'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:59 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B92BED3B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ad43af6f-e01e-00c5-06c0-532cac000000'
    'x-ms-client-request-id': 'c3ed9bd3-bfb3-11ef-8547-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:53:48 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpggoeioc2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   6%|▌         | 25/445 [03:15<50:20,  7.19s/it]2024-12-22 00:53:54,946 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p120.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c8217642-bfb3-11ef-80b5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpggoeioc2.pdf を削除しました。
26/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p120.pdf

2024-12-22 00:53:55,721 - INFO - Response status: 206
Response headers:
    'Content-Length': '629794'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:56 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B6FF9775"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'abd07e6b-d01e-00a0-58c0-539df1000000'
    'x-ms-client-request-id': 'c8217642-bfb3-11ef-80b5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:53:55 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6zewsn03.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   6%|▌         | 26/445 [03:23<50:17,  7.20s/it]2024-12-22 00:54:02,165 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p121.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'cc6f0a83-bfb3-11ef-b7c9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6zewsn03.pdf を削除しました。
27/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p121.pdf

2024-12-22 00:54:02,949 - INFO - Response status: 206
Response headers:
    'Content-Length': '653438'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:55 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B6C62A59"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd929559d-301e-00c7-5bc0-532e56000000'
    'x-ms-client-request-id': 'cc6f0a83-bfb3-11ef-b7c9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:54:03 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptr2e6m9g.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   6%|▌         | 27/445 [03:30<50:23,  7.23s/it]2024-12-22 00:54:09,472 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p122.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd0ca1186-bfb3-11ef-b474-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptr2e6m9g.pdf を削除しました。
28/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p122.pdf

2024-12-22 00:54:10,221 - INFO - Response status: 206
Response headers:
    'Content-Length': '588176'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B7DE010E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '0a243b50-101e-003e-2ec0-53e4b6000000'
    'x-ms-client-request-id': 'd0ca1186-bfb3-11ef-b474-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:54:09 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpt69zfgxi.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   6%|▋         | 28/445 [03:37<50:13,  7.23s/it]2024-12-22 00:54:16,689 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p123.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd5172fb7-bfb3-11ef-a29d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpt69zfgxi.pdf を削除しました。
29/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p123.pdf

2024-12-22 00:54:17,423 - INFO - Response status: 206
Response headers:
    'Content-Length': '451442'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B7E0E3FF"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '820ec976-a01e-002c-1dc0-53d0aa000000'
    'x-ms-client-request-id': 'd5172fb7-bfb3-11ef-a29d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:54:16 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphvy_jp16.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   7%|▋         | 29/445 [03:44<49:33,  7.15s/it]2024-12-22 00:54:23,649 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p124.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd93d434b-bfb3-11ef-9de0-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphvy_jp16.pdf を削除しました。
30/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p124.pdf

2024-12-22 00:54:24,410 - INFO - Response status: 206
Response headers:
    'Content-Length': '842233'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B572ED06"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '38f75b33-b01e-00dd-69c0-530139000000'
    'x-ms-client-request-id': 'd93d434b-bfb3-11ef-9de0-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:54:24 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwrezawkw.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   7%|▋         | 30/445 [03:51<49:42,  7.19s/it]2024-12-22 00:54:30,926 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p125.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'dd93908b-bfb3-11ef-827f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwrezawkw.pdf を削除しました。
31/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p125.pdf

2024-12-22 00:54:31,636 - INFO - Response status: 206
Response headers:
    'Content-Length': '519685'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B5A6BB25"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '07d23e9e-701e-0061-32c0-531648000000'
    'x-ms-client-request-id': 'dd93908b-bfb3-11ef-827f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:54:31 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphktp7_xl.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   7%|▋         | 31/445 [03:58<49:06,  7.12s/it]2024-12-22 00:54:37,881 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p126.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e1b8f056-bfb3-11ef-bec8-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphktp7_xl.pdf を削除しました。
32/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p126.pdf

2024-12-22 00:54:38,634 - INFO - Response status: 206
Response headers:
    'Content-Length': '513565'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:51 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B46BA58D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '230a9f5d-d01e-0028-33c0-532528000000'
    'x-ms-client-request-id': 'e1b8f056-bfb3-11ef-bec8-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:54:38 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmppaaa3bxg.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   7%|▋         | 32/445 [04:06<49:17,  7.16s/it]2024-12-22 00:54:45,148 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p127.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e60db73b-bfb3-11ef-b731-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmppaaa3bxg.pdf を削除しました。
33/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p127.pdf

2024-12-22 00:54:46,331 - INFO - Response status: 206
Response headers:
    'Content-Length': '153528'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:50 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B3D20DFA"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9c1cfb1c-b01e-00ff-7dc0-536f0f000000'
    'x-ms-client-request-id': 'e60db73b-bfb3-11ef-b731-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:54:45 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvij8jior.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   7%|▋         | 33/445 [04:13<49:04,  7.15s/it]2024-12-22 00:54:52,261 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p128.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ea4b1d0a-bfb3-11ef-b129-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvij8jior.pdf を削除しました。
34/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p128.pdf

2024-12-22 00:54:53,026 - INFO - Response status: 206
Response headers:
    'Content-Length': '558936'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:09 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BF2EE2BB"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '7188e589-901e-000d-31c0-53bd9b000000'
    'x-ms-client-request-id': 'ea4b1d0a-bfb3-11ef-b129-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:54:52 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk55qjxxr.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   8%|▊         | 34/445 [04:20<49:13,  7.19s/it]2024-12-22 00:54:59,540 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p129.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'eea1cf74-bfb3-11ef-8792-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk55qjxxr.pdf を削除しました。
35/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p129.pdf

2024-12-22 00:55:00,290 - INFO - Response status: 206
Response headers:
    'Content-Length': '745420'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:10 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BF50C3A2"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '39421a7c-d01e-00cd-7fc0-5337df000000'
    'x-ms-client-request-id': 'eea1cf74-bfb3-11ef-8792-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:55:00 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphm6xr9f9.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   8%|▊         | 35/445 [04:27<49:08,  7.19s/it]2024-12-22 00:55:06,746 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p13.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f2ed25ce-bfb3-11ef-9b83-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphm6xr9f9.pdf を削除しました。
36/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p13.pdf

2024-12-22 00:55:07,484 - INFO - Response status: 206
Response headers:
    'Content-Length': '353511'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:58 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B88E8940"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '25b3fc3d-901e-0060-0ac0-5317b5000000'
    'x-ms-client-request-id': 'f2ed25ce-bfb3-11ef-9b83-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:55:07 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6ug8iug0.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   8%|▊         | 36/445 [04:34<48:32,  7.12s/it]2024-12-22 00:55:13,700 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p130.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f71239d9-bfb3-11ef-843f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6ug8iug0.pdf を削除しました。
37/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p130.pdf

2024-12-22 00:55:14,423 - INFO - Response status: 206
Response headers:
    'Content-Length': '593803'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:54 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B606E5A8"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '440818e3-801e-00fc-4ec0-536c08000000'
    'x-ms-client-request-id': 'f71239d9-bfb3-11ef-843f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:55:14 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9ry0_wfn.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   8%|▊         | 37/445 [04:41<48:34,  7.14s/it]2024-12-22 00:55:20,893 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p131.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'fb5c0111-bfb3-11ef-b609-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9ry0_wfn.pdf を削除しました。
38/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p131.pdf

2024-12-22 00:55:21,631 - INFO - Response status: 206
Response headers:
    'Content-Length': '632269'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B5B1D23B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '5e690e3d-001e-0065-6bc0-53e3ca000000'
    'x-ms-client-request-id': 'fb5c0111-bfb3-11ef-b609-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:55:21 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0y61kzm0.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   9%|▊         | 38/445 [04:49<48:37,  7.17s/it]2024-12-22 00:55:28,117 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p132.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ffaa5012-bfb3-11ef-ad92-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0y61kzm0.pdf を削除しました。
39/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p132.pdf

2024-12-22 00:55:28,858 - INFO - Response status: 206
Response headers:
    'Content-Length': '564362'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:52 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B4B1D587"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2717e269-c01e-00d2-68c0-53eccf000000'
    'x-ms-client-request-id': 'ffaa5012-bfb3-11ef-ad92-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:55:29 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb2ny0zgo.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   9%|▉         | 39/445 [04:56<48:35,  7.18s/it]2024-12-22 00:55:35,332 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p133.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '03f7225b-bfb4-11ef-b359-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb2ny0zgo.pdf を削除しました。
40/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p133.pdf

2024-12-22 00:55:36,084 - INFO - Response status: 206
Response headers:
    'Content-Length': '532371'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:51 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B3FBD53A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '76c070c1-f01e-00f3-7ac0-5381fe000000'
    'x-ms-client-request-id': '03f7225b-bfb4-11ef-b359-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:55:35 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp187zp8ux.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   9%|▉         | 40/445 [05:03<48:30,  7.19s/it]2024-12-22 00:55:42,533 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p134.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0841ee2f-bfb4-11ef-b23b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp187zp8ux.pdf を削除しました。
41/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p134.pdf

2024-12-22 00:55:43,277 - INFO - Response status: 206
Response headers:
    'Content-Length': '516178'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:55 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B6D44B50"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9068c721-001e-00cf-08c0-533525000000'
    'x-ms-client-request-id': '0841ee2f-bfb4-11ef-b23b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:55:43 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp69qcl6r3.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   9%|▉         | 41/445 [05:10<48:03,  7.14s/it]2024-12-22 00:55:49,549 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p135.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0c707e41-bfb4-11ef-abd3-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp69qcl6r3.pdf を削除しました。
42/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p135.pdf

2024-12-22 00:55:50,279 - INFO - Response status: 206
Response headers:
    'Content-Length': '455351'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:55 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B6AB9464"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b59cef6c-401e-0100-28c0-5314c2000000'
    'x-ms-client-request-id': '0c707e41-bfb4-11ef-abd3-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:55:49 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3nzqvb80.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:   9%|▉         | 42/445 [05:17<47:43,  7.11s/it]2024-12-22 00:55:56,590 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p136.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '10a2bc98-bfb4-11ef-bc71-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3nzqvb80.pdf を削除しました。
43/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p136.pdf

2024-12-22 00:55:57,336 - INFO - Response status: 206
Response headers:
    'Content-Length': '63011'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B7B3C520"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fd610c5c-201e-009c-4cc0-53292a000000'
    'x-ms-client-request-id': '10a2bc98-bfb4-11ef-bc71-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:55:56 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5_xpv356.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  10%|▉         | 43/445 [05:24<46:20,  6.92s/it]2024-12-22 00:56:03,063 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p14.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '147ea292-bfb4-11ef-a5ab-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5_xpv356.pdf を削除しました。
44/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p14.pdf

2024-12-22 00:56:03,809 - INFO - Response status: 206
Response headers:
    'Content-Length': '488789'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:00 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B9B0B49F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '98f535af-c01e-0037-1ec0-53fe38000000'
    'x-ms-client-request-id': '147ea292-bfb4-11ef-a5ab-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:56:04 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpt0f5qil1.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  10%|▉         | 44/445 [05:31<46:31,  6.96s/it]2024-12-22 00:56:10,125 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p15.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '18b402b1-bfb4-11ef-92dc-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpt0f5qil1.pdf を削除しました。
45/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p15.pdf

2024-12-22 00:56:10,837 - INFO - Response status: 206
Response headers:
    'Content-Length': '355921'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:59 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B94304C9"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fbac07cc-101e-00f2-6fc0-538003000000'
    'x-ms-client-request-id': '18b402b1-bfb4-11ef-92dc-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:56:10 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5a236a7y.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  10%|█         | 45/445 [05:38<46:26,  6.97s/it]2024-12-22 00:56:17,107 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p16.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1cdd59eb-bfb4-11ef-8e45-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5a236a7y.pdf を削除しました。
46/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p16.pdf

2024-12-22 00:56:17,860 - INFO - Response status: 206
Response headers:
    'Content-Length': '492636'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:00 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B9C27AEC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '39f2c063-801e-005d-0ac0-53a293000000'
    'x-ms-client-request-id': '1cdd59eb-bfb4-11ef-8e45-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:56:17 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvff0d15o.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  10%|█         | 46/445 [05:45<46:45,  7.03s/it]2024-12-22 00:56:24,286 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p17.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2124eaf3-bfb4-11ef-aff5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvff0d15o.pdf を削除しました。
47/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p17.pdf

2024-12-22 00:56:25,003 - INFO - Response status: 206
Response headers:
    'Content-Length': '354547'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:00 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B9C3D8F8"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '333a277c-301e-0066-42c0-53e0cd000000'
    'x-ms-client-request-id': '2124eaf3-bfb4-11ef-aff5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:56:24 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpaoslinqs.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  11%|█         | 47/445 [05:52<46:27,  7.00s/it]2024-12-22 00:56:31,226 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p18.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2547fe4a-bfb4-11ef-9dd5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpaoslinqs.pdf を削除しました。
48/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p18.pdf

2024-12-22 00:56:31,977 - INFO - Response status: 206
Response headers:
    'Content-Length': '486730'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:02 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BAC29E75"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '7d8b6c39-d01e-0001-7dc0-53536a000000'
    'x-ms-client-request-id': '2547fe4a-bfb4-11ef-9dd5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:56:31 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0vs9d_ll.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  11%|█         | 48/445 [05:59<46:34,  7.04s/it]2024-12-22 00:56:38,347 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p19.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '298674ea-bfb4-11ef-ad91-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0vs9d_ll.pdf を削除しました。
49/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p19.pdf

2024-12-22 00:56:39,087 - INFO - Response status: 206
Response headers:
    'Content-Length': '353437'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:01 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BA3F82DB"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fdc5f94f-b01e-007c-2dc0-53cfa2000000'
    'x-ms-client-request-id': '298674ea-bfb4-11ef-ad91-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:56:38 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphjyxrk0y.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  11%|█         | 49/445 [06:06<46:32,  7.05s/it]2024-12-22 00:56:45,427 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p2.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2dbec1a3-bfb4-11ef-bdee-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphjyxrk0y.pdf を削除しました。
50/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p2.pdf

2024-12-22 00:56:46,156 - INFO - Response status: 206
Response headers:
    'Content-Length': '688274'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:04 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BC31CFDC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '1a263913-b01e-001a-0bc0-537df8000000'
    'x-ms-client-request-id': '2dbec1a3-bfb4-11ef-bdee-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:56:45 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfpb2iwq8.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  11%|█         | 50/445 [06:18<56:48,  8.63s/it]2024-12-22 00:56:57,735 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p20.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3514f42e-bfb4-11ef-a01d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfpb2iwq8.pdf を削除しました。
51/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p20.pdf

2024-12-22 00:56:58,481 - INFO - Response status: 206
Response headers:
    'Content-Length': '489834'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:02 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BAC5339E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '03ad3413-101e-00bd-39c0-53441b000000'
    'x-ms-client-request-id': '3514f42e-bfb4-11ef-a01d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:56:58 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpw6k5d60f.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  11%|█▏        | 51/445 [06:25<53:26,  8.14s/it]2024-12-22 00:57:04,733 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p21.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3940c5dc-bfb4-11ef-9183-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpw6k5d60f.pdf を削除しました。
52/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p21.pdf

2024-12-22 00:57:05,459 - INFO - Response status: 206
Response headers:
    'Content-Length': '354839'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:02 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BB11C50D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e34cf309-301e-00aa-34c0-538478000000'
    'x-ms-client-request-id': '3940c5dc-bfb4-11ef-9183-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:57:05 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpq3gxrcdn.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  12%|█▏        | 52/445 [06:32<51:04,  7.80s/it]2024-12-22 00:57:11,733 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p22.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3d6cc068-bfb4-11ef-82a2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpq3gxrcdn.pdf を削除しました。
53/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p22.pdf

2024-12-22 00:57:12,460 - INFO - Response status: 206
Response headers:
    'Content-Length': '488086'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:03 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BB3E4851"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8ae13d80-401e-00a5-33c0-53698e000000'
    'x-ms-client-request-id': '3d6cc068-bfb4-11ef-82a2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:57:12 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpnfhika4l.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  12%|█▏        | 53/445 [06:39<49:17,  7.55s/it]2024-12-22 00:57:18,692 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p23.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4192a49a-bfb4-11ef-86bf-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpnfhika4l.pdf を削除しました。
54/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p23.pdf

2024-12-22 00:57:19,426 - INFO - Response status: 206
Response headers:
    'Content-Length': '354116'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:03 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BB35040C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '427be3c0-501e-00fe-1ac1-536ef2000000'
    'x-ms-client-request-id': '4192a49a-bfb4-11ef-86bf-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:57:19 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp94vaz_ph.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  12%|█▏        | 54/445 [06:46<48:17,  7.41s/it]2024-12-22 00:57:25,790 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p24.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '45cda0b5-bfb4-11ef-9fe1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp94vaz_ph.pdf を削除しました。
55/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p24.pdf

2024-12-22 00:57:26,514 - INFO - Response status: 206
Response headers:
    'Content-Length': '305632'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:02 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BAB5401B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b5bdfd50-701e-00c0-16c1-53d8d3000000'
    'x-ms-client-request-id': '45cda0b5-bfb4-11ef-9fe1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:57:26 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpa2laj212.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  12%|█▏        | 55/445 [06:53<47:27,  7.30s/it]2024-12-22 00:57:32,836 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p25.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4a00d657-bfb4-11ef-982c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpa2laj212.pdf を削除しました。
56/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p25.pdf

2024-12-22 00:57:33,550 - INFO - Response status: 206
Response headers:
    'Content-Length': '223761'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:01 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BA3A0ABE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9a901a61-601e-00b9-7cc1-53b199000000'
    'x-ms-client-request-id': '4a00d657-bfb4-11ef-982c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:57:33 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3bui7wxm.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  13%|█▎        | 56/445 [07:00<46:12,  7.13s/it]2024-12-22 00:57:39,555 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p26.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4e022738-bfb4-11ef-ad2c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3bui7wxm.pdf を削除しました。
57/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p26.pdf

2024-12-22 00:57:40,285 - INFO - Response status: 206
Response headers:
    'Content-Length': '306690'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:00 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B9E7B36E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fdc2f556-301e-0088-20c1-53ea4e000000'
    'x-ms-client-request-id': '4e022738-bfb4-11ef-ad2c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:57:39 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpz67r4rd1.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  13%|█▎        | 57/445 [07:07<45:44,  7.07s/it]2024-12-22 00:57:46,506 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p27.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5226c2b4-bfb4-11ef-8d83-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpz67r4rd1.pdf を削除しました。
58/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p27.pdf

2024-12-22 00:57:47,232 - INFO - Response status: 206
Response headers:
    'Content-Length': '223399'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:01 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B9F78029"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '567b12e9-101e-00db-11c1-53f641000000'
    'x-ms-client-request-id': '5226c2b4-bfb4-11ef-8d83-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:57:47 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfnsmg2sp.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  13%|█▎        | 58/445 [07:14<44:57,  6.97s/it]2024-12-22 00:57:53,237 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p28.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5629a7f8-bfb4-11ef-9959-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfnsmg2sp.pdf を削除しました。
59/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p28.pdf

2024-12-22 00:57:53,974 - INFO - Response status: 206
Response headers:
    'Content-Length': '307191'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:00 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B99707E0"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '5295159f-f01e-00bc-13c1-5345e6000000'
    'x-ms-client-request-id': '5629a7f8-bfb4-11ef-9959-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:57:53 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpahdf0c89.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  13%|█▎        | 59/445 [07:21<44:54,  6.98s/it]2024-12-22 00:58:00,238 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p29.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5a5604f2-bfb4-11ef-b452-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpahdf0c89.pdf を削除しました。
60/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p29.pdf

2024-12-22 00:58:00,964 - INFO - Response status: 206
Response headers:
    'Content-Length': '225921'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:59 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B935F400"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f7da909b-901e-00e8-16c1-53af6c000000'
    'x-ms-client-request-id': '5a5604f2-bfb4-11ef-b452-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:58:00 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpiddqn91g.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  13%|█▎        | 60/445 [07:28<44:26,  6.93s/it]2024-12-22 00:58:07,040 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p3.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5e64121c-bfb4-11ef-a6ec-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpiddqn91g.pdf を削除しました。
61/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p3.pdf

2024-12-22 00:58:07,787 - INFO - Response status: 206
Response headers:
    'Content-Length': '576164'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:04 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BBD6F698"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8285742f-001e-00ed-18c1-535b13000000'
    'x-ms-client-request-id': '5e64121c-bfb4-11ef-a6ec-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:58:07 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpkhmcv2qc.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  14%|█▎        | 61/445 [07:35<44:54,  7.02s/it]2024-12-22 00:58:14,263 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p30.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '62b23768-bfb4-11ef-b02a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpkhmcv2qc.pdf を削除しました。
62/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p30.pdf

2024-12-22 00:58:14,998 - INFO - Response status: 206
Response headers:
    'Content-Length': '202377'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:01 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BA893164"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'da244456-a01e-00c9-5dc1-53c25d000000'
    'x-ms-client-request-id': '62b23768-bfb4-11ef-b02a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:58:14 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp1evocamu.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  14%|█▍        | 62/445 [07:41<44:11,  6.92s/it]2024-12-22 00:58:20,972 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p31.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '66b1da9b-bfb4-11ef-be84-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp1evocamu.pdf を削除しました。
63/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p31.pdf

2024-12-22 00:58:21,717 - INFO - Response status: 206
Response headers:
    'Content-Length': '301136'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:01 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BA3BB687"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '15e591c9-f01e-0070-6dc1-532153000000'
    'x-ms-client-request-id': '66b1da9b-bfb4-11ef-be84-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:58:21 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwr7kh65z.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  14%|█▍        | 63/445 [07:48<44:02,  6.92s/it]2024-12-22 00:58:27,872 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p32.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6aceaa05-bfb4-11ef-8ad2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwr7kh65z.pdf を削除しました。
64/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p32.pdf

2024-12-22 00:58:28,618 - INFO - Response status: 206
Response headers:
    'Content-Length': '572290'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:00 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B9CA3A69"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cbcd22bc-101e-0017-57c1-5392f4000000'
    'x-ms-client-request-id': '6aceaa05-bfb4-11ef-8ad2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:58:28 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpysddu3tz.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  14%|█▍        | 64/445 [07:56<44:24,  6.99s/it]2024-12-22 00:58:35,045 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p33.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6f1531a7-bfb4-11ef-91e7-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpysddu3tz.pdf を削除しました。
65/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p33.pdf

2024-12-22 00:58:35,804 - INFO - Response status: 206
Response headers:
    'Content-Length': '858228'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:01 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BA33F71E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'feee29ba-801e-009a-2fc1-53de52000000'
    'x-ms-client-request-id': '6f1531a7-bfb4-11ef-91e7-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:58:35 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6x6mq_l5.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  15%|█▍        | 65/445 [08:03<44:51,  7.08s/it]2024-12-22 00:58:42,333 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p34.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '736d302b-bfb4-11ef-8061-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6x6mq_l5.pdf を削除しました。
66/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p34.pdf

2024-12-22 00:58:43,090 - INFO - Response status: 206
Response headers:
    'Content-Length': '475932'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:02 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BAC44A4A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a2ec312d-c01e-0078-3dc1-533a20000000'
    'x-ms-client-request-id': '736d302b-bfb4-11ef-8061-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:58:42 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp68lbwwxg.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  15%|█▍        | 66/445 [08:10<45:01,  7.13s/it]2024-12-22 00:58:49,566 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p35.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '77bcf375-bfb4-11ef-9c6a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp68lbwwxg.pdf を削除しました。
67/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p35.pdf

2024-12-22 00:58:50,308 - INFO - Response status: 206
Response headers:
    'Content-Length': '668914'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:02 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BB0D841D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2610895c-601e-0057-05c1-53bb1a000000'
    'x-ms-client-request-id': '77bcf375-bfb4-11ef-9c6a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:58:50 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpu1hv84aw.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  15%|█▌        | 67/445 [08:17<45:03,  7.15s/it]2024-12-22 00:58:56,773 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p36.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7c08a385-bfb4-11ef-8b18-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpu1hv84aw.pdf を削除しました。
68/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p36.pdf

2024-12-22 00:58:57,523 - INFO - Response status: 206
Response headers:
    'Content-Length': '432307'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:03 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BB66FF55"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6d5faca2-901e-00ca-39c1-53c15a000000'
    'x-ms-client-request-id': '7c08a385-bfb4-11ef-8b18-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:58:57 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2w8cplhx.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  15%|█▌        | 68/445 [08:24<44:35,  7.10s/it]2024-12-22 00:59:03,742 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p37.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '802ffec0-bfb4-11ef-a45a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2w8cplhx.pdf を削除しました。
69/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p37.pdf

2024-12-22 00:59:04,491 - INFO - Response status: 206
Response headers:
    'Content-Length': '596655'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:03 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BB3E4851"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9a3aab09-c01e-001e-03c1-53887a000000'
    'x-ms-client-request-id': '802ffec0-bfb4-11ef-a45a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:59:03 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmh9f1813.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  16%|█▌        | 69/445 [08:31<44:39,  7.13s/it]2024-12-22 00:59:10,939 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p38.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '847a46b3-bfb4-11ef-bceb-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmh9f1813.pdf を削除しました。
70/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p38.pdf

2024-12-22 00:59:11,666 - INFO - Response status: 206
Response headers:
    'Content-Length': '464800'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:59 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B932758F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '25b5c34b-901e-0060-05c1-5317b5000000'
    'x-ms-client-request-id': '847a46b3-bfb4-11ef-bceb-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:59:11 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpp49llhf_.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  16%|█▌        | 70/445 [08:38<44:19,  7.09s/it]2024-12-22 00:59:17,952 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p39.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '88a83b17-bfb4-11ef-8a52-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpp49llhf_.pdf を削除しました。
71/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p39.pdf

2024-12-22 00:59:18,699 - INFO - Response status: 206
Response headers:
    'Content-Length': '488512'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:59 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B8DC0419"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4409940c-801e-00fc-46c1-536c08000000'
    'x-ms-client-request-id': '88a83b17-bfb4-11ef-8a52-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:59:17 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvm692097.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  16%|█▌        | 71/445 [08:46<44:35,  7.15s/it]2024-12-22 00:59:25,244 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p4.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8d00f842-bfb4-11ef-aeb9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvm692097.pdf を削除しました。
72/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p4.pdf

2024-12-22 00:59:25,993 - INFO - Response status: 206
Response headers:
    'Content-Length': '536407'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:10 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BF7208ED"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '76de6b9f-a01e-0086-48c1-530645000000'
    'x-ms-client-request-id': '8d00f842-bfb4-11ef-aeb9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:59:25 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpw3hmj9xy.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  16%|█▌        | 72/445 [08:53<44:36,  7.18s/it]2024-12-22 00:59:32,474 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p40.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '91503909-bfb4-11ef-8e90-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpw3hmj9xy.pdf を削除しました。
73/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p40.pdf

2024-12-22 00:59:33,205 - INFO - Response status: 206
Response headers:
    'Content-Length': '489877'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:11 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BFED6503"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f59f3695-001e-006e-0ac1-53fbbe000000'
    'x-ms-client-request-id': '91503909-bfb4-11ef-8e90-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:59:32 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp8xfx1i_b.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  16%|█▋        | 73/445 [09:00<44:17,  7.14s/it]2024-12-22 00:59:39,539 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p41.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '95863751-bfb4-11ef-96f9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp8xfx1i_b.pdf を削除しました。
74/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p41.pdf

2024-12-22 00:59:40,262 - INFO - Response status: 206
Response headers:
    'Content-Length': '558460'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:12 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C10624F7"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e15b6ef6-001e-0003-77c1-535190000000'
    'x-ms-client-request-id': '95863751-bfb4-11ef-96f9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:59:40 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpr0zzerm_.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  17%|█▋        | 74/445 [09:07<44:17,  7.16s/it]2024-12-22 00:59:46,750 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p42.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '99d28d8b-bfb4-11ef-9b6f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpr0zzerm_.pdf を削除しました。
75/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p42.pdf

2024-12-22 00:59:47,479 - INFO - Response status: 206
Response headers:
    'Content-Length': '439794'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:10 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BFE1D935"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4cff8d5d-101e-001c-57c1-538a80000000'
    'x-ms-client-request-id': '99d28d8b-bfb4-11ef-9b6f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:59:47 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4z1v8sns.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  17%|█▋        | 75/445 [09:14<43:51,  7.11s/it]2024-12-22 00:59:53,742 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p43.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9dfd8145-bfb4-11ef-9ff8-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4z1v8sns.pdf を削除しました。
76/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p43.pdf

2024-12-22 00:59:54,481 - INFO - Response status: 206
Response headers:
    'Content-Length': '927591'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:08 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BE58FB27"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '906bc013-001e-00cf-72c1-533525000000'
    'x-ms-client-request-id': '9dfd8145-bfb4-11ef-9ff8-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 15:59:54 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjh36pd7j.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  17%|█▋        | 76/445 [09:21<43:54,  7.14s/it]2024-12-22 01:00:00,950 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p44.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a2495729-bfb4-11ef-bd1a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjh36pd7j.pdf を削除しました。
77/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p44.pdf

2024-12-22 01:00:01,654 - INFO - Response status: 206
Response headers:
    'Content-Length': '524717'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:05 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BCCA304B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b59ee54b-401e-0100-36c1-5314c2000000'
    'x-ms-client-request-id': 'a2495729-bfb4-11ef-bd1a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:00:01 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpkssnio_r.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  17%|█▋        | 77/445 [09:29<43:46,  7.14s/it]2024-12-22 01:00:08,077 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p45.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a688c28a-bfb4-11ef-8468-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpkssnio_r.pdf を削除しました。
78/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p45.pdf

2024-12-22 01:00:08,810 - INFO - Response status: 206
Response headers:
    'Content-Length': '655309'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:04 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BBBCFC10"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '864c9c89-b01e-0055-6dc1-53b9e0000000'
    'x-ms-client-request-id': 'a688c28a-bfb4-11ef-8468-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:00:08 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp47pf7wl3.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  18%|█▊        | 78/445 [09:36<43:44,  7.15s/it]2024-12-22 01:00:15,267 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p46.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'aad1d39e-bfb4-11ef-bdb1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp47pf7wl3.pdf を削除しました。
79/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p46.pdf

2024-12-22 01:00:16,012 - INFO - Response status: 206
Response headers:
    'Content-Length': '587542'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:05 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BCD3C27F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'bbfe0fe0-401e-0004-6ec1-53a715000000'
    'x-ms-client-request-id': 'aad1d39e-bfb4-11ef-bdb1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:00:15 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmph241xs8o.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  18%|█▊        | 79/445 [09:43<43:47,  7.18s/it]2024-12-22 01:00:22,511 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p47.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'af233f2c-bfb4-11ef-9801-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmph241xs8o.pdf を削除しました。
80/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p47.pdf

2024-12-22 01:00:23,272 - INFO - Response status: 206
Response headers:
    'Content-Length': '451731'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:08 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BE2112F1"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '98f6fe72-c01e-0037-11c1-53fe38000000'
    'x-ms-client-request-id': 'af233f2c-bfb4-11ef-9801-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:00:23 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp47jcfaki.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  18%|█▊        | 80/445 [09:50<43:28,  7.15s/it]2024-12-22 01:00:29,583 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p48.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b35a4298-bfb4-11ef-96f9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp47jcfaki.pdf を削除しました。
81/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p48.pdf

2024-12-22 01:00:30,322 - INFO - Response status: 206
Response headers:
    'Content-Length': '63175'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B7E1A671"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '36df3b53-001e-0080-04c1-53f13d000000'
    'x-ms-client-request-id': 'b35a4298-bfb4-11ef-96f9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:00:30 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5lxjuhjo.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  18%|█▊        | 81/445 [09:57<42:08,  6.95s/it]2024-12-22 01:00:36,059 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p49.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b7368ec0-bfb4-11ef-a0e4-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5lxjuhjo.pdf を削除しました。
82/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p49.pdf

2024-12-22 01:00:36,788 - INFO - Response status: 206
Response headers:
    'Content-Length': '186621'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B7997CCE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '23796251-301e-00e5-5dc1-534060000000'
    'x-ms-client-request-id': 'b7368ec0-bfb4-11ef-a0e4-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:00:36 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4boyuntu.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  18%|█▊        | 82/445 [10:03<41:26,  6.85s/it]2024-12-22 01:00:42,688 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p5.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'bb29ef6c-bfb4-11ef-9135-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4boyuntu.pdf を削除しました。
83/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p5.pdf

2024-12-22 01:00:43,422 - INFO - Response status: 206
Response headers:
    'Content-Length': '454343'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:09 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BEC1F554"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8b7c08c2-201e-0014-2dc1-5391f3000000'
    'x-ms-client-request-id': 'bb29ef6c-bfb4-11ef-9135-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:00:42 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0rhrtfsj.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  19%|█▊        | 83/445 [10:10<41:26,  6.87s/it]2024-12-22 01:00:49,597 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p50.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'bf484788-bfb4-11ef-8fb7-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0rhrtfsj.pdf を削除しました。
84/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p50.pdf

2024-12-22 01:00:50,351 - INFO - Response status: 206
Response headers:
    'Content-Length': '482786'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:05 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BCD1EFCC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd50449b3-001e-0047-49c1-538dfc000000'
    'x-ms-client-request-id': 'bf484788-bfb4-11ef-8fb7-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:00:50 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpa0ijrd12.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  19%|█▉        | 84/445 [10:17<41:46,  6.94s/it]2024-12-22 01:00:56,717 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p51.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c386ad0c-bfb4-11ef-be23-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpa0ijrd12.pdf を削除しました。
85/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p51.pdf

2024-12-22 01:00:57,436 - INFO - Response status: 206
Response headers:
    'Content-Length': '445191'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:03 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BB9C7944"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '237489ee-601e-005c-27c1-53a36e000000'
    'x-ms-client-request-id': 'c386ad0c-bfb4-11ef-be23-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:00:57 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmppny7rg_x.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  19%|█▉        | 85/445 [10:24<41:52,  6.98s/it]2024-12-22 01:01:03,777 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p52.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c7bbeb3d-bfb4-11ef-8a75-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmppny7rg_x.pdf を削除しました。
86/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p52.pdf

2024-12-22 01:01:04,523 - INFO - Response status: 206
Response headers:
    'Content-Length': '631423'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:06 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BD060BB5"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '1a284a02-b01e-001a-0bc1-537df8000000'
    'x-ms-client-request-id': 'c7bbeb3d-bfb4-11ef-8a75-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:01:03 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3phsk1ix.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  19%|█▉        | 86/445 [10:37<51:38,  8.63s/it]2024-12-22 01:01:16,262 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p53.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'cf2cf335-bfb4-11ef-b59d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3phsk1ix.pdf を削除しました。
87/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p53.pdf

2024-12-22 01:01:17,007 - INFO - Response status: 206
Response headers:
    'Content-Length': '389037'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:08 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BE2553F0"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '03af2ca7-101e-00bd-6fc1-53441b000000'
    'x-ms-client-request-id': 'cf2cf335-bfb4-11ef-b59d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:01:16 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7wcduf6t.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  20%|█▉        | 87/445 [10:44<48:41,  8.16s/it]2024-12-22 01:01:23,326 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p54.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd362e2bc-bfb4-11ef-9e35-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7wcduf6t.pdf を削除しました。
88/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p54.pdf

2024-12-22 01:01:24,044 - INFO - Response status: 206
Response headers:
    'Content-Length': '444654'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:10 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BFDD23A1"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e3505a3a-301e-00aa-26c1-538478000000'
    'x-ms-client-request-id': 'd362e2bc-bfb4-11ef-9e35-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:01:23 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmpfmfpa0.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  20%|█▉        | 88/445 [10:56<55:39,  9.35s/it]2024-12-22 01:01:35,464 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p55.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'da9f00bd-bfb4-11ef-a192-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmpfmfpa0.pdf を削除しました。
89/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p55.pdf

2024-12-22 01:01:36,210 - INFO - Response status: 206
Response headers:
    'Content-Length': '471569'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:12 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C107A9DA"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8ae34b47-401e-00a5-50c1-53698e000000'
    'x-ms-client-request-id': 'da9f00bd-bfb4-11ef-a192-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:01:36 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpq0p0hpu_.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  20%|██        | 89/445 [11:03<51:28,  8.67s/it]2024-12-22 01:01:42,555 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p56.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ded8d790-bfb4-11ef-b8d1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpq0p0hpu_.pdf を削除しました。
90/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p56.pdf

2024-12-22 01:01:43,281 - INFO - Response status: 206
Response headers:
    'Content-Length': '658882'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:10 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BFB6662B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '427d7b62-501e-00fe-51c1-536ef2000000'
    'x-ms-client-request-id': 'ded8d790-bfb4-11ef-b8d1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:01:43 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpl5nvpad0.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  20%|██        | 90/445 [11:10<48:47,  8.25s/it]2024-12-22 01:01:49,803 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p57.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e32af926-bfb4-11ef-b008-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpl5nvpad0.pdf を削除しました。
91/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p57.pdf

2024-12-22 01:01:50,553 - INFO - Response status: 206
Response headers:
    'Content-Length': '422781'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:08 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BE9B1113"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b1a57f40-b01e-0099-03c1-53dd55000000'
    'x-ms-client-request-id': 'e32af926-bfb4-11ef-b008-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:01:50 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpu3yo9r3c.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  20%|██        | 91/445 [11:22<55:29,  9.41s/it]2024-12-22 01:02:01,912 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p58.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ea629f4c-bfb4-11ef-91c9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpu3yo9r3c.pdf を削除しました。
92/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p58.pdf

2024-12-22 01:02:02,636 - INFO - Response status: 206
Response headers:
    'Content-Length': '435963'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:50 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B3DBEDEE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fdc50536-301e-0088-55c1-53ea4e000000'
    'x-ms-client-request-id': 'ea629f4c-bfb4-11ef-91c9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:02:02 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpqmmlrdwj.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  21%|██        | 92/445 [11:30<51:32,  8.76s/it]2024-12-22 01:02:09,169 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p59.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'eeb6018e-bfb4-11ef-8045-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpqmmlrdwj.pdf を削除しました。
93/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p59.pdf

2024-12-22 01:02:09,908 - INFO - Response status: 206
Response headers:
    'Content-Length': '500060'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:52 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B4B7E93F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '567d7311-101e-00db-03c1-53f641000000'
    'x-ms-client-request-id': 'eeb6018e-bfb4-11ef-8045-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:02:09 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpn763o7zb.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  21%|██        | 93/445 [11:37<48:38,  8.29s/it]2024-12-22 01:02:16,368 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p6.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f30079ec-bfb4-11ef-be1a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpn763o7zb.pdf を削除しました。
94/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p6.pdf

2024-12-22 01:02:17,131 - INFO - Response status: 206
Response headers:
    'Content-Length': '455306'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:11 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C0499C56"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f3f09089-a01e-004a-4dc1-5362f0000000'
    'x-ms-client-request-id': 'f30079ec-bfb4-11ef-be1a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:02:17 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpzvp4eizm.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  21%|██        | 94/445 [11:44<46:35,  7.97s/it]2024-12-22 01:02:23,574 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p60.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f74bf065-bfb4-11ef-a83f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpzvp4eizm.pdf を削除しました。
95/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p60.pdf

2024-12-22 01:02:24,314 - INFO - Response status: 206
Response headers:
    'Content-Length': '484245'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B8055A06"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ae332609-401e-008c-07c1-531fcc000000'
    'x-ms-client-request-id': 'f74bf065-bfb4-11ef-a83f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:02:23 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2yguxfxv.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  21%|██▏       | 95/445 [11:51<45:02,  7.72s/it]2024-12-22 01:02:30,719 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p61.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'fb8e1ef6-bfb4-11ef-b3f5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2yguxfxv.pdf を削除しました。
96/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p61.pdf

2024-12-22 01:02:31,446 - INFO - Response status: 206
Response headers:
    'Content-Length': '545459'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B81CBF56"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '459fb2e7-701e-008f-27c1-531ccb000000'
    'x-ms-client-request-id': 'fb8e1ef6-bfb4-11ef-b3f5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:02:31 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp34awbksl.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  22%|██▏       | 96/445 [11:58<43:47,  7.53s/it]2024-12-22 01:02:37,801 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p62.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ffc6e680-bfb4-11ef-8d0c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp34awbksl.pdf を削除しました。
97/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p62.pdf

2024-12-22 01:02:38,574 - INFO - Response status: 206
Response headers:
    'Content-Length': '636333'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:54 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B641FE87"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cab250df-d01e-00ef-4cc1-5359e9000000'
    'x-ms-client-request-id': 'ffc6e680-bfb4-11ef-8d0c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:02:37 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp8_q59c1i.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  22%|██▏       | 97/445 [12:06<43:12,  7.45s/it]2024-12-22 01:02:45,071 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p63.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '041c3481-bfb5-11ef-a0d6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp8_q59c1i.pdf を削除しました。
98/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p63.pdf

2024-12-22 01:02:45,818 - INFO - Response status: 206
Response headers:
    'Content-Length': '422918'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:56 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B76A3D81"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '095a0c62-a01e-0041-66c1-537a84000000'
    'x-ms-client-request-id': '041c3481-bfb5-11ef-a0d6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:02:45 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpqohuunj3.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  22%|██▏       | 98/445 [12:13<42:18,  7.32s/it]2024-12-22 01:02:52,069 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p64.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0847f56a-bfb5-11ef-8312-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpqohuunj3.pdf を削除しました。
99/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p64.pdf

2024-12-22 01:02:52,778 - INFO - Response status: 206
Response headers:
    'Content-Length': '594267'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:51 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B3FFC869"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '828783bb-001e-00ed-50c1-535b13000000'
    'x-ms-client-request-id': '0847f56a-bfb5-11ef-8312-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:02:52 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb_acogjq.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  22%|██▏       | 99/445 [12:20<41:49,  7.25s/it]2024-12-22 01:02:59,180 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p65.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0c8501cd-bfb5-11ef-85d4-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb_acogjq.pdf を削除しました。
100/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p65.pdf

2024-12-22 01:02:59,904 - INFO - Response status: 206
Response headers:
    'Content-Length': '529360'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:52 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B4B2E5D1"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '1fa141a6-a01e-00eb-21c1-53ac6b000000'
    'x-ms-client-request-id': '0c8501cd-bfb5-11ef-85d4-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:03:00 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7thh7uxo.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  22%|██▏       | 100/445 [12:27<41:13,  7.17s/it]2024-12-22 01:03:06,156 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p66.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '10ad6bc9-bfb5-11ef-82a6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7thh7uxo.pdf を削除しました。
101/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p66.pdf

2024-12-22 01:03:06,892 - INFO - Response status: 206
Response headers:
    'Content-Length': '612570'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:54 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B6327F9C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b08bc5fd-601e-00d4-33c1-531bb7000000'
    'x-ms-client-request-id': '10ad6bc9-bfb5-11ef-82a6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:03:06 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpj20txo70.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  23%|██▎       | 101/445 [12:34<41:17,  7.20s/it]2024-12-22 01:03:13,433 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p67.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1503e25d-bfb5-11ef-a348-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpj20txo70.pdf を削除しました。
102/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p67.pdf

2024-12-22 01:03:14,161 - INFO - Response status: 206
Response headers:
    'Content-Length': '416103'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:52 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B5008785"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e9cd41c6-701e-00ad-4cc1-5372fd000000'
    'x-ms-client-request-id': '1503e25d-bfb5-11ef-a348-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:03:13 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmblk10kc.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  23%|██▎       | 102/445 [12:41<40:53,  7.15s/it]2024-12-22 01:03:20,467 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p68.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '193516d2-bfb5-11ef-a72a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmblk10kc.pdf を削除しました。
103/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p68.pdf

2024-12-22 01:03:21,239 - INFO - Response status: 206
Response headers:
    'Content-Length': '513256'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:11 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C01669D1"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fef05a60-801e-009a-66c1-53de52000000'
    'x-ms-client-request-id': '193516d2-bfb5-11ef-a72a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:03:21 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyrtcp2fx.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  23%|██▎       | 103/445 [12:48<40:35,  7.12s/it]2024-12-22 01:03:27,514 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p69.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1d6881f7-bfb5-11ef-b93f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyrtcp2fx.pdf を削除しました。
104/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p69.pdf

2024-12-22 01:03:28,246 - INFO - Response status: 206
Response headers:
    'Content-Length': '489805'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:12 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C0FDC9DB"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a2eea1f8-c01e-0078-2bc1-533a20000000'
    'x-ms-client-request-id': '1d6881f7-bfb5-11ef-b93f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:03:27 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp42kq2z2g.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  23%|██▎       | 104/445 [12:55<40:16,  7.09s/it]2024-12-22 01:03:34,519 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p7.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '21955a4a-bfb5-11ef-9401-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp42kq2z2g.pdf を削除しました。
105/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p7.pdf

2024-12-22 01:03:35,237 - INFO - Response status: 206
Response headers:
    'Content-Length': '454750'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:12 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C09606DA"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cd918bde-301e-006d-5ec1-53f8b9000000'
    'x-ms-client-request-id': '21955a4a-bfb5-11ef-9401-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:03:34 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdddkcc99.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  24%|██▎       | 105/445 [13:02<39:51,  7.03s/it]2024-12-22 01:03:41,427 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p70.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '25b374de-bfb5-11ef-af34-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdddkcc99.pdf を削除しました。
106/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p70.pdf

2024-12-22 01:03:42,162 - INFO - Response status: 206
Response headers:
    'Content-Length': '446226'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:50 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B3E02EE2"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'c6d59679-f01e-0052-6fc1-534f65000000'
    'x-ms-client-request-id': '25b374de-bfb5-11ef-af34-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:03:41 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpzbmpotxp.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  24%|██▍       | 106/445 [13:09<39:41,  7.03s/it]2024-12-22 01:03:48,436 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p71.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '29e0d4c8-bfb5-11ef-9611-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpzbmpotxp.pdf を削除しました。
107/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p71.pdf

2024-12-22 01:03:49,154 - INFO - Response status: 206
Response headers:
    'Content-Length': '513442'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:52 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B4C78F16"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4125579f-d01e-00c6-21c1-532fab000000'
    'x-ms-client-request-id': '29e0d4c8-bfb5-11ef-9611-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:03:49 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3oo61ian.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  24%|██▍       | 107/445 [13:16<39:47,  7.06s/it]2024-12-22 01:03:55,588 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p72.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2e2442f3-bfb5-11ef-ad8e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3oo61ian.pdf を削除しました。
108/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p72.pdf

2024-12-22 01:03:56,338 - INFO - Response status: 206
Response headers:
    'Content-Length': '494322'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:54 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B62300A1"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '89ee2b8a-c01e-0096-19c1-5330a3000000'
    'x-ms-client-request-id': '2e2442f3-bfb5-11ef-ad8e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:03:56 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpykwjlilx.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  24%|██▍       | 108/445 [13:23<39:33,  7.04s/it]2024-12-22 01:04:02,582 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p73.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '324f2c97-bfb5-11ef-8f88-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpykwjlilx.pdf を削除しました。
109/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p73.pdf

2024-12-22 01:04:03,319 - INFO - Response status: 206
Response headers:
    'Content-Length': '592034'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B5347C82"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '50562e45-801e-0074-13c1-53d4d1000000'
    'x-ms-client-request-id': '324f2c97-bfb5-11ef-8f88-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:04:02 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpewenfho2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  24%|██▍       | 109/445 [13:30<39:41,  7.09s/it]2024-12-22 01:04:09,776 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p74.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '36990f5e-bfb5-11ef-bfe5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpewenfho2.pdf を削除しました。
110/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p74.pdf

2024-12-22 01:04:10,506 - INFO - Response status: 206
Response headers:
    'Content-Length': '544365'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:58 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B8519DB4"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e70140e4-301e-0044-1cc1-538efb000000'
    'x-ms-client-request-id': '36990f5e-bfb5-11ef-bfe5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:04:09 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0ambo3vk.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  25%|██▍       | 110/445 [13:38<39:48,  7.13s/it]2024-12-22 01:04:17,000 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p75.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3ae75b82-bfb5-11ef-825b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0ambo3vk.pdf を削除しました。
111/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p75.pdf

2024-12-22 01:04:17,740 - INFO - Response status: 206
Response headers:
    'Content-Length': '622860'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:56 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B773A8CE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f9749e94-f01e-00da-47c1-53f7bc000000'
    'x-ms-client-request-id': '3ae75b82-bfb5-11ef-825b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:04:17 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2tghztbh.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  25%|██▍       | 111/445 [13:45<40:02,  7.19s/it]2024-12-22 01:04:24,341 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p76.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3f47a2ab-bfb5-11ef-a663-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2tghztbh.pdf を削除しました。
112/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p76.pdf

2024-12-22 01:04:25,110 - INFO - Response status: 206
Response headers:
    'Content-Length': '465869'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:55 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B66B2A2E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'abd530f9-d01e-00a0-77c2-539df1000000'
    'x-ms-client-request-id': '3f47a2ab-bfb5-11ef-a663-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:04:25 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpee27di0f.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  25%|██▌       | 112/445 [13:52<39:58,  7.20s/it]2024-12-22 01:04:31,563 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p77.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '43958a26-bfb5-11ef-8ac0-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpee27di0f.pdf を削除しました。
113/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p77.pdf

2024-12-22 01:04:32,288 - INFO - Response status: 206
Response headers:
    'Content-Length': '453532'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:56 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B760D244"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd92e2fd7-301e-00c7-7ec2-532e56000000'
    'x-ms-client-request-id': '43958a26-bfb5-11ef-8ac0-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:04:31 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpygp3lvlq.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  25%|██▌       | 113/445 [13:59<39:28,  7.14s/it]2024-12-22 01:04:38,544 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p78.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '47bebd56-bfb5-11ef-a8ee-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpygp3lvlq.pdf を削除しました。
114/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p78.pdf

2024-12-22 01:04:39,314 - INFO - Response status: 206
Response headers:
    'Content-Length': '63187'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:05 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BCC49148"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '066692d1-101e-0071-58c2-5320ae000000'
    'x-ms-client-request-id': '47bebd56-bfb5-11ef-a8ee-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:04:39 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvvkbe3hn.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  26%|██▌       | 114/445 [14:06<38:22,  6.96s/it]2024-12-22 01:04:45,083 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p79.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4ba4618e-bfb5-11ef-ac9e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvvkbe3hn.pdf を削除しました。
115/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p79.pdf

2024-12-22 01:04:45,808 - INFO - Response status: 206
Response headers:
    'Content-Length': '186766'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:03 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BB6505BE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '91c56ad6-a01e-000e-67c2-53be9c000000'
    'x-ms-client-request-id': '4ba4618e-bfb5-11ef-ac9e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:04:45 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk9s2gyy8.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  26%|██▌       | 115/445 [14:12<37:44,  6.86s/it]2024-12-22 01:04:51,727 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p8.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4f9a4b47-bfb5-11ef-984c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk9s2gyy8.pdf を削除しました。
116/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p8.pdf

2024-12-22 01:04:52,463 - INFO - Response status: 206
Response headers:
    'Content-Length': '455877'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B5BE9522"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '305f7434-b01e-00b0-1dc2-53ab17000000'
    'x-ms-client-request-id': '4f9a4b47-bfb5-11ef-984c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:04:52 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7g8tld9n.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  26%|██▌       | 116/445 [14:19<37:49,  6.90s/it]2024-12-22 01:04:58,711 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p80.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '53c3ef4d-bfb5-11ef-bdd1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7g8tld9n.pdf を削除しました。
117/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p80.pdf

2024-12-22 01:04:59,439 - INFO - Response status: 206
Response headers:
    'Content-Length': '502533'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:09 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BEB99A4F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '89b09936-101e-0094-69c2-533259000000'
    'x-ms-client-request-id': '53c3ef4d-bfb5-11ef-bdd1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:04:58 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphhjki7i4.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  26%|██▋       | 117/445 [14:26<37:51,  6.93s/it]2024-12-22 01:05:05,697 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p81.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '57ee0ed6-bfb5-11ef-81ae-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphhjki7i4.pdf を削除しました。
118/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p81.pdf

2024-12-22 01:05:06,444 - INFO - Response status: 206
Response headers:
    'Content-Length': '524763'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:10 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BFB30E92"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fb80dbc5-b01e-005e-55c2-53a194000000'
    'x-ms-client-request-id': '57ee0ed6-bfb5-11ef-81ae-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:05:06 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpo6btmbum.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  27%|██▋       | 118/445 [14:33<37:56,  6.96s/it]2024-12-22 01:05:12,743 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p82.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5c212a62-bfb5-11ef-988e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpo6btmbum.pdf を削除しました。
119/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p82.pdf

2024-12-22 01:05:13,475 - INFO - Response status: 206
Response headers:
    'Content-Length': '725172'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:12 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C0B6B095"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2264b605-301e-0000-74c2-535297000000'
    'x-ms-client-request-id': '5c212a62-bfb5-11ef-988e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:05:12 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9aennv8d.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  27%|██▋       | 119/445 [14:40<38:12,  7.03s/it]2024-12-22 01:05:19,939 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p83.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '606b361b-bfb5-11ef-b35b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9aennv8d.pdf を削除しました。
120/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p83.pdf

2024-12-22 01:05:20,654 - INFO - Response status: 206
Response headers:
    'Content-Length': '510117'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:11 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C03981CC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '5c621aa1-201e-0097-60c2-53315e000000'
    'x-ms-client-request-id': '606b361b-bfb5-11ef-b35b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:05:19 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0rndkxr7.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  27%|██▋       | 120/445 [14:53<46:21,  8.56s/it]2024-12-22 01:05:32,055 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p84.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '67a3cebf-bfb5-11ef-b91c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0rndkxr7.pdf を削除しました。
121/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p84.pdf

2024-12-22 01:05:32,846 - INFO - Response status: 206
Response headers:
    'Content-Length': '451641'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:08 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BE1ECBA0"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '69e06dbd-301e-00ee-3dc2-535814000000'
    'x-ms-client-request-id': '67a3cebf-bfb5-11ef-b91c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:05:32 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0flqf9_j.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  27%|██▋       | 121/445 [15:00<43:47,  8.11s/it]2024-12-22 01:05:39,116 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p85.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6bd94de6-bfb5-11ef-9f2f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0flqf9_j.pdf を削除しました。
122/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p85.pdf

2024-12-22 01:05:39,829 - INFO - Response status: 206
Response headers:
    'Content-Length': '572384'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:06 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BD51B3BF"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '427f236d-501e-00fe-79c2-536ef2000000'
    'x-ms-client-request-id': '6bd94de6-bfb5-11ef-9f2f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:05:39 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpowg460cm.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  27%|██▋       | 122/445 [15:12<50:18,  9.35s/it]2024-12-22 01:05:51,348 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p86.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7323cf7c-bfb5-11ef-8013-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpowg460cm.pdf を削除しました。
123/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p86.pdf

2024-12-22 01:05:52,067 - INFO - Response status: 206
Response headers:
    'Content-Length': '568590'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:04 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BBC8AEC4"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f5a38b28-001e-006e-4cc2-53fbbe000000'
    'x-ms-client-request-id': '7323cf7c-bfb5-11ef-8013-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:05:51 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfy6_4gwr.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  28%|██▊       | 123/445 [15:19<46:39,  8.69s/it]2024-12-22 01:05:58,522 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p87.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '776a5fe7-bfb5-11ef-8cdc-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfy6_4gwr.pdf を削除しました。
124/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p87.pdf

2024-12-22 01:05:59,265 - INFO - Response status: 206
Response headers:
    'Content-Length': '640827'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:04 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BC4ED431"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'c521d742-701e-0043-62c2-53787e000000'
    'x-ms-client-request-id': '776a5fe7-bfb5-11ef-8cdc-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:05:58 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsoh9strn.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  28%|██▊       | 124/445 [15:31<52:21,  9.79s/it]2024-12-22 01:06:10,862 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p88.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7ec5552d-bfb5-11ef-878a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsoh9strn.pdf を削除しました。
125/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p88.pdf

2024-12-22 01:06:11,616 - INFO - Response status: 206
Response headers:
    'Content-Length': '416033'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:56 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B7539AA6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '1d121046-c01e-00b4-4bc2-535e95000000'
    'x-ms-client-request-id': '7ec5552d-bfb5-11ef-878a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:06:11 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxpkt6zvh.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  28%|██▊       | 125/445 [15:38<47:48,  8.96s/it]2024-12-22 01:06:17,907 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p89.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '82f84d09-bfb5-11ef-ada1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxpkt6zvh.pdf を削除しました。
126/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p89.pdf

2024-12-22 01:06:18,670 - INFO - Response status: 206
Response headers:
    'Content-Length': '470514'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:55 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B6802147"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cd93024a-301e-006d-48c2-53f8b9000000'
    'x-ms-client-request-id': '82f84d09-bfb5-11ef-ada1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:06:18 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvo5k3v3d.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  28%|██▊       | 126/445 [15:46<44:45,  8.42s/it]2024-12-22 01:06:25,051 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p9.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '873a567a-bfb5-11ef-a658-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvo5k3v3d.pdf を削除しました。
127/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p9.pdf

2024-12-22 01:06:25,770 - INFO - Response status: 206
Response headers:
    'Content-Length': '454657'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B53282EC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '354c23d7-d01e-006c-57c2-53f944000000'
    'x-ms-client-request-id': '873a567a-bfb5-11ef-a658-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:06:25 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp22e0jzo2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  29%|██▊       | 127/445 [15:53<42:21,  7.99s/it]2024-12-22 01:06:32,046 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p90.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8b65cd4d-bfb5-11ef-b419-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp22e0jzo2.pdf を削除しました。
128/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p90.pdf

2024-12-22 01:06:32,803 - INFO - Response status: 206
Response headers:
    'Content-Length': '442098'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:07 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BE1622CA"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b5c19f4b-701e-00c0-67c2-53d8d3000000'
    'x-ms-client-request-id': '8b65cd4d-bfb5-11ef-b419-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:06:32 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpf0urls1_.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  29%|██▉       | 128/445 [16:00<40:38,  7.69s/it]2024-12-22 01:06:39,043 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p91.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8f916cd8-bfb5-11ef-bade-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpf0urls1_.pdf を削除しました。
129/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p91.pdf

2024-12-22 01:06:39,783 - INFO - Response status: 206
Response headers:
    'Content-Length': '537574'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:06 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BD831397"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2e35b7dd-101e-009f-22c2-532a2d000000'
    'x-ms-client-request-id': '8f916cd8-bfb5-11ef-bade-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:06:40 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0vlm22yg.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  29%|██▉       | 129/445 [16:07<39:43,  7.54s/it]2024-12-22 01:06:46,232 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p92.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '93da75fa-bfb5-11ef-9ffd-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0vlm22yg.pdf を削除しました。
130/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p92.pdf

2024-12-22 01:06:46,963 - INFO - Response status: 206
Response headers:
    'Content-Length': '614230'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:03 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BBA9D7B6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '88fb5eb3-101e-0053-36c2-534e98000000'
    'x-ms-client-request-id': '93da75fa-bfb5-11ef-9ffd-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:06:46 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphtswkehf.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  29%|██▉       | 130/445 [16:14<39:14,  7.47s/it]2024-12-22 01:06:53,547 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p93.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '98368cc8-bfb5-11ef-9683-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphtswkehf.pdf を削除しました。
131/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p93.pdf

2024-12-22 01:06:54,272 - INFO - Response status: 206
Response headers:
    'Content-Length': '411712'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:05 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BCB33FA5"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4d03a51c-101e-001c-24c2-538a80000000'
    'x-ms-client-request-id': '98368cc8-bfb5-11ef-9683-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:06:53 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbwefaelz.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  29%|██▉       | 131/445 [16:21<38:14,  7.31s/it]2024-12-22 01:07:00,467 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p94.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9c5679c3-bfb5-11ef-ba06-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbwefaelz.pdf を削除しました。
132/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p94.pdf

2024-12-22 01:07:01,222 - INFO - Response status: 206
Response headers:
    'Content-Length': '464083'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:09 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BEC04993"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '3a80327e-e01e-0009-57c2-534819000000'
    'x-ms-client-request-id': '9c5679c3-bfb5-11ef-ba06-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:07:00 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpnc_a77hs.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  30%|██▉       | 132/445 [16:28<37:47,  7.24s/it]2024-12-22 01:07:07,566 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p95.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a091c695-bfb5-11ef-bb76-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpnc_a77hs.pdf を削除しました。
133/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p95.pdf

2024-12-22 01:07:08,327 - INFO - Response status: 206
Response headers:
    'Content-Length': '451223'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:10 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64BF7AFF86"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6d795c1e-401e-00ae-46c2-5371fa000000'
    'x-ms-client-request-id': 'a091c695-bfb5-11ef-bb76-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:07:08 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvdwt8_d8.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  30%|██▉       | 133/445 [16:35<37:23,  7.19s/it]2024-12-22 01:07:14,634 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p96.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a4c83bab-bfb5-11ef-9025-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvdwt8_d8.pdf を削除しました。
134/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p96.pdf

2024-12-22 01:07:15,364 - INFO - Response status: 206
Response headers:
    'Content-Length': '539530'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:12 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C0E774D7"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '965f4481-201e-0079-4fc2-533bdd000000'
    'x-ms-client-request-id': 'a4c83bab-bfb5-11ef-9025-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:07:15 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphh05va4o.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  30%|███       | 134/445 [16:43<37:33,  7.25s/it]2024-12-22 01:07:22,010 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p97.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a92d8eba-bfb5-11ef-b902-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphh05va4o.pdf を削除しました。
135/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p97.pdf

2024-12-22 01:07:22,810 - INFO - Response status: 206
Response headers:
    'Content-Length': '653758'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:11 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64C01690C0"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9da24485-e01e-00ec-29c2-535aee000000'
    'x-ms-client-request-id': 'a92d8eba-bfb5-11ef-b902-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:07:22 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4rvg_izb.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  30%|███       | 135/445 [16:50<37:37,  7.28s/it]2024-12-22 01:07:29,375 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p98.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ad917003-bfb5-11ef-8824-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4rvg_izb.pdf を削除しました。
136/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p98.pdf

2024-12-22 01:07:30,108 - INFO - Response status: 206
Response headers:
    'Content-Length': '443097'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:52 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B52AC373"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '7f8dd692-a01e-00c2-30c2-53da29000000'
    'x-ms-client-request-id': 'ad917003-bfb5-11ef-8824-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:07:29 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmz8crdwy.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  31%|███       | 136/445 [16:57<37:07,  7.21s/it]2024-12-22 01:07:36,414 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/1%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p99.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b1c3871d-bfb5-11ef-b554-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmz8crdwy.pdf を削除しました。
137/445 処理中
コンテナ名: rag-pdf, Blob名: 1年_中学校理科_指導書_板書例_/1年_中学校理科_指導書_板書例_p99.pdf

2024-12-22 01:07:37,158 - INFO - Response status: 206
Response headers:
    'Content-Length': '520217'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:00:54 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64B61D3AB6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4f5d257c-e01e-002b-14c2-53262f000000'
    'x-ms-client-request-id': 'b1c3871d-bfb5-11ef-b554-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:07:37 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdadtqpm5.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  31%|███       | 137/445 [17:04<37:02,  7.22s/it]2024-12-22 01:07:43,645 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p1.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b612e000-bfb5-11ef-a10f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdadtqpm5.pdf を削除しました。
138/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p1.pdf

2024-12-22 01:07:44,374 - INFO - Response status: 206
Response headers:
    'Content-Length': '163111'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D4E22C47"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'c19a5680-f01e-0059-80c2-535711000000'
    'x-ms-client-request-id': 'b612e000-bfb5-11ef-a10f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:07:44 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7l5jsyuh.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  31%|███       | 138/445 [17:11<36:12,  7.08s/it]2024-12-22 01:07:50,390 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p10.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ba182f83-bfb5-11ef-8733-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7l5jsyuh.pdf を削除しました。
139/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p10.pdf

2024-12-22 01:07:51,114 - INFO - Response status: 206
Response headers:
    'Content-Length': '488251'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D4B5F6D2"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a428c0da-f01e-009e-13c2-532bd0000000'
    'x-ms-client-request-id': 'ba182f83-bfb5-11ef-8733-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:07:51 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp1z8fipe6.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  31%|███       | 139/445 [17:18<36:13,  7.10s/it]2024-12-22 01:07:57,559 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p100.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'be5dfc14-bfb5-11ef-8d64-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp1z8fipe6.pdf を削除しました。
140/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p100.pdf

2024-12-22 01:07:58,310 - INFO - Response status: 206
Response headers:
    'Content-Length': '671562'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D6D58948"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f2abb2ae-201e-00be-73c2-53471c000000'
    'x-ms-client-request-id': 'be5dfc14-bfb5-11ef-8d64-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:07:57 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplthh5lka.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  31%|███▏      | 140/445 [17:25<36:33,  7.19s/it]2024-12-22 01:08:04,962 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p101.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c2c7a995-bfb5-11ef-acb8-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplthh5lka.pdf を削除しました。
141/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p101.pdf

2024-12-22 01:08:05,706 - INFO - Response status: 206
Response headers:
    'Content-Length': '437953'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:50 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D75D8149"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9a3eadab-c01e-001e-30c2-53887a000000'
    'x-ms-client-request-id': 'c2c7a995-bfb5-11ef-acb8-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:08:05 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6stpwx61.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  32%|███▏      | 141/445 [17:33<36:13,  7.15s/it]2024-12-22 01:08:12,014 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p102.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c6fbb70d-bfb5-11ef-99c9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6stpwx61.pdf を削除しました。
142/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p102.pdf

2024-12-22 01:08:12,729 - INFO - Response status: 206
Response headers:
    'Content-Length': '445197'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D68ACA8C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e3542689-301e-00aa-08c2-538478000000'
    'x-ms-client-request-id': 'c6fbb70d-bfb5-11ef-99c9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:08:12 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgunzrs4v.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  32%|███▏      | 142/445 [17:40<35:51,  7.10s/it]2024-12-22 01:08:19,001 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p103.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'cb25c5b5-bfb5-11ef-ab25-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgunzrs4v.pdf を削除しました。
143/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p103.pdf

2024-12-22 01:08:19,736 - INFO - Response status: 206
Response headers:
    'Content-Length': '501829'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D5C8552D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9adbfd27-e01e-006f-59c2-53fa43000000'
    'x-ms-client-request-id': 'cb25c5b5-bfb5-11ef-ab25-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:08:19 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpubt4r5i6.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  32%|███▏      | 143/445 [17:47<35:42,  7.09s/it]2024-12-22 01:08:26,075 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p104.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'cf5d30a9-bfb5-11ef-90b9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpubt4r5i6.pdf を削除しました。
144/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p104.pdf

2024-12-22 01:08:26,815 - INFO - Response status: 206
Response headers:
    'Content-Length': '634214'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:51 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D83514B3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2a6b35ab-601e-0018-2dc2-537f02000000'
    'x-ms-client-request-id': 'cf5d30a9-bfb5-11ef-90b9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:08:26 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5ivuvscm.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  32%|███▏      | 144/445 [17:54<35:40,  7.11s/it]2024-12-22 01:08:33,230 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p105.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd3a1099f-bfb5-11ef-b097-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5ivuvscm.pdf を削除しました。
145/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p105.pdf

2024-12-22 01:08:33,997 - INFO - Response status: 206
Response headers:
    'Content-Length': '716232'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:50 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D7B6AEBE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cdffe10b-701e-00a6-66c2-536a89000000'
    'x-ms-client-request-id': 'd3a1099f-bfb5-11ef-b097-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:08:34 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpkzfb3nqx.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  33%|███▎      | 145/445 [18:01<35:53,  7.18s/it]2024-12-22 01:08:40,567 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p106.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd8009199-bfb5-11ef-ac67-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpkzfb3nqx.pdf を削除しました。
146/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p106.pdf

2024-12-22 01:08:41,319 - INFO - Response status: 206
Response headers:
    'Content-Length': '423153'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:52 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D88095C8"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8c56eef4-b01e-00bb-72c2-53b363000000'
    'x-ms-client-request-id': 'd8009199-bfb5-11ef-ac67-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:08:40 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6oiqe6yn.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  33%|███▎      | 146/445 [18:08<35:37,  7.15s/it]2024-12-22 01:08:47,645 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p107.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'dc387da2-bfb5-11ef-9ee9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6oiqe6yn.pdf を削除しました。
147/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p107.pdf

2024-12-22 01:08:48,385 - INFO - Response status: 206
Response headers:
    'Content-Length': '514738'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D906BB16"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '047d52ec-c01e-005a-2dc2-535416000000'
    'x-ms-client-request-id': 'dc387da2-bfb5-11ef-9ee9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:08:47 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpspj8pira.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  33%|███▎      | 147/445 [18:15<35:41,  7.19s/it]2024-12-22 01:08:54,916 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p108.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e08df009-bfb5-11ef-80dc-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpspj8pira.pdf を削除しました。
148/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p108.pdf

2024-12-22 01:08:55,670 - INFO - Response status: 206
Response headers:
    'Content-Length': '641641'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D4440618"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '215ea454-301e-00a1-01c2-539c0c000000'
    'x-ms-client-request-id': 'e08df009-bfb5-11ef-80dc-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:08:54 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfyw2x00f.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  33%|███▎      | 148/445 [18:23<35:39,  7.20s/it]2024-12-22 01:09:02,162 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p109.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e4df6549-bfb5-11ef-81bf-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfyw2x00f.pdf を削除しました。
149/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p109.pdf

2024-12-22 01:09:02,873 - INFO - Response status: 206
Response headers:
    'Content-Length': '402037'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D3AB57EB"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9c24c611-b01e-00ff-7ec2-536f0f000000'
    'x-ms-client-request-id': 'e4df6549-bfb5-11ef-81bf-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:09:02 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplx5hgpyx.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  33%|███▎      | 149/445 [18:30<35:18,  7.16s/it]2024-12-22 01:09:09,207 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p11.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e9129f11-bfb5-11ef-834e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplx5hgpyx.pdf を削除しました。
150/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p11.pdf

2024-12-22 01:09:09,933 - INFO - Response status: 206
Response headers:
    'Content-Length': '435573'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D4ED1C7C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'bc026dc4-401e-0004-25c2-53a715000000'
    'x-ms-client-request-id': 'e9129f11-bfb5-11ef-834e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:09:09 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb93lwpbr.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  34%|███▎      | 150/445 [18:37<34:56,  7.11s/it]2024-12-22 01:09:16,200 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p110.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ed3dc487-bfb5-11ef-aaf5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb93lwpbr.pdf を削除しました。
151/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p110.pdf

2024-12-22 01:09:16,955 - INFO - Response status: 206
Response headers:
    'Content-Length': '607679'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:52 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D86E0CFA"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'aed3ef79-b01e-0033-16c2-530bba000000'
    'x-ms-client-request-id': 'ed3dc487-bfb5-11ef-aaf5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:09:16 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpg15uqjgl.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  34%|███▍      | 151/445 [18:44<34:57,  7.13s/it]2024-12-22 01:09:23,399 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p111.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f1882281-bfb5-11ef-a1de-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpg15uqjgl.pdf を削除しました。
152/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p111.pdf

2024-12-22 01:09:24,131 - INFO - Response status: 206
Response headers:
    'Content-Length': '460355'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:50 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D77C316D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '058c798b-801e-0056-5cc2-53bae7000000'
    'x-ms-client-request-id': 'f1882281-bfb5-11ef-a1de-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:09:23 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5v_ifgkx.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  34%|███▍      | 152/445 [18:51<35:02,  7.18s/it]2024-12-22 01:09:30,672 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p112.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f5ddeee5-bfb5-11ef-8082-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5v_ifgkx.pdf を削除しました。
153/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p112.pdf

2024-12-22 01:09:31,426 - INFO - Response status: 206
Response headers:
    'Content-Length': '491784'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:52 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D881F3C6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '3947e872-d01e-00cd-75c2-5337df000000'
    'x-ms-client-request-id': 'f5ddeee5-bfb5-11ef-8082-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:09:30 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptef69m_p.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  34%|███▍      | 153/445 [18:58<34:51,  7.16s/it]2024-12-22 01:09:37,806 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p113.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'fa1e878f-bfb5-11ef-9114-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptef69m_p.pdf を削除しました。
154/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p113.pdf

2024-12-22 01:09:38,542 - INFO - Response status: 206
Response headers:
    'Content-Length': '710250'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D906BB16"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e5c7e23e-501e-007d-21c2-53ce5f000000'
    'x-ms-client-request-id': 'fa1e878f-bfb5-11ef-9114-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:09:38 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp75r4i3r7.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  35%|███▍      | 154/445 [19:06<34:56,  7.21s/it]2024-12-22 01:09:45,109 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p114.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'fe78ea22-bfb5-11ef-8329-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp75r4i3r7.pdf を削除しました。
155/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p114.pdf

2024-12-22 01:09:45,872 - INFO - Response status: 206
Response headers:
    'Content-Length': '622946'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D6A2F254"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '5049c127-501e-0054-6ec2-53b81d000000'
    'x-ms-client-request-id': 'fe78ea22-bfb5-11ef-8329-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:09:45 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp08hddjq3.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  35%|███▍      | 155/445 [19:13<34:50,  7.21s/it]2024-12-22 01:09:52,322 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p115.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '02c58a96-bfb6-11ef-80b7-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp08hddjq3.pdf を削除しました。
156/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p115.pdf

2024-12-22 01:09:53,063 - INFO - Response status: 206
Response headers:
    'Content-Length': '488321'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:50 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D7614D90"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4f55c065-e01e-0081-7fc2-53f0c0000000'
    'x-ms-client-request-id': '02c58a96-bfb6-11ef-80b7-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:09:52 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplvtq_f0k.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  35%|███▌      | 156/445 [19:20<34:46,  7.22s/it]2024-12-22 01:09:59,574 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p116.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '07181852-bfb6-11ef-af58-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplvtq_f0k.pdf を削除しました。
157/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p116.pdf

2024-12-22 01:10:00,327 - INFO - Response status: 206
Response headers:
    'Content-Length': '533542'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D6D01123"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '689a1108-201e-0036-42c2-53ffc5000000'
    'x-ms-client-request-id': '07181852-bfb6-11ef-af58-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:09:59 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp1jvcx6kc.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  35%|███▌      | 157/445 [19:27<34:45,  7.24s/it]2024-12-22 01:10:06,858 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p117.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0b6f870e-bfb6-11ef-b465-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp1jvcx6kc.pdf を削除しました。
158/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p117.pdf

2024-12-22 01:10:07,590 - INFO - Response status: 206
Response headers:
    'Content-Length': '417163'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D5E29D6E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'c296fbf7-201e-001f-58c2-538987000000'
    'x-ms-client-request-id': '0b6f870e-bfb6-11ef-b465-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:10:07 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwazay1ut.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  36%|███▌      | 158/445 [19:34<34:17,  7.17s/it]2024-12-22 01:10:13,859 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p118.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0f9bd38e-bfb6-11ef-a86e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwazay1ut.pdf を削除しました。
159/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p118.pdf

2024-12-22 01:10:14,609 - INFO - Response status: 206
Response headers:
    'Content-Length': '639451'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D486B777"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '3681ee3b-901e-0102-54c2-531638000000'
    'x-ms-client-request-id': '0f9bd38e-bfb6-11ef-a86e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:10:14 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9msni5ix.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  36%|███▌      | 159/445 [19:42<34:27,  7.23s/it]2024-12-22 01:10:21,233 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p119.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1401011b-bfb6-11ef-acbf-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9msni5ix.pdf を削除しました。
160/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p119.pdf

2024-12-22 01:10:21,974 - INFO - Response status: 206
Response headers:
    'Content-Length': '503713'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D549A18C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '39fc6f7a-801e-005d-72c2-53a293000000'
    'x-ms-client-request-id': '1401011b-bfb6-11ef-acbf-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:10:21 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphabqb93q.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  36%|███▌      | 160/445 [19:49<34:26,  7.25s/it]2024-12-22 01:10:28,535 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p12.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '185b1600-bfb6-11ef-a7a3-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphabqb93q.pdf を削除しました。
161/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p12.pdf

2024-12-22 01:10:29,373 - INFO - Response status: 206
Response headers:
    'Content-Length': '487831'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D5BAA8E3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6a8b7ab7-501e-0093-09c2-53c4dc000000'
    'x-ms-client-request-id': '185b1600-bfb6-11ef-a7a3-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:10:28 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsd9784ts.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  36%|███▌      | 161/445 [19:56<34:19,  7.25s/it]2024-12-22 01:10:35,794 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p120.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1caec0c4-bfb6-11ef-bfa2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsd9784ts.pdf を削除しました。
162/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p120.pdf

2024-12-22 01:10:36,542 - INFO - Response status: 206
Response headers:
    'Content-Length': '496354'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D46DF427"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'abd9b310-d01e-00a0-1fc2-539df1000000'
    'x-ms-client-request-id': '1caec0c4-bfb6-11ef-bfa2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:10:36 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxou9zxz5.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  36%|███▋      | 162/445 [20:04<34:24,  7.29s/it]2024-12-22 01:10:43,180 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p121.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2115dba2-bfb6-11ef-a0cd-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxou9zxz5.pdf を削除しました。
163/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p121.pdf

2024-12-22 01:10:43,902 - INFO - Response status: 206
Response headers:
    'Content-Length': '186231'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D39D100F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '865361f8-b01e-0055-48c2-53b9e0000000'
    'x-ms-client-request-id': '2115dba2-bfb6-11ef-a0cd-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:10:43 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbocwn2u_.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  37%|███▋      | 163/445 [20:10<33:26,  7.12s/it]2024-12-22 01:10:49,881 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p122.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '25145f49-bfb6-11ef-9634-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbocwn2u_.pdf を削除しました。
164/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p122.pdf

2024-12-22 01:10:50,632 - INFO - Response status: 206
Response headers:
    'Content-Length': '544729'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D2F971BD"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6d6685f9-901e-00ca-66c2-53c15a000000'
    'x-ms-client-request-id': '25145f49-bfb6-11ef-9634-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:10:50 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb9z0bhla.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  37%|███▋      | 164/445 [20:18<33:24,  7.13s/it]2024-12-22 01:10:57,052 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p123.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '295a679b-bfb6-11ef-a5bb-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb9z0bhla.pdf を削除しました。
165/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p123.pdf

2024-12-22 01:10:57,806 - INFO - Response status: 206
Response headers:
    'Content-Length': '486333'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D385AACD"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'c2975862-201e-001f-5cc2-538987000000'
    'x-ms-client-request-id': '295a679b-bfb6-11ef-a5bb-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:10:57 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfuif1189.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  37%|███▋      | 165/445 [20:25<33:07,  7.10s/it]2024-12-22 01:11:04,071 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p124.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2d8995a9-bfb6-11ef-9745-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfuif1189.pdf を削除しました。
166/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p124.pdf

2024-12-22 01:11:04,800 - INFO - Response status: 206
Response headers:
    'Content-Length': '471715'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D4998E0A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a0d3fb4a-e01e-00ce-17c2-5334d8000000'
    'x-ms-client-request-id': '2d8995a9-bfb6-11ef-9745-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:11:04 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbasqfcgv.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  37%|███▋      | 166/445 [20:32<32:55,  7.08s/it]2024-12-22 01:11:11,109 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p125.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '31bb71b9-bfb6-11ef-8d7d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbasqfcgv.pdf を削除しました。
167/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p125.pdf

2024-12-22 01:11:11,844 - INFO - Response status: 206
Response headers:
    'Content-Length': '443058'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D502614D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6fc4e338-f01e-007b-46c2-533927000000'
    'x-ms-client-request-id': '31bb71b9-bfb6-11ef-8d7d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:11:12 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyuy0juvh.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  38%|███▊      | 167/445 [20:39<32:42,  7.06s/it]2024-12-22 01:11:18,119 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p126.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '35e90299-bfb6-11ef-a4dc-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyuy0juvh.pdf を削除しました。
168/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p126.pdf

2024-12-22 01:11:18,870 - INFO - Response status: 206
Response headers:
    'Content-Length': '389591'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D5BD8BDC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a9416d52-501e-00dc-6dc2-5300c4000000'
    'x-ms-client-request-id': '35e90299-bfb6-11ef-a4dc-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:11:18 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpszksqv_q.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  38%|███▊      | 168/445 [20:46<32:34,  7.06s/it]2024-12-22 01:11:25,170 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p127.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3a1cc155-bfb6-11ef-af49-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpszksqv_q.pdf を削除しました。
169/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p127.pdf

2024-12-22 01:11:25,911 - INFO - Response status: 206
Response headers:
    'Content-Length': '492445'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D54EF2B8"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '7f904032-a01e-00c2-39c2-53da29000000'
    'x-ms-client-request-id': '3a1cc155-bfb6-11ef-af49-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:11:25 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_03zh9ra.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  38%|███▊      | 169/445 [20:53<32:25,  7.05s/it]2024-12-22 01:11:32,206 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p128.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3e4e8da6-bfb6-11ef-a1c9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_03zh9ra.pdf を削除しました。
170/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p128.pdf

2024-12-22 01:11:32,931 - INFO - Response status: 206
Response headers:
    'Content-Length': '461267'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D706C229"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fb844b90-b01e-005e-43c3-53a194000000'
    'x-ms-client-request-id': '3e4e8da6-bfb6-11ef-a1c9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:11:32 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5wpztsj5.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  38%|███▊      | 170/445 [21:00<32:11,  7.03s/it]2024-12-22 01:11:39,172 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p129.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '427570ae-bfb6-11ef-87cd-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5wpztsj5.pdf を削除しました。
171/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p129.pdf

2024-12-22 01:11:39,917 - INFO - Response status: 206
Response headers:
    'Content-Length': '650720'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:50 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D7583020"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f58e10ac-f01e-001d-1bc3-538b7d000000'
    'x-ms-client-request-id': '427570ae-bfb6-11ef-87cd-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:11:40 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpu2ue836f.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  38%|███▊      | 171/445 [21:07<32:17,  7.07s/it]2024-12-22 01:11:46,351 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p13.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '46bce0a4-bfb6-11ef-b013-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpu2ue836f.pdf を削除しました。
172/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p13.pdf

2024-12-22 01:11:47,082 - INFO - Response status: 206
Response headers:
    'Content-Length': '354922'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D55774BE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'efbec616-901e-00ac-17c3-537300000000'
    'x-ms-client-request-id': '46bce0a4-bfb6-11ef-b013-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:11:47 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphvc1mz8v.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  39%|███▊      | 172/445 [21:14<32:01,  7.04s/it]2024-12-22 01:11:53,313 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p130.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4ae3498a-bfb6-11ef-acc0-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphvc1mz8v.pdf を削除しました。
173/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p130.pdf

2024-12-22 01:11:54,075 - INFO - Response status: 206
Response headers:
    'Content-Length': '423361'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D48201D1"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '76e47ac3-a01e-0086-02c3-530645000000'
    'x-ms-client-request-id': '4ae3498a-bfb6-11ef-acc0-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:11:54 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4utg6sj5.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  39%|███▉      | 173/445 [21:21<31:51,  7.03s/it]2024-12-22 01:12:00,311 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p131.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4f0f2317-bfb6-11ef-815f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4utg6sj5.pdf を削除しました。
174/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p131.pdf

2024-12-22 01:12:01,134 - INFO - Response status: 206
Response headers:
    'Content-Length': '499212'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D534AA7B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8f8b04a1-701e-006a-60c3-530e3c000000'
    'x-ms-client-request-id': '4f0f2317-bfb6-11ef-815f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:12:01 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2ddddmbh.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  39%|███▉      | 174/445 [21:28<31:52,  7.06s/it]2024-12-22 01:12:07,434 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p132.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '534dfb12-bfb6-11ef-922b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2ddddmbh.pdf を削除しました。
175/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p132.pdf

2024-12-22 01:12:08,220 - INFO - Response status: 206
Response headers:
    'Content-Length': '443804'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D5BBB923"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '047efb84-c01e-005a-70c3-535416000000'
    'x-ms-client-request-id': '534dfb12-bfb6-11ef-922b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:12:08 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp61x4b5w6.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  39%|███▉      | 175/445 [21:35<31:49,  7.07s/it]2024-12-22 01:12:14,540 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p133.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '578a48cc-bfb6-11ef-966e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp61x4b5w6.pdf を削除しました。
176/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p133.pdf

2024-12-22 01:12:15,280 - INFO - Response status: 206
Response headers:
    'Content-Length': '579167'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D55A57A0"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4d06a299-101e-001c-2cc3-538a80000000'
    'x-ms-client-request-id': '578a48cc-bfb6-11ef-966e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:12:15 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjo230j53.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  40%|███▉      | 176/445 [21:42<31:47,  7.09s/it]2024-12-22 01:12:21,686 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p134.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5bcc9783-bfb6-11ef-a06c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjo230j53.pdf を削除しました。
177/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p134.pdf

2024-12-22 01:12:22,440 - INFO - Response status: 206
Response headers:
    'Content-Length': '635949'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D483D487"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fef3c761-801e-009a-2dc3-53de52000000'
    'x-ms-client-request-id': '5bcc9783-bfb6-11ef-a06c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:12:21 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxylwrsqm.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  40%|███▉      | 177/445 [21:50<32:13,  7.22s/it]2024-12-22 01:12:29,186 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p135.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6044e7a2-bfb6-11ef-9c93-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxylwrsqm.pdf を削除しました。
178/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p135.pdf

2024-12-22 01:12:29,910 - INFO - Response status: 206
Response headers:
    'Content-Length': '383389'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D3985A7A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6d6789d2-901e-00ca-2cc3-53c15a000000'
    'x-ms-client-request-id': '6044e7a2-bfb6-11ef-9c93-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:12:29 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphv8jyju2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  40%|████      | 178/445 [21:57<31:41,  7.12s/it]2024-12-22 01:12:36,091 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p136.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '64629dc2-bfb6-11ef-9e19-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphv8jyju2.pdf を削除しました。
179/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p136.pdf

2024-12-22 01:12:36,853 - INFO - Response status: 206
Response headers:
    'Content-Length': '487726'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D3091792"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6d7b8663-401e-00ae-10c3-5371fa000000'
    'x-ms-client-request-id': '64629dc2-bfb6-11ef-9e19-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:12:36 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_dqouj8v.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  40%|████      | 179/445 [22:04<31:28,  7.10s/it]2024-12-22 01:12:43,141 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p137.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6896701f-bfb6-11ef-a0de-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_dqouj8v.pdf を削除しました。
180/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p137.pdf

2024-12-22 01:12:43,872 - INFO - Response status: 206
Response headers:
    'Content-Length': '687632'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D355CFE0"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '335459c2-401e-00c8-58c3-53c3a0000000'
    'x-ms-client-request-id': '6896701f-bfb6-11ef-a0de-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:12:43 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpx3919mt9.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  40%|████      | 180/445 [22:11<31:26,  7.12s/it]2024-12-22 01:12:50,302 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p138.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6cdb1f35-bfb6-11ef-b1ee-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpx3919mt9.pdf を削除しました。
181/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p138.pdf

2024-12-22 01:12:51,029 - INFO - Response status: 206
Response headers:
    'Content-Length': '744440'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:52 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D88A75B7"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '066a6436-101e-0071-46c3-5320ae000000'
    'x-ms-client-request-id': '6cdb1f35-bfb6-11ef-b1ee-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:12:50 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyjlelzcn.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  41%|████      | 181/445 [22:18<31:26,  7.15s/it]2024-12-22 01:12:57,517 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p139.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7127f285-bfb6-11ef-92b0-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyjlelzcn.pdf を削除しました。
182/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p139.pdf

2024-12-22 01:12:58,296 - INFO - Response status: 206
Response headers:
    'Content-Length': '680473'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:50 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D78292D6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '3187d149-e01e-0002-3ac3-53506d000000'
    'x-ms-client-request-id': '7127f285-bfb6-11ef-92b0-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:12:57 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdum5kyg0.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  41%|████      | 182/445 [22:25<31:26,  7.17s/it]2024-12-22 01:13:04,746 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p14.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '75771092-bfb6-11ef-ac70-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdum5kyg0.pdf を削除しました。
183/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p14.pdf

2024-12-22 01:13:05,461 - INFO - Response status: 206
Response headers:
    'Content-Length': '488145'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D40A244D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'efbf528e-901e-00ac-40c3-537300000000'
    'x-ms-client-request-id': '75771092-bfb6-11ef-ac70-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:13:05 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmph101w40h.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  41%|████      | 183/445 [22:32<30:58,  7.09s/it]2024-12-22 01:13:11,656 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p140.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '799566b9-bfb6-11ef-aa1d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmph101w40h.pdf を削除しました。
184/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p140.pdf

2024-12-22 01:13:12,398 - INFO - Response status: 206
Response headers:
    'Content-Length': '572615'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D0A7216E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '122a9393-901e-0042-0cc3-537983000000'
    'x-ms-client-request-id': '799566b9-bfb6-11ef-aa1d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:13:11 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3p_8vgbl.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  41%|████▏     | 184/445 [22:39<31:04,  7.14s/it]2024-12-22 01:13:18,917 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p141.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7de96d30-bfb6-11ef-8099-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3p_8vgbl.pdf を削除しました。
185/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p141.pdf

2024-12-22 01:13:19,628 - INFO - Response status: 206
Response headers:
    'Content-Length': '536008'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64CFBBF505"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '237aa390-601e-005c-1dc3-53a36e000000'
    'x-ms-client-request-id': '7de96d30-bfb6-11ef-8099-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:13:18 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpc_dek6s0.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  42%|████▏     | 185/445 [22:47<30:54,  7.13s/it]2024-12-22 01:13:26,029 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p142.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8226a6c3-bfb6-11ef-8472-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpc_dek6s0.pdf を削除しました。
186/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p142.pdf

2024-12-22 01:13:26,768 - INFO - Response status: 206
Response headers:
    'Content-Length': '591393'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D11801F3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9c6f4cf7-201e-00d3-0fc3-53ed32000000'
    'x-ms-client-request-id': '8226a6c3-bfb6-11ef-8472-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:13:26 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp8ehfp3xx.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  42%|████▏     | 186/445 [22:54<30:54,  7.16s/it]2024-12-22 01:13:33,257 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p143.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '867585cb-bfb6-11ef-b514-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp8ehfp3xx.pdf を削除しました。
187/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p143.pdf

2024-12-22 01:13:34,011 - INFO - Response status: 206
Response headers:
    'Content-Length': '518711'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D19C7B78"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'dbde20d3-801e-007f-4fc3-53cca5000000'
    'x-ms-client-request-id': '867585cb-bfb6-11ef-b514-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:13:33 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpr1xos1ie.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  42%|████▏     | 187/445 [23:06<37:25,  8.70s/it]2024-12-22 01:13:45,555 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p144.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8dca1616-bfb6-11ef-b274-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpr1xos1ie.pdf を削除しました。
188/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p144.pdf

2024-12-22 01:13:46,295 - INFO - Response status: 206
Response headers:
    'Content-Length': '63511'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D23FCC2D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '435d6b65-001e-00a9-22c3-53877f000000'
    'x-ms-client-request-id': '8dca1616-bfb6-11ef-b274-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:13:45 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpkzhhdmv8.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  42%|████▏     | 188/445 [23:13<34:26,  8.04s/it]2024-12-22 01:13:52,051 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p145.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '91a94b9e-bfb6-11ef-8641-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpkzhhdmv8.pdf を削除しました。
189/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p145.pdf

2024-12-22 01:13:52,774 - INFO - Response status: 206
Response headers:
    'Content-Length': '154902'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D2D60BFA"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '819cbc81-601e-003a-50c3-531134000000'
    'x-ms-client-request-id': '91a94b9e-bfb6-11ef-8641-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:13:52 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7u0f7220.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  42%|████▏     | 189/445 [23:19<32:30,  7.62s/it]2024-12-22 01:13:58,684 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p146.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '959d60bf-bfb6-11ef-81e6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7u0f7220.pdf を削除しました。
190/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p146.pdf

2024-12-22 01:13:59,435 - INFO - Response status: 206
Response headers:
    'Content-Length': '622708'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D227F210"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '90737ce1-001e-00cf-0bc3-533525000000'
    'x-ms-client-request-id': '959d60bf-bfb6-11ef-81e6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:13:59 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxzc7lbtg.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  43%|████▎     | 190/445 [23:27<31:59,  7.53s/it]2024-12-22 01:14:05,999 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p147.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '99f95e9b-bfb6-11ef-a5f6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxzc7lbtg.pdf を削除しました。
191/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p147.pdf

2024-12-22 01:14:06,725 - INFO - Response status: 206
Response headers:
    'Content-Length': '522530'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D1C3AD97"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4c936a21-201e-00f1-4ac3-538304000000'
    'x-ms-client-request-id': '99f95e9b-bfb6-11ef-a5f6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:14:06 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6c6jfyyc.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  43%|████▎     | 191/445 [23:34<31:21,  7.41s/it]2024-12-22 01:14:13,132 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p148.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9e3a035d-bfb6-11ef-b36e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6c6jfyyc.pdf を削除しました。
192/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p148.pdf

2024-12-22 01:14:13,860 - INFO - Response status: 206
Response headers:
    'Content-Length': '425748'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D975066E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '39ca65d8-501e-0098-0cc3-53dca8000000'
    'x-ms-client-request-id': '9e3a035d-bfb6-11ef-b36e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:14:13 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxujcoz2x.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  43%|████▎     | 192/445 [23:41<30:41,  7.28s/it]2024-12-22 01:14:20,099 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p149.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a2611067-bfb6-11ef-b3ec-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxujcoz2x.pdf を削除しました。
193/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p149.pdf

2024-12-22 01:14:20,829 - INFO - Response status: 206
Response headers:
    'Content-Length': '676885'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:55 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DA322A92"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '56373b99-401e-0087-2dc3-5307b8000000'
    'x-ms-client-request-id': 'a2611067-bfb6-11ef-b3ec-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:14:20 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpi9vbvxnw.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  43%|████▎     | 193/445 [23:48<30:26,  7.25s/it]2024-12-22 01:14:27,280 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p15.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a6a8d0d1-bfb6-11ef-9b58-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpi9vbvxnw.pdf を削除しました。
194/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p15.pdf

2024-12-22 01:14:28,003 - INFO - Response status: 206
Response headers:
    'Content-Length': '355128'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D3EF1987"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '425ce94c-601e-00df-0ec3-5303c3000000'
    'x-ms-client-request-id': 'a6a8d0d1-bfb6-11ef-9b58-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:14:27 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp83snnxyf.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  44%|████▎     | 194/445 [24:00<36:26,  8.71s/it]2024-12-22 01:14:39,411 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p150.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ade3d27a-bfb6-11ef-ba6b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp83snnxyf.pdf を削除しました。
195/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p150.pdf

2024-12-22 01:14:40,142 - INFO - Response status: 206
Response headers:
    'Content-Length': '560535'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D2691E98"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6e0607ca-201e-00fa-70c3-539b70000000'
    'x-ms-client-request-id': 'ade3d27a-bfb6-11ef-ba6b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:14:39 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyp3334dl.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  44%|████▍     | 195/445 [24:07<34:23,  8.26s/it]2024-12-22 01:14:46,599 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p151.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b22ca285-bfb6-11ef-b300-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyp3334dl.pdf を削除しました。
196/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p151.pdf

2024-12-22 01:14:47,334 - INFO - Response status: 206
Response headers:
    'Content-Length': '436830'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D2D659BD"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a792f589-601e-009b-42c3-53dfaf000000'
    'x-ms-client-request-id': 'b22ca285-bfb6-11ef-b300-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:14:46 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5veipmq9.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  44%|████▍     | 196/445 [24:14<32:42,  7.88s/it]2024-12-22 01:14:53,610 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p152.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b65a77a4-bfb6-11ef-8a87-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5veipmq9.pdf を削除しました。
197/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p152.pdf

2024-12-22 01:14:54,356 - INFO - Response status: 206
Response headers:
    'Content-Length': '442500'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D2383376"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '3f6b63a8-701e-00e9-75c3-53ae91000000'
    'x-ms-client-request-id': 'b65a77a4-bfb6-11ef-8a87-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:14:53 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbkriadqv.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  44%|████▍     | 197/445 [24:21<31:33,  7.64s/it]2024-12-22 01:15:00,673 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p153.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ba9029c1-bfb6-11ef-a148-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbkriadqv.pdf を削除しました。
198/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p153.pdf

2024-12-22 01:15:01,406 - INFO - Response status: 206
Response headers:
    'Content-Length': '506741'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D1A82E38"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8b843917-201e-0014-3bc3-5391f3000000'
    'x-ms-client-request-id': 'ba9029c1-bfb6-11ef-a148-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:15:01 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0a9f0we0.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  44%|████▍     | 198/445 [24:28<30:33,  7.42s/it]2024-12-22 01:15:07,597 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p154.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'beb09533-bfb6-11ef-9583-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0a9f0we0.pdf を削除しました。
199/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p154.pdf

2024-12-22 01:15:08,325 - INFO - Response status: 206
Response headers:
    'Content-Length': '444494'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D103CD57"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '36e7f4b4-001e-0080-7cc3-53f13d000000'
    'x-ms-client-request-id': 'beb09533-bfb6-11ef-9583-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:15:08 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpli8iuqjq.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  45%|████▍     | 199/445 [24:35<29:59,  7.32s/it]2024-12-22 01:15:14,667 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p16.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c2e75efa-bfb6-11ef-afa2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpli8iuqjq.pdf を削除しました。
200/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p16.pdf

2024-12-22 01:15:15,406 - INFO - Response status: 206
Response headers:
    'Content-Length': '488178'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D3382FF4"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '31890b97-e01e-0002-6bc3-53506d000000'
    'x-ms-client-request-id': 'c2e75efa-bfb6-11ef-afa2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:15:14 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp71hsxmp0.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  45%|████▍     | 200/445 [24:42<29:31,  7.23s/it]2024-12-22 01:15:21,700 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p17.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c718a18a-bfb6-11ef-bbfc-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp71hsxmp0.pdf を削除しました。
201/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p17.pdf

2024-12-22 01:15:22,435 - INFO - Response status: 206
Response headers:
    'Content-Length': '355731'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D3484A8B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a942e935-501e-00dc-1ac3-5300c4000000'
    'x-ms-client-request-id': 'c718a18a-bfb6-11ef-bbfc-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:15:22 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphcktov8a.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  45%|████▌     | 201/445 [24:49<29:12,  7.18s/it]2024-12-22 01:15:28,763 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p18.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'cb4e5e01-bfb6-11ef-9c3f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphcktov8a.pdf を削除しました。
202/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p18.pdf

2024-12-22 01:15:29,498 - INFO - Response status: 206
Response headers:
    'Content-Length': '487991'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:51 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D8109E99"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '048087cb-c01e-005a-4dc3-535416000000'
    'x-ms-client-request-id': 'cb4e5e01-bfb6-11ef-9c3f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:15:29 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpm4nsi5go.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  45%|████▌     | 202/445 [24:56<28:58,  7.16s/it]2024-12-22 01:15:35,864 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p19.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'cf89cb1b-bfb6-11ef-8d22-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpm4nsi5go.pdf を削除しました。
203/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p19.pdf

2024-12-22 01:15:36,590 - INFO - Response status: 206
Response headers:
    'Content-Length': '355088'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:51 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D7E41B52"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'c19e980c-f01e-0059-4ac3-535711000000'
    'x-ms-client-request-id': 'cf89cb1b-bfb6-11ef-8d22-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:15:35 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpx15hp7gf.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  46%|████▌     | 203/445 [25:03<28:38,  7.10s/it]2024-12-22 01:15:42,837 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p2.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd3b1e7aa-bfb6-11ef-96a0-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpx15hp7gf.pdf を削除しました。
204/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p2.pdf

2024-12-22 01:15:43,580 - INFO - Response status: 206
Response headers:
    'Content-Length': '425671'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D57BEAAA"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fd6b009b-201e-009c-10c3-53292a000000'
    'x-ms-client-request-id': 'd3b1e7aa-bfb6-11ef-96a0-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:15:43 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpt1y33lqc.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  46%|████▌     | 204/445 [25:10<28:32,  7.10s/it]2024-12-22 01:15:49,949 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p20.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd7eefaab-bfb6-11ef-86b5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpt1y33lqc.pdf を削除しました。
205/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p20.pdf

2024-12-22 01:15:50,671 - INFO - Response status: 206
Response headers:
    'Content-Length': '488524'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D711B258"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '03c92bfc-801e-0012-23c3-53668b000000'
    'x-ms-client-request-id': 'd7eefaab-bfb6-11ef-86b5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:15:50 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmproxjlrpg.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  46%|████▌     | 205/445 [25:18<28:26,  7.11s/it]2024-12-22 01:15:57,067 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p21.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'dc2d1a7d-bfb6-11ef-a614-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmproxjlrpg.pdf を削除しました。
206/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p21.pdf

2024-12-22 01:15:57,847 - INFO - Response status: 206
Response headers:
    'Content-Length': '355634'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:50 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D734CA5F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e162dcec-001e-0003-1dc3-535190000000'
    'x-ms-client-request-id': 'dc2d1a7d-bfb6-11ef-a614-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:15:57 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2abhnedu.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  46%|████▋     | 206/445 [25:25<28:50,  7.24s/it]2024-12-22 01:16:04,612 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p22.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e0ac7302-bfb6-11ef-a3e1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2abhnedu.pdf を削除しました。
207/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p22.pdf

2024-12-22 01:16:05,354 - INFO - Response status: 206
Response headers:
    'Content-Length': '489186'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D6559E6C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'bedc0d40-401e-0026-21c3-53c923000000'
    'x-ms-client-request-id': 'e0ac7302-bfb6-11ef-a3e1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:16:05 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplhcw1bxb.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  47%|████▋     | 207/445 [25:32<28:27,  7.17s/it]2024-12-22 01:16:11,635 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p23.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e4dc1b08-bfb6-11ef-a4ee-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplhcw1bxb.pdf を削除しました。
208/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p23.pdf

2024-12-22 01:16:12,367 - INFO - Response status: 206
Response headers:
    'Content-Length': '355764'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D6A697BC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f3bc7e86-b01e-0011-23c3-53658c000000'
    'x-ms-client-request-id': 'e4dc1b08-bfb6-11ef-a4ee-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:16:11 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp883jbx3m.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  47%|████▋     | 208/445 [25:39<28:05,  7.11s/it]2024-12-22 01:16:18,598 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p24.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e9027fff-bfb6-11ef-96c6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp883jbx3m.pdf を削除しました。
209/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p24.pdf

2024-12-22 01:16:19,353 - INFO - Response status: 206
Response headers:
    'Content-Length': '486221'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:51 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D81EE66C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6b968346-e01e-008a-65c3-53e8b4000000'
    'x-ms-client-request-id': 'e9027fff-bfb6-11ef-96c6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:16:18 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpj8u_eode.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  47%|████▋     | 209/445 [25:46<27:59,  7.12s/it]2024-12-22 01:16:25,729 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p25.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ed42ac7e-bfb6-11ef-9502-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpj8u_eode.pdf を削除しました。
210/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p25.pdf

2024-12-22 01:16:26,466 - INFO - Response status: 206
Response headers:
    'Content-Length': '353534'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:50 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D7B3A4E4"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '434fa2b0-301e-004f-52c3-53968f000000'
    'x-ms-client-request-id': 'ed42ac7e-bfb6-11ef-9502-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:16:25 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpj4lj85kt.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  47%|████▋     | 210/445 [25:53<27:41,  7.07s/it]2024-12-22 01:16:32,687 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p26.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f168620c-bfb6-11ef-8972-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpj4lj85kt.pdf を削除しました。
211/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p26.pdf

2024-12-22 01:16:33,414 - INFO - Response status: 206
Response headers:
    'Content-Length': '307584'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D9055D0E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'efc0abac-901e-00ac-03c3-537300000000'
    'x-ms-client-request-id': 'f168620c-bfb6-11ef-8972-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:16:33 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyep2pn0c.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  47%|████▋     | 211/445 [26:00<27:25,  7.03s/it]2024-12-22 01:16:39,634 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p27.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f58c6797-bfb6-11ef-adc1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyep2pn0c.pdf を削除しました。
212/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p27.pdf

2024-12-22 01:16:40,394 - INFO - Response status: 206
Response headers:
    'Content-Length': '226903'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D905362B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ba6a22e9-801e-00b3-60c3-53a810000000'
    'x-ms-client-request-id': 'f58c6797-bfb6-11ef-adc1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:16:40 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxak1r37v.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  48%|████▊     | 212/445 [26:07<27:01,  6.96s/it]2024-12-22 01:16:46,420 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p28.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f997ac0e-bfb6-11ef-85f2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxak1r37v.pdf を削除しました。
213/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p28.pdf

2024-12-22 01:16:47,172 - INFO - Response status: 206
Response headers:
    'Content-Length': '308641'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D412A63A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e61a150c-201e-0072-37c3-5323a9000000'
    'x-ms-client-request-id': 'f997ac0e-bfb6-11ef-85f2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:16:47 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmprqt3ujcr.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  48%|████▊     | 213/445 [26:14<26:54,  6.96s/it]2024-12-22 01:16:53,385 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p29.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'fdbe9e95-bfb6-11ef-8e04-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmprqt3ujcr.pdf を削除しました。
214/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p29.pdf

2024-12-22 01:16:54,129 - INFO - Response status: 206
Response headers:
    'Content-Length': '226539'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D3CAF160"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '318a143d-e01e-0002-64c3-53506d000000'
    'x-ms-client-request-id': 'fdbe9e95-bfb6-11ef-8e04-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:16:53 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmprblddysh.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  48%|████▊     | 214/445 [26:21<26:32,  6.90s/it]2024-12-22 01:17:00,131 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p3.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '01c3bd9b-bfb7-11ef-9451-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmprblddysh.pdf を削除しました。
215/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p3.pdf

2024-12-22 01:17:00,842 - INFO - Response status: 206
Response headers:
    'Content-Length': '475846'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D59B3656"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '811ec0ee-701e-0103-57c3-5317c5000000'
    'x-ms-client-request-id': '01c3bd9b-bfb7-11ef-9451-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:17:00 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxlyaz_nc.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  48%|████▊     | 215/445 [26:28<26:28,  6.91s/it]2024-12-22 01:17:07,065 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p30.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '05e60ba0-bfb7-11ef-9b48-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxlyaz_nc.pdf を削除しました。
216/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p30.pdf

2024-12-22 01:17:07,793 - INFO - Response status: 206
Response headers:
    'Content-Length': '309146'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:51 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D810EC5B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '42848115-501e-00fe-72c3-536ef2000000'
    'x-ms-client-request-id': '05e60ba0-bfb7-11ef-9b48-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:17:07 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplghlng_n.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  49%|████▊     | 216/445 [26:35<26:25,  6.92s/it]2024-12-22 01:17:14,029 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p31.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0a0c95a9-bfb7-11ef-8556-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplghlng_n.pdf を削除しました。
217/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p31.pdf

2024-12-22 01:17:14,770 - INFO - Response status: 206
Response headers:
    'Content-Length': '229062'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:50 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D7B18464"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '10645e8d-f01e-0016-49c3-539309000000'
    'x-ms-client-request-id': '0a0c95a9-bfb7-11ef-8556-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:17:15 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdpikbtl9.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  49%|████▉     | 217/445 [26:41<26:16,  6.92s/it]2024-12-22 01:17:20,922 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p32.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0e286bde-bfb7-11ef-885e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdpikbtl9.pdf を削除しました。
218/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p32.pdf

2024-12-22 01:17:21,654 - INFO - Response status: 206
Response headers:
    'Content-Length': '147568'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:52 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D87C06FE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '38e94c3a-001e-0021-2fc3-533fa6000000'
    'x-ms-client-request-id': '0e286bde-bfb7-11ef-885e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:17:21 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3_uphecs.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  49%|████▉     | 218/445 [26:48<26:01,  6.88s/it]2024-12-22 01:17:27,714 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p33.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1234c3f7-bfb7-11ef-9369-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3_uphecs.pdf を削除しました。
219/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p33.pdf

2024-12-22 01:17:28,469 - INFO - Response status: 206
Response headers:
    'Content-Length': '246983'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D9066D55"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'c8e234fb-301e-0029-30c3-5324d5000000'
    'x-ms-client-request-id': '1234c3f7-bfb7-11ef-9369-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:17:28 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0glwodn0.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  49%|████▉     | 219/445 [26:55<25:43,  6.83s/it]2024-12-22 01:17:34,426 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p34.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '163508fc-bfb7-11ef-9467-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0glwodn0.pdf を削除しました。
220/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p34.pdf

2024-12-22 01:17:35,195 - INFO - Response status: 206
Response headers:
    'Content-Length': '687102'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D700FC4F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '52435817-201e-0079-6ec3-533bdd000000'
    'x-ms-client-request-id': '163508fc-bfb7-11ef-9467-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:17:34 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmph8df8l97.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  49%|████▉     | 220/445 [27:02<26:04,  6.95s/it]2024-12-22 01:17:41,665 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p35.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1a8594f5-bfb7-11ef-bce9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmph8df8l97.pdf を削除しました。
221/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p35.pdf

2024-12-22 01:17:42,380 - INFO - Response status: 206
Response headers:
    'Content-Length': '640004'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:50 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D7260DD5"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '23819638-301e-00e5-4bc3-534060000000'
    'x-ms-client-request-id': '1a8594f5-bfb7-11ef-bce9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:17:42 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpiot202w3.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  50%|████▉     | 221/445 [27:09<26:14,  7.03s/it]2024-12-22 01:17:48,872 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p36.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1ed140ec-bfb7-11ef-a24c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpiot202w3.pdf を削除しました。
222/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p36.pdf

2024-12-22 01:17:49,647 - INFO - Response status: 206
Response headers:
    'Content-Length': '435726'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D6B38188"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ef02422f-501e-00d7-6cc3-5318b0000000'
    'x-ms-client-request-id': '1ed140ec-bfb7-11ef-a24c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:17:49 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp75nyrac6.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  50%|████▉     | 222/445 [27:17<26:15,  7.06s/it]2024-12-22 01:17:56,018 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p37.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2313b100-bfb7-11ef-99e4-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp75nyrac6.pdf を削除しました。
223/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p37.pdf

2024-12-22 01:17:56,772 - INFO - Response status: 206
Response headers:
    'Content-Length': '855164'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D641B7B0"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e2e8c31a-901e-00e3-03c3-53b718000000'
    'x-ms-client-request-id': '2313b100-bfb7-11ef-99e4-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:17:56 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmppw8ozd1o.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  50%|█████     | 223/445 [27:24<26:23,  7.13s/it]2024-12-22 01:18:03,317 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p38.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '276d398f-bfb7-11ef-9b92-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmppw8ozd1o.pdf を削除しました。
224/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p38.pdf

2024-12-22 01:18:04,057 - INFO - Response status: 206
Response headers:
    'Content-Length': '638374'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D4E49A8B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'af58fb37-501e-005f-7cc3-53a069000000'
    'x-ms-client-request-id': '276d398f-bfb7-11ef-9b92-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:18:04 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpr2ed44_g.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  50%|█████     | 224/445 [27:31<26:38,  7.23s/it]2024-12-22 01:18:10,778 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p39.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2bdfd9c6-bfb7-11ef-88ca-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpr2ed44_g.pdf を削除しました。
225/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p39.pdf

2024-12-22 01:18:11,732 - INFO - Response status: 206
Response headers:
    'Content-Length': '433842'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D4EFD882"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fbb6d017-101e-00f2-54c3-538003000000'
    'x-ms-client-request-id': '2bdfd9c6-bfb7-11ef-88ca-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:18:12 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2dv3ubek.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  51%|█████     | 225/445 [27:39<26:35,  7.25s/it]2024-12-22 01:18:18,078 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p4.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3039a1e1-bfb7-11ef-9d0f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2dv3ubek.pdf を削除しました。
226/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p4.pdf

2024-12-22 01:18:18,789 - INFO - Response status: 206
Response headers:
    'Content-Length': '536031'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D407B610"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '819f3eda-601e-003a-13c3-531134000000'
    'x-ms-client-request-id': '3039a1e1-bfb7-11ef-9d0f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:18:18 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6e0kaaez.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  51%|█████     | 226/445 [27:46<26:18,  7.21s/it]2024-12-22 01:18:25,184 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p40.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '34760e95-bfb7-11ef-a05f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6e0kaaez.pdf を削除しました。
227/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p40.pdf

2024-12-22 01:18:25,936 - INFO - Response status: 206
Response headers:
    'Content-Length': '469465'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D9876857"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b22acefc-e01e-0046-7ac3-538c01000000'
    'x-ms-client-request-id': '34760e95-bfb7-11ef-a05f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:18:25 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpku2ue_od.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  51%|█████     | 227/445 [27:53<25:57,  7.15s/it]2024-12-22 01:18:32,186 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p41.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '38a26863-bfb7-11ef-90e1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpku2ue_od.pdf を削除しました。
228/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p41.pdf

2024-12-22 01:18:32,913 - INFO - Response status: 206
Response headers:
    'Content-Length': '722073'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:54 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DA07EEB6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cd99bc33-301e-006d-28c3-53f8b9000000'
    'x-ms-client-request-id': '38a26863-bfb7-11ef-90e1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:18:32 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpi_0r9jpb.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  51%|█████     | 228/445 [28:00<25:52,  7.16s/it]2024-12-22 01:18:39,363 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p42.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3ce998f1-bfb7-11ef-8405-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpi_0r9jpb.pdf を削除しました。
229/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p42.pdf

2024-12-22 01:18:40,243 - INFO - Response status: 206
Response headers:
    'Content-Length': '584512'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DB6D8DBD"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fef65b52-801e-009a-5ec3-53de52000000'
    'x-ms-client-request-id': '3ce998f1-bfb7-11ef-8405-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:18:40 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxev71jba.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  51%|█████▏    | 229/445 [28:07<26:06,  7.25s/it]2024-12-22 01:18:46,842 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p43.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '415e9954-bfb7-11ef-897f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxev71jba.pdf を削除しました。
230/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p43.pdf

2024-12-22 01:18:47,593 - INFO - Response status: 206
Response headers:
    'Content-Length': '571924'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:56 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DAE547DE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '7a3e1868-e01e-0064-20c4-53e237000000'
    'x-ms-client-request-id': '415e9954-bfb7-11ef-897f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:18:47 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk2g5syz_.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  52%|█████▏    | 230/445 [28:15<25:54,  7.23s/it]2024-12-22 01:18:54,019 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p44.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '45a5e4ee-bfb7-11ef-9fc3-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk2g5syz_.pdf を削除しました。
231/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p44.pdf

2024-12-22 01:18:54,773 - INFO - Response status: 206
Response headers:
    'Content-Length': '656509'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:00 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DD59C6B6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '821ad3d3-a01e-002c-2ec4-53d0aa000000'
    'x-ms-client-request-id': '45a5e4ee-bfb7-11ef-9fc3-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:18:54 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2001mo65.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  52%|█████▏    | 231/445 [28:22<25:52,  7.25s/it]2024-12-22 01:19:01,330 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p45.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4a016427-bfb7-11ef-b0ce-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2001mo65.pdf を削除しました。
232/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p45.pdf

2024-12-22 01:19:02,192 - INFO - Response status: 206
Response headers:
    'Content-Length': '473329'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:59 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DCC2769A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e474ba6e-501e-00f5-36c4-537686000000'
    'x-ms-client-request-id': '4a016427-bfb7-11ef-b0ce-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:19:02 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk2spinkb.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  52%|█████▏    | 232/445 [28:29<25:47,  7.27s/it]2024-12-22 01:19:08,625 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p46.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4e5a942c-bfb7-11ef-90b5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk2spinkb.pdf を削除しました。
233/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p46.pdf

2024-12-22 01:19:09,364 - INFO - Response status: 206
Response headers:
    'Content-Length': '617538'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DB721C81"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8965919e-b01e-0038-1ac4-5313ce000000'
    'x-ms-client-request-id': '4e5a942c-bfb7-11ef-90b5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:19:09 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmns0mqqq.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  52%|█████▏    | 233/445 [28:36<25:35,  7.24s/it]2024-12-22 01:19:15,814 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p47.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '52a38086-bfb7-11ef-af33-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmns0mqqq.pdf を削除しました。
234/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p47.pdf

2024-12-22 01:19:16,665 - INFO - Response status: 206
Response headers:
    'Content-Length': '571451'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:58 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DC231942"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e24502de-e01e-004d-6ec4-539475000000'
    'x-ms-client-request-id': '52a38086-bfb7-11ef-af33-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:19:16 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjl8reo_d.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  53%|█████▎    | 234/445 [28:44<25:30,  7.25s/it]2024-12-22 01:19:23,091 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p48.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '56f9ebf7-bfb7-11ef-92a6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjl8reo_d.pdf を削除しました。
235/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p48.pdf

2024-12-22 01:19:23,811 - INFO - Response status: 206
Response headers:
    'Content-Length': '645161'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D10DAD4B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ce043d79-701e-00a6-62c4-536a89000000'
    'x-ms-client-request-id': '56f9ebf7-bfb7-11ef-92a6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:19:23 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpszfvyu2h.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  53%|█████▎    | 235/445 [28:51<25:21,  7.25s/it]2024-12-22 01:19:30,317 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p49.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5b48892c-bfb7-11ef-8a22-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpszfvyu2h.pdf を削除しました。
236/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p49.pdf

2024-12-22 01:19:31,031 - INFO - Response status: 206
Response headers:
    'Content-Length': '569445'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64CFCE0921"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '17310027-501e-0076-46c4-53d62b000000'
    'x-ms-client-request-id': '5b48892c-bfb7-11ef-8a22-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:19:30 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptcfibpvl.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  53%|█████▎    | 236/445 [28:58<25:06,  7.21s/it]2024-12-22 01:19:37,440 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p5.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5f877196-bfb7-11ef-9988-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptcfibpvl.pdf を削除しました。
237/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p5.pdf

2024-12-22 01:19:38,153 - INFO - Response status: 206
Response headers:
    'Content-Length': '455154'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D41B2829"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e61b3aad-201e-0072-69c4-5323a9000000'
    'x-ms-client-request-id': '5f877196-bfb7-11ef-9988-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:19:38 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsiicm66t.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  53%|█████▎    | 237/445 [29:05<24:40,  7.12s/it]2024-12-22 01:19:44,350 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p50.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '63a5b9b4-bfb7-11ef-81a5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsiicm66t.pdf を削除しました。
238/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p50.pdf

2024-12-22 01:19:45,123 - INFO - Response status: 206
Response headers:
    'Content-Length': '923240'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:00 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DD699376"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ceafee22-901e-002f-38c4-53d3ad000000'
    'x-ms-client-request-id': '63a5b9b4-bfb7-11ef-81a5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:19:44 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsi1j7vqt.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  53%|█████▎    | 238/445 [29:12<24:47,  7.19s/it]2024-12-22 01:19:51,694 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p51.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '68066066-bfb7-11ef-b51c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsi1j7vqt.pdf を削除しました。
239/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p51.pdf

2024-12-22 01:19:52,512 - INFO - Response status: 206
Response headers:
    'Content-Length': '691889'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:59 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DCC13F72"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8b556789-401e-00c3-40c4-53dbd4000000'
    'x-ms-client-request-id': '68066066-bfb7-11ef-b51c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:19:52 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdav7zsj7.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  54%|█████▎    | 239/445 [29:19<24:45,  7.21s/it]2024-12-22 01:19:58,962 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p52.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6c5b7a6e-bfb7-11ef-8055-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdav7zsj7.pdf を削除しました。
240/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p52.pdf

2024-12-22 01:19:59,705 - INFO - Response status: 206
Response headers:
    'Content-Length': '585869'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DB6F12A7"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '828edf92-001e-00ed-47c4-535b13000000'
    'x-ms-client-request-id': '6c5b7a6e-bfb7-11ef-8055-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:19:59 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4a57s6wi.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  54%|█████▍    | 240/445 [29:27<24:46,  7.25s/it]2024-12-22 01:20:06,301 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p53.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '70bb1b1a-bfb7-11ef-9687-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4a57s6wi.pdf を削除しました。
241/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p53.pdf

2024-12-22 01:20:07,070 - INFO - Response status: 206
Response headers:
    'Content-Length': '748717'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DBEA47C2"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '0a7830eb-001e-002a-40c4-5327d2000000'
    'x-ms-client-request-id': '70bb1b1a-bfb7-11ef-9687-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:20:06 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9d3oqjg1.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  54%|█████▍    | 241/445 [29:34<24:48,  7.30s/it]2024-12-22 01:20:13,706 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p54.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '752532fe-bfb7-11ef-87a6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9d3oqjg1.pdf を削除しました。
242/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p54.pdf

2024-12-22 01:20:14,521 - INFO - Response status: 206
Response headers:
    'Content-Length': '709689'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:54 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D98DF0B1"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '38ea81c0-001e-0021-20c4-533fa6000000'
    'x-ms-client-request-id': '752532fe-bfb7-11ef-87a6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:20:14 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyt9762ye.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  54%|█████▍    | 242/445 [29:41<24:38,  7.28s/it]2024-12-22 01:20:20,956 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p55.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '797759fa-bfb7-11ef-9df4-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyt9762ye.pdf を削除しました。
243/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p55.pdf

2024-12-22 01:20:21,714 - INFO - Response status: 206
Response headers:
    'Content-Length': '660163'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:54 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D9FD4C40"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6b999ca8-e01e-008a-76c4-53e8b4000000'
    'x-ms-client-request-id': '797759fa-bfb7-11ef-9df4-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:20:21 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4uytcan9.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  55%|█████▍    | 243/445 [29:49<24:37,  7.31s/it]2024-12-22 01:20:28,346 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p56.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7ddf0777-bfb7-11ef-8f5c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4uytcan9.pdf を削除しました。
244/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p56.pdf

2024-12-22 01:20:29,098 - INFO - Response status: 206
Response headers:
    'Content-Length': '486134'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DB688A4C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '122d9c0a-901e-0042-4dc4-537983000000'
    'x-ms-client-request-id': '7ddf0777-bfb7-11ef-8f5c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:20:29 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmprq2j3x19.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  55%|█████▍    | 244/445 [29:56<24:24,  7.29s/it]2024-12-22 01:20:35,570 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p57.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '822d648f-bfb7-11ef-b370-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmprq2j3x19.pdf を削除しました。
245/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p57.pdf

2024-12-22 01:20:36,354 - INFO - Response status: 206
Response headers:
    'Content-Length': '544337'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:56 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DAE56EBF"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b5a9bc46-401e-0100-34c4-5314c2000000'
    'x-ms-client-request-id': '822d648f-bfb7-11ef-b370-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:20:36 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9xqtuxgz.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  55%|█████▌    | 245/445 [30:03<24:14,  7.27s/it]2024-12-22 01:20:42,807 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p58.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '867d98b9-bfb7-11ef-a101-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9xqtuxgz.pdf を削除しました。
246/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p58.pdf

2024-12-22 01:20:43,546 - INFO - Response status: 206
Response headers:
    'Content-Length': '484089'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D2A9140F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b22ff341-c01e-00bf-66c4-5346e1000000'
    'x-ms-client-request-id': '867d98b9-bfb7-11ef-a101-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:20:43 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7xk1n3yf.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  55%|█████▌    | 246/445 [30:10<23:56,  7.22s/it]2024-12-22 01:20:49,908 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p59.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8ab8f429-bfb7-11ef-8aa5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7xk1n3yf.pdf を削除しました。
247/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p59.pdf

2024-12-22 01:20:50,659 - INFO - Response status: 206
Response headers:
    'Content-Length': '131515'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D2875A0C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8444d2ab-501e-00ba-2ac4-53b29e000000'
    'x-ms-client-request-id': '8ab8f429-bfb7-11ef-8aa5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:20:50 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpn_kju3ep.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  56%|█████▌    | 247/445 [30:17<23:20,  7.07s/it]2024-12-22 01:20:56,642 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p6.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8ebca499-bfb7-11ef-8d78-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpn_kju3ep.pdf を削除しました。
248/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p6.pdf

2024-12-22 01:20:57,384 - INFO - Response status: 206
Response headers:
    'Content-Length': '455858'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D3478807"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e35b3a13-301e-00aa-61c4-538478000000'
    'x-ms-client-request-id': '8ebca499-bfb7-11ef-8d78-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:20:56 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpue9eglhd.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  56%|█████▌    | 248/445 [30:24<23:08,  7.05s/it]2024-12-22 01:21:03,633 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p60.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '92e76968-bfb7-11ef-9fa6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpue9eglhd.pdf を削除しました。
249/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p60.pdf

2024-12-22 01:21:04,403 - INFO - Response status: 206
Response headers:
    'Content-Length': '466853'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64CFC27D60"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'dfd3868f-a01e-00a4-75c4-536873000000'
    'x-ms-client-request-id': '92e76968-bfb7-11ef-9fa6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:21:04 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp01vhun_6.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  56%|█████▌    | 249/445 [30:31<23:07,  7.08s/it]2024-12-22 01:21:10,775 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p61.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '97290888-bfb7-11ef-8edf-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp01vhun_6.pdf を削除しました。
250/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p61.pdf

2024-12-22 01:21:11,527 - INFO - Response status: 206
Response headers:
    'Content-Length': '524229'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64CFD139E5"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f3fc1dd0-a01e-004a-16c4-5362f0000000'
    'x-ms-client-request-id': '97290888-bfb7-11ef-8edf-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:21:11 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdnq_z1rp.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  56%|█████▌    | 250/445 [30:38<23:05,  7.11s/it]2024-12-22 01:21:17,943 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p62.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9b6f022e-bfb7-11ef-9228-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdnq_z1rp.pdf を削除しました。
251/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p62.pdf

2024-12-22 01:21:18,688 - INFO - Response status: 206
Response headers:
    'Content-Length': '450148'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D108D0C2"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2312fd97-d01e-0028-69c4-532528000000'
    'x-ms-client-request-id': '9b6f022e-bfb7-11ef-9228-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:21:18 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgub693ry.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  56%|█████▋    | 251/445 [30:45<22:51,  7.07s/it]2024-12-22 01:21:24,929 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p63.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9f98ed9e-bfb7-11ef-814f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgub693ry.pdf を削除しました。
252/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p63.pdf

2024-12-22 01:21:25,660 - INFO - Response status: 206
Response headers:
    'Content-Length': '445999'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D174392D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e8572268-501e-0039-02c4-531233000000'
    'x-ms-client-request-id': '9f98ed9e-bfb7-11ef-814f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:21:25 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5p7yi8n6.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  57%|█████▋    | 252/445 [30:52<22:43,  7.06s/it]2024-12-22 01:21:31,978 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p64.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a3cc73e2-bfb7-11ef-83c4-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5p7yi8n6.pdf を削除しました。
253/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p64.pdf

2024-12-22 01:21:32,702 - INFO - Response status: 206
Response headers:
    'Content-Length': '514302'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D27986EB"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '15eef278-f01e-0070-76c4-532153000000'
    'x-ms-client-request-id': 'a3cc73e2-bfb7-11ef-83c4-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:21:32 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_1uix9wp.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  57%|█████▋    | 253/445 [31:00<22:40,  7.09s/it]2024-12-22 01:21:39,126 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p65.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a80f2679-bfb7-11ef-a76b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_1uix9wp.pdf を削除しました。
254/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p65.pdf

2024-12-22 01:21:39,892 - INFO - Response status: 206
Response headers:
    'Content-Length': '737128'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D2B67275"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9901cdb0-c01e-0037-4fc4-53fe38000000'
    'x-ms-client-request-id': 'a80f2679-bfb7-11ef-a76b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:21:39 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7h60eb79.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  57%|█████▋    | 254/445 [31:07<22:45,  7.15s/it]2024-12-22 01:21:46,415 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p66.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ac6768eb-bfb7-11ef-9f3c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7h60eb79.pdf を削除しました。
255/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p66.pdf

2024-12-22 01:21:47,150 - INFO - Response status: 206
Response headers:
    'Content-Length': '390526'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D219D126"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '42adcef9-a01e-0068-63c4-530cc6000000'
    'x-ms-client-request-id': 'ac6768eb-bfb7-11ef-9f3c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:21:46 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpf_60vtjo.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  57%|█████▋    | 255/445 [31:14<22:25,  7.08s/it]2024-12-22 01:21:53,347 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p67.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b0892c23-bfb7-11ef-8bb5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpf_60vtjo.pdf を削除しました。
256/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p67.pdf

2024-12-22 01:21:54,095 - INFO - Response status: 206
Response headers:
    'Content-Length': '725664'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D1C925A5"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '60a54fdf-701e-00e2-6dc4-53b6e5000000'
    'x-ms-client-request-id': 'b0892c23-bfb7-11ef-8bb5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:21:54 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpqqozr3_u.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  58%|█████▊    | 256/445 [31:21<22:25,  7.12s/it]2024-12-22 01:22:00,551 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p68.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b4d47068-bfb7-11ef-bc6c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpqqozr3_u.pdf を削除しました。
257/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p68.pdf

2024-12-22 01:22:01,298 - INFO - Response status: 206
Response headers:
    'Content-Length': '664972'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:54 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D98B34A3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4d0bee5c-101e-001c-2ec4-538a80000000'
    'x-ms-client-request-id': 'b4d47068-bfb7-11ef-bc6c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:22:01 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpoohx70ib.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  58%|█████▊    | 257/445 [31:28<22:30,  7.18s/it]2024-12-22 01:22:07,883 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p69.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b93344bc-bfb7-11ef-88cf-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpoohx70ib.pdf を削除しました。
258/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p69.pdf

2024-12-22 01:22:08,600 - INFO - Response status: 206
Response headers:
    'Content-Length': '655013'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:54 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DA0B1F76"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f2b21b43-201e-00be-45c4-53471c000000'
    'x-ms-client-request-id': 'b93344bc-bfb7-11ef-88cf-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:22:08 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpd4iep8jb.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  58%|█████▊    | 258/445 [31:36<22:20,  7.17s/it]2024-12-22 01:22:15,022 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p7.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'bd748af3-bfb7-11ef-9a2f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpd4iep8jb.pdf を削除しました。
259/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p7.pdf

2024-12-22 01:22:15,781 - INFO - Response status: 206
Response headers:
    'Content-Length': '455564'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D3A98533"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cacabb09-d01e-0045-63c4-538f06000000'
    'x-ms-client-request-id': 'bd748af3-bfb7-11ef-9a2f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:22:15 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5zb22f82.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  58%|█████▊    | 259/445 [31:43<22:03,  7.11s/it]2024-12-22 01:22:22,005 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p70.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c19e085b-bfb7-11ef-96c3-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5zb22f82.pdf を削除しました。
260/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p70.pdf

2024-12-22 01:22:22,728 - INFO - Response status: 206
Response headers:
    'Content-Length': '396961'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D276CADE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '3008a505-601e-00fd-68c4-536df5000000'
    'x-ms-client-request-id': 'c19e085b-bfb7-11ef-96c3-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:22:22 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpykl1zroj.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  58%|█████▊    | 260/445 [31:50<21:53,  7.10s/it]2024-12-22 01:22:29,079 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p71.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c5d57ff3-bfb7-11ef-aae5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpykl1zroj.pdf を削除しました。
261/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p71.pdf

2024-12-22 01:22:29,814 - INFO - Response status: 206
Response headers:
    'Content-Length': '597696'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D2CFF84A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '1067678a-f01e-0016-4ec4-539309000000'
    'x-ms-client-request-id': 'c5d57ff3-bfb7-11ef-aae5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:22:29 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb1aa8rgf.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  59%|█████▊    | 261/445 [31:57<21:52,  7.14s/it]2024-12-22 01:22:36,292 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p72.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ca220225-bfb7-11ef-b54a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb1aa8rgf.pdf を削除しました。
262/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p72.pdf

2024-12-22 01:22:37,022 - INFO - Response status: 206
Response headers:
    'Content-Length': '482225'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D217FE70"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f3bf9f0e-b01e-0011-17c4-53658c000000'
    'x-ms-client-request-id': 'ca220225-bfb7-11ef-b54a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:22:37 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_djwy_9b.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  59%|█████▉    | 262/445 [32:04<21:34,  7.07s/it]2024-12-22 01:22:43,225 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p73.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ce43e69f-bfb7-11ef-b9ac-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_djwy_9b.pdf を削除しました。
263/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p73.pdf

2024-12-22 01:22:43,972 - INFO - Response status: 206
Response headers:
    'Content-Length': '518570'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D1DC4A0B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9d508996-401e-002d-7cc4-53d157000000'
    'x-ms-client-request-id': 'ce43e69f-bfb7-11ef-b9ac-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:22:44 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpugg_berv.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  59%|█████▉    | 263/445 [32:11<21:34,  7.11s/it]2024-12-22 01:22:50,432 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p74.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd28fa571-bfb7-11ef-a183-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpugg_berv.pdf を削除しました。
264/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p74.pdf

2024-12-22 01:22:51,201 - INFO - Response status: 206
Response headers:
    'Content-Length': '655899'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:38 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D03A0D25"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b23109ed-c01e-00bf-1cc4-5346e1000000'
    'x-ms-client-request-id': 'd28fa571-bfb7-11ef-a183-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:22:51 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvfk_4pdg.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  59%|█████▉    | 264/445 [32:18<21:35,  7.16s/it]2024-12-22 01:22:57,698 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p75.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd6e45be8-bfb7-11ef-9ac0-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvfk_4pdg.pdf を削除しました。
265/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p75.pdf

2024-12-22 01:22:58,437 - INFO - Response status: 206
Response headers:
    'Content-Length': '624625'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64CFCD46B9"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6ce27bdd-f01e-00f8-4dc4-53998a000000'
    'x-ms-client-request-id': 'd6e45be8-bfb7-11ef-9ac0-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:22:58 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpcgxngy2l.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  60%|█████▉    | 265/445 [32:25<21:35,  7.20s/it]2024-12-22 01:23:04,978 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p76.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'db3b2a40-bfb7-11ef-a7e9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpcgxngy2l.pdf を削除しました。
266/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p76.pdf

2024-12-22 01:23:05,710 - INFO - Response status: 206
Response headers:
    'Content-Length': '430307'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D0ED515C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8445b515-501e-00ba-30c4-53b29e000000'
    'x-ms-client-request-id': 'db3b2a40-bfb7-11ef-a7e9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:23:05 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_f5x_2bm.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  60%|█████▉    | 266/445 [32:32<21:16,  7.13s/it]2024-12-22 01:23:11,961 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p77.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'df64c057-bfb7-11ef-84b7-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_f5x_2bm.pdf を削除しました。
267/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p77.pdf

2024-12-22 01:23:12,689 - INFO - Response status: 206
Response headers:
    'Content-Length': '536008'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D17FC4EF"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '5244d58b-201e-0079-7bc4-533bdd000000'
    'x-ms-client-request-id': 'df64c057-bfb7-11ef-84b7-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:23:12 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxnwm7zke.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  60%|██████    | 267/445 [32:40<21:09,  7.13s/it]2024-12-22 01:23:19,088 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p78.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e3a42672-bfb7-11ef-93f2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxnwm7zke.pdf を削除しました。
268/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p78.pdf

2024-12-22 01:23:19,818 - INFO - Response status: 206
Response headers:
    'Content-Length': '525175'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:00 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DD5537F1"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cd9c1fc3-301e-006d-6dc4-53f8b9000000'
    'x-ms-client-request-id': 'e3a42672-bfb7-11ef-93f2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:23:19 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp60xwpzks.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  60%|██████    | 268/445 [32:52<25:32,  8.66s/it]2024-12-22 01:23:31,315 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p79.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'eaedf26f-bfb7-11ef-b3ec-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp60xwpzks.pdf を削除しました。
269/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p79.pdf

2024-12-22 01:23:32,097 - INFO - Response status: 206
Response headers:
    'Content-Length': '554256'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:59 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DCC29D7F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '17f8dae0-201e-00b5-70c4-535f68000000'
    'x-ms-client-request-id': 'eaedf26f-bfb7-11ef-b3ec-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:23:31 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsalac7c4.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  60%|██████    | 269/445 [32:59<24:11,  8.25s/it]2024-12-22 01:23:38,600 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p8.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ef456ee2-bfb7-11ef-9a44-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsalac7c4.pdf を削除しました。
270/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p8.pdf

2024-12-22 01:23:39,351 - INFO - Response status: 206
Response headers:
    'Content-Length': '456431'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:51 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D7D4C346"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'da816641-c01e-0078-47c4-533a20000000'
    'x-ms-client-request-id': 'ef456ee2-bfb7-11ef-9a44-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:23:39 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp52_uvlzb.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  61%|██████    | 270/445 [33:06<22:59,  7.88s/it]2024-12-22 01:23:45,627 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p80.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f375c0ce-bfb7-11ef-8680-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp52_uvlzb.pdf を削除しました。
271/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p80.pdf

2024-12-22 01:23:46,349 - INFO - Response status: 206
Response headers:
    'Content-Length': '615305'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:56 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DAE7DD05"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '30093075-601e-00fd-57c4-536df5000000'
    'x-ms-client-request-id': 'f375c0ce-bfb7-11ef-8680-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:23:46 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxt3mgshn.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  61%|██████    | 271/445 [33:18<26:38,  9.19s/it]2024-12-22 01:23:57,861 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p81.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'fac08633-bfb7-11ef-8b6d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxt3mgshn.pdf を削除しました。
272/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p81.pdf

2024-12-22 01:23:58,583 - INFO - Response status: 206
Response headers:
    'Content-Length': '640358'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DB672C44"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4261b907-601e-00df-1ac4-5303c3000000'
    'x-ms-client-request-id': 'fac08633-bfb7-11ef-8b6d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:23:58 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0kt3avju.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  61%|██████    | 272/445 [33:26<24:51,  8.62s/it]2024-12-22 01:24:05,166 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p82.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ff1b26bb-bfb7-11ef-87a3-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0kt3avju.pdf を削除しました。
273/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p82.pdf

2024-12-22 01:24:05,896 - INFO - Response status: 206
Response headers:
    'Content-Length': '456161'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:54 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D9E76BE7"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '89f6e896-c01e-0096-59c4-5330a3000000'
    'x-ms-client-request-id': 'ff1b26bb-bfb7-11ef-87a3-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:24:06 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpguvk3l6r.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  61%|██████▏   | 273/445 [33:48<36:35, 12.76s/it]2024-12-22 01:24:27,592 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p83.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0c79055e-bfb8-11ef-a1ae-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpguvk3l6r.pdf を削除しました。
274/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p83.pdf

2024-12-22 01:24:28,343 - INFO - Response status: 206
Response headers:
    'Content-Length': '601239'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:54 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D9BDA4B3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cbdb9af3-101e-0017-1cc4-5392f4000000'
    'x-ms-client-request-id': '0c79055e-bfb8-11ef-a1ae-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:24:28 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp8krxoait.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  62%|██████▏   | 274/445 [33:55<31:43, 11.13s/it]2024-12-22 01:24:34,913 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p84.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '10d639e7-bfb8-11ef-838b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp8krxoait.pdf を削除しました。
275/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p84.pdf

2024-12-22 01:24:35,667 - INFO - Response status: 206
Response headers:
    'Content-Length': '571586'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:58 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DBEB7EEC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e252dc18-301e-00cc-6dc4-533622000000'
    'x-ms-client-request-id': '10d639e7-bfb8-11ef-838b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:24:34 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjwjpgl2z.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  62%|██████▏   | 275/445 [34:03<28:09,  9.94s/it]2024-12-22 01:24:42,069 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p85.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '151a2505-bfb8-11ef-a645-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjwjpgl2z.pdf を削除しました。
276/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p85.pdf

2024-12-22 01:24:42,793 - INFO - Response status: 206
Response headers:
    'Content-Length': '666921'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DBCA8770"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9c73bcdd-201e-00d3-76c4-53ed32000000'
    'x-ms-client-request-id': '151a2505-bfb8-11ef-a645-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:24:42 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdgm6vs8r.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  62%|██████▏   | 276/445 [34:10<25:40,  9.11s/it]2024-12-22 01:24:49,261 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p86.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1963940d-bfb8-11ef-b601-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdgm6vs8r.pdf を削除しました。
277/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p86.pdf

2024-12-22 01:24:50,012 - INFO - Response status: 206
Response headers:
    'Content-Length': '432108'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:59 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DCC35FF3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6fcca9b4-f01e-007b-47c4-533927000000'
    'x-ms-client-request-id': '1963940d-bfb8-11ef-b601-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:24:49 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpspaanwic.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  62%|██████▏   | 277/445 [34:17<23:43,  8.47s/it]2024-12-22 01:24:56,244 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p87.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1d8cf9df-bfb8-11ef-b0d4-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpspaanwic.pdf を削除しました。
278/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p87.pdf

2024-12-22 01:24:56,957 - INFO - Response status: 206
Response headers:
    'Content-Length': '496369'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:00 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DD555ED6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '621a6a36-801e-00b8-80c4-53b064000000'
    'x-ms-client-request-id': '1d8cf9df-bfb8-11ef-b0d4-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:24:56 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpx4h2j9_i.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  62%|██████▏   | 278/445 [34:24<22:19,  8.02s/it]2024-12-22 01:25:03,199 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p88.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '21b22412-bfb8-11ef-ad92-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpx4h2j9_i.pdf を削除しました。
279/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p88.pdf

2024-12-22 01:25:03,963 - INFO - Response status: 206
Response headers:
    'Content-Length': '63515'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D1616292"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fdcfe495-301e-0088-75c4-53ea4e000000'
    'x-ms-client-request-id': '21b22412-bfb8-11ef-ad92-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:25:04 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6iwavuv8.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  63%|██████▎   | 279/445 [34:30<20:56,  7.57s/it]2024-12-22 01:25:09,732 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p89.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '259723c9-bfb8-11ef-b4a4-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6iwavuv8.pdf を削除しました。
280/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p89.pdf

2024-12-22 01:25:10,447 - INFO - Response status: 206
Response headers:
    'Content-Length': '185909'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D1368B30"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '700a3340-f01e-003f-6ac4-53e54b000000'
    'x-ms-client-request-id': '259723c9-bfb8-11ef-b4a4-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:25:10 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4hlrbe0l.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  63%|██████▎   | 280/445 [34:37<20:03,  7.29s/it]2024-12-22 01:25:16,375 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p9.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '298cc666-bfb8-11ef-9c68-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4hlrbe0l.pdf を削除しました。
281/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p9.pdf

2024-12-22 01:25:17,113 - INFO - Response status: 206
Response headers:
    'Content-Length': '455470'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:51 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D8129830"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd3b9641d-d01e-0023-2bc4-533d5c000000'
    'x-ms-client-request-id': '298cc666-bfb8-11ef-9c68-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:25:16 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpntnubjyc.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  63%|██████▎   | 281/445 [34:42<18:22,  6.72s/it]2024-12-22 01:25:21,767 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p90.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2cc36b16-bfb8-11ef-bfc9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpntnubjyc.pdf を削除しました。
282/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p90.pdf

2024-12-22 01:25:22,505 - INFO - Response status: 206
Response headers:
    'Content-Length': '605346'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DBE7B2AE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '698a4ccf-101e-007a-47c4-5338da000000'
    'x-ms-client-request-id': '2cc36b16-bfb8-11ef-bfc9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:25:22 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpv_u8c4sa.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  63%|██████▎   | 282/445 [34:49<18:38,  6.86s/it]2024-12-22 01:25:28,946 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p91.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '310b082b-bfb8-11ef-86c0-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpv_u8c4sa.pdf を削除しました。
283/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p91.pdf

2024-12-22 01:25:29,677 - INFO - Response status: 206
Response headers:
    'Content-Length': '485448'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:57 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DBD7BEFA"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fa8bafa3-a01e-0027-2ec4-53c8de000000'
    'x-ms-client-request-id': '310b082b-bfb8-11ef-86c0-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:25:29 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpchpzxcb2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  64%|██████▎   | 283/445 [34:56<18:37,  6.90s/it]2024-12-22 01:25:35,933 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p92.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3535124a-bfb8-11ef-afdf-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpchpzxcb2.pdf を削除しました。
284/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p92.pdf

2024-12-22 01:25:36,691 - INFO - Response status: 206
Response headers:
    'Content-Length': '669612'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:59 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DCC35FF3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8291353a-001e-00ed-01c4-535b13000000'
    'x-ms-client-request-id': '3535124a-bfb8-11ef-afdf-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:25:36 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxmj1zeap.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  64%|██████▍   | 284/445 [35:04<18:49,  7.02s/it]2024-12-22 01:25:43,228 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p93.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '398e3e71-bfb8-11ef-bb8e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxmj1zeap.pdf を削除しました。
285/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p93.pdf

2024-12-22 01:25:43,990 - INFO - Response status: 206
Response headers:
    'Content-Length': '491584'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:00 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DD5E07B3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6e500ed0-d01e-0067-5fc4-53e130000000'
    'x-ms-client-request-id': '398e3e71-bfb8-11ef-bb8e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:25:43 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0wywp2wu.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  64%|██████▍   | 285/445 [35:11<18:42,  7.02s/it]2024-12-22 01:25:50,247 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p94.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3dbd4080-bfb8-11ef-8ef1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0wywp2wu.pdf を削除しました。
286/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p94.pdf

2024-12-22 01:25:50,991 - INFO - Response status: 206
Response headers:
    'Content-Length': '462052'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:56 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DAE78F3B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '17339f6d-501e-0076-04c5-53d62b000000'
    'x-ms-client-request-id': '3dbd4080-bfb8-11ef-8ef1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:25:51 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp57nkq5w6.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  64%|██████▍   | 286/445 [35:18<18:35,  7.01s/it]2024-12-22 01:25:57,258 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p95.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '41eb1210-bfb8-11ef-9bd4-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp57nkq5w6.pdf を削除しました。
287/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p95.pdf

2024-12-22 01:25:58,017 - INFO - Response status: 206
Response headers:
    'Content-Length': '533825'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:56 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64DAE851B3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '39064880-b01e-00dd-26c5-530139000000'
    'x-ms-client-request-id': '41eb1210-bfb8-11ef-9bd4-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:25:57 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwm9ig2p1.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  64%|██████▍   | 287/445 [35:25<18:38,  7.08s/it]2024-12-22 01:26:04,484 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p96.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4639a9ea-bfb8-11ef-852f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwm9ig2p1.pdf を削除しました。
288/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p96.pdf

2024-12-22 01:26:05,478 - INFO - Response status: 206
Response headers:
    'Content-Length': '622394'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:54 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D9FB52AF"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '91ce4715-a01e-000e-63c5-53be9c000000'
    'x-ms-client-request-id': '4639a9ea-bfb8-11ef-852f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:26:05 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpg2ma3v67.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  65%|██████▍   | 288/445 [35:33<18:51,  7.21s/it]2024-12-22 01:26:11,986 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p97.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4ab26895-bfb8-11ef-bc95-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpg2ma3v67.pdf を削除しました。
289/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p97.pdf

2024-12-22 01:26:12,811 - INFO - Response status: 206
Response headers:
    'Content-Length': '414797'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:53 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D9876857"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b2327ac0-c01e-00bf-17c5-5346e1000000'
    'x-ms-client-request-id': '4ab26895-bfb8-11ef-bc95-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:26:12 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpivlpxz9x.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  65%|██████▍   | 289/445 [35:40<18:38,  7.17s/it]2024-12-22 01:26:19,077 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p98.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4eec32d3-bfb8-11ef-ae83-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpivlpxz9x.pdf を削除しました。
290/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p98.pdf

2024-12-22 01:26:19,798 - INFO - Response status: 206
Response headers:
    'Content-Length': '599297'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D1FBBC90"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '1d1a6ae0-c01e-00b4-1ac5-535e95000000'
    'x-ms-client-request-id': '4eec32d3-bfb8-11ef-ae83-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:26:20 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpv998wzt1.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  65%|██████▌   | 290/445 [35:47<18:31,  7.17s/it]2024-12-22 01:26:26,243 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/2%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p99.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5331cab9-bfb8-11ef-a378-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpv998wzt1.pdf を削除しました。
291/445 処理中
コンテナ名: rag-pdf, Blob名: 2年_中学校理科_指導書_板書例_/2年_中学校理科_指導書_板書例_p99.pdf

2024-12-22 01:26:26,982 - INFO - Response status: 206
Response headers:
    'Content-Length': '546755'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:01:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64D1F167EF"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '43643a33-001e-00a9-40c5-53877f000000'
    'x-ms-client-request-id': '5331cab9-bfb8-11ef-a378-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:26:26 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpj0v_agq7.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  65%|██████▌   | 291/445 [35:54<18:30,  7.21s/it]2024-12-22 01:26:33,559 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p1.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '578e1c21-bfb8-11ef-919d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpj0v_agq7.pdf を削除しました。
292/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p1.pdf

2024-12-22 01:26:34,310 - INFO - Response status: 206
Response headers:
    'Content-Length': '166582'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64FA1C4BA8"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '568ae2d4-101e-00db-76c5-53f641000000'
    'x-ms-client-request-id': '578e1c21-bfb8-11ef-919d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:26:34 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpv7ak806p.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  66%|██████▌   | 292/445 [36:01<18:05,  7.09s/it]2024-12-22 01:26:40,374 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p10.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5b9e11ab-bfb8-11ef-bebc-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpv7ak806p.pdf を削除しました。
293/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p10.pdf

2024-12-22 01:26:41,130 - INFO - Response status: 206
Response headers:
    'Content-Length': '498360'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:31 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EFDB43A9"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '73255aaa-301e-0083-11c5-53f23a000000'
    'x-ms-client-request-id': '5b9e11ab-bfb8-11ef-bebc-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:26:40 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgx8kuth3.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  66%|██████▌   | 293/445 [36:08<18:00,  7.11s/it]2024-12-22 01:26:47,518 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p100.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5fe00f62-bfb8-11ef-ba2c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgx8kuth3.pdf を削除しました。
294/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p100.pdf

2024-12-22 01:26:48,263 - INFO - Response status: 206
Response headers:
    'Content-Length': '451910'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:33 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F0DC2959"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '0594836c-801e-0056-71c5-53bae7000000'
    'x-ms-client-request-id': '5fe00f62-bfb8-11ef-ba2c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:26:48 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0234dxq2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  66%|██████▌   | 294/445 [36:15<17:50,  7.09s/it]2024-12-22 01:26:54,556 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p101.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6411f9f5-bfb8-11ef-978e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0234dxq2.pdf を削除しました。
295/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p101.pdf

2024-12-22 01:26:55,278 - INFO - Response status: 206
Response headers:
    'Content-Length': '446497'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:32 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F07F5689"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b1c118ed-001e-00e6-6fc5-534367000000'
    'x-ms-client-request-id': '6411f9f5-bfb8-11ef-978e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:26:54 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptokaxgnm.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  66%|██████▋   | 295/445 [36:22<17:39,  7.06s/it]2024-12-22 01:27:01,560 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p102.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '683ebb57-bfb8-11ef-bdb2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptokaxgnm.pdf を削除しました。
296/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p102.pdf

2024-12-22 01:27:02,287 - INFO - Response status: 206
Response headers:
    'Content-Length': '668033'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:34 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F17F2C0E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cd366e43-f01e-00b7-38c5-535d92000000'
    'x-ms-client-request-id': '683ebb57-bfb8-11ef-bdb2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:27:01 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmputunhxi8.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  67%|██████▋   | 296/445 [36:29<17:42,  7.13s/it]2024-12-22 01:27:08,843 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p103.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6c95fa8f-bfb8-11ef-a154-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmputunhxi8.pdf を削除しました。
297/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p103.pdf

2024-12-22 01:27:09,580 - INFO - Response status: 206
Response headers:
    'Content-Length': '510912'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:35 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F23C76F3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '7ae4711e-d01e-00ab-65c5-538585000000'
    'x-ms-client-request-id': '6c95fa8f-bfb8-11ef-a154-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:27:09 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpuctg7j6k.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  67%|██████▋   | 297/445 [36:36<17:29,  7.09s/it]2024-12-22 01:27:15,836 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p104.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '70c12761-bfb8-11ef-8973-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpuctg7j6k.pdf を削除しました。
298/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p104.pdf

2024-12-22 01:27:16,601 - INFO - Response status: 206
Response headers:
    'Content-Length': '971027'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:30 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EF6A631F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '45abbdb1-701e-008f-5cc5-531ccb000000'
    'x-ms-client-request-id': '70c12761-bfb8-11ef-8973-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:27:16 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp8oodxi7g.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  67%|██████▋   | 298/445 [36:44<17:30,  7.15s/it]2024-12-22 01:27:23,125 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p105.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '751950ac-bfb8-11ef-9950-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp8oodxi7g.pdf を削除しました。
299/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p105.pdf

2024-12-22 01:27:23,880 - INFO - Response status: 206
Response headers:
    'Content-Length': '634247'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:31 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F0044854"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '0545b0d1-901e-00a7-4cc5-536b74000000'
    'x-ms-client-request-id': '751950ac-bfb8-11ef-9950-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:27:23 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7xrvltgk.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  67%|██████▋   | 299/445 [36:51<17:28,  7.18s/it]2024-12-22 01:27:30,396 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p106.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '796eb7ab-bfb8-11ef-ac18-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7xrvltgk.pdf を削除しました。
300/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p106.pdf

2024-12-22 01:27:31,143 - INFO - Response status: 206
Response headers:
    'Content-Length': '589655'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:30 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EF488255"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '5c6b9f1f-201e-0097-47c5-53315e000000'
    'x-ms-client-request-id': '796eb7ab-bfb8-11ef-ac18-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:27:31 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpnbxxlpn2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  67%|██████▋   | 300/445 [36:58<17:22,  7.19s/it]2024-12-22 01:27:37,590 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p107.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7db88c75-bfb8-11ef-9de7-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpnbxxlpn2.pdf を削除しました。
301/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p107.pdf

2024-12-22 01:27:38,332 - INFO - Response status: 206
Response headers:
    'Content-Length': '699785'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:29 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EEBD32B0"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e24b7837-e01e-004d-7ec5-539475000000'
    'x-ms-client-request-id': '7db88c75-bfb8-11ef-9de7-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:27:38 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3r77nk0n.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  68%|██████▊   | 301/445 [37:05<17:21,  7.23s/it]2024-12-22 01:27:44,933 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p108.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8218fa36-bfb8-11ef-b4a2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3r77nk0n.pdf を削除しました。
302/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p108.pdf

2024-12-22 01:27:45,716 - INFO - Response status: 206
Response headers:
    'Content-Length': '563658'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F96C117C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2365a8f2-401e-0062-3ac5-53154f000000'
    'x-ms-client-request-id': '8218fa36-bfb8-11ef-b4a2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:27:45 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmph4n8mrze.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  68%|██████▊   | 302/445 [37:13<17:14,  7.23s/it]2024-12-22 01:27:52,170 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p109.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '86693ab9-bfb8-11ef-8723-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmph4n8mrze.pdf を削除しました。
303/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p109.pdf

2024-12-22 01:27:52,899 - INFO - Response status: 206
Response headers:
    'Content-Length': '598144'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64FA01B5AB"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '7325ca25-301e-0083-4fc5-53f23a000000'
    'x-ms-client-request-id': '86693ab9-bfb8-11ef-8723-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:27:52 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5uowniry.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  68%|██████▊   | 303/445 [37:20<17:06,  7.23s/it]2024-12-22 01:27:59,387 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p11.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8ab6771c-bfb8-11ef-bbb5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5uowniry.pdf を削除しました。
304/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p11.pdf

2024-12-22 01:28:00,139 - INFO - Response status: 206
Response headers:
    'Content-Length': '445178'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:30 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EF5A6F8E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4264e8c1-601e-00df-4ec5-5303c3000000'
    'x-ms-client-request-id': '8ab6771c-bfb8-11ef-bbb5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:27:59 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_edm6j4a.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  68%|██████▊   | 304/445 [37:27<16:57,  7.21s/it]2024-12-22 01:28:06,565 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p110.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8efdae57-bfb8-11ef-b93f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_edm6j4a.pdf を削除しました。
305/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p110.pdf

2024-12-22 01:28:07,298 - INFO - Response status: 206
Response headers:
    'Content-Length': '536770'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:30 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EF53C04B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '15f20ca2-f01e-0070-40c5-532153000000'
    'x-ms-client-request-id': '8efdae57-bfb8-11ef-b93f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:28:06 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpnlrw1n8h.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  69%|██████▊   | 305/445 [37:34<16:55,  7.25s/it]2024-12-22 01:28:13,911 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p111.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '935eae65-bfb8-11ef-90c3-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpnlrw1n8h.pdf を削除しました。
306/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p111.pdf

2024-12-22 01:28:14,670 - INFO - Response status: 206
Response headers:
    'Content-Length': '538836'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:31 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EFF53E15"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '03ceafd1-801e-0012-22c5-53668b000000'
    'x-ms-client-request-id': '935eae65-bfb8-11ef-90c3-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:28:14 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpy85sroif.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  69%|██████▉   | 306/445 [37:42<16:50,  7.27s/it]2024-12-22 01:28:21,219 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p112.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '97b9c690-bfb8-11ef-a863-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpy85sroif.pdf を削除しました。
307/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p112.pdf

2024-12-22 01:28:21,976 - INFO - Response status: 206
Response headers:
    'Content-Length': '468824'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:29 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EEB048DE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '35581e12-d01e-006c-46c5-53f944000000'
    'x-ms-client-request-id': '97b9c690-bfb8-11ef-a863-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:28:22 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplcqvyxbe.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  69%|██████▉   | 307/445 [37:49<16:39,  7.24s/it]2024-12-22 01:28:28,397 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p113.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9c0117ea-bfb8-11ef-8782-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplcqvyxbe.pdf を削除しました。
308/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p113.pdf

2024-12-22 01:28:29,131 - INFO - Response status: 206
Response headers:
    'Content-Length': '628448'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:29 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EEC2F8A0"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '99053006-c01e-0037-46c5-53fe38000000'
    'x-ms-client-request-id': '9c0117ea-bfb8-11ef-8782-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:28:28 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyvo09e2j.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  69%|██████▉   | 308/445 [37:56<16:32,  7.25s/it]2024-12-22 01:28:35,656 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p114.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a054975d-bfb8-11ef-9fde-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyvo09e2j.pdf を削除しました。
309/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p114.pdf

2024-12-22 01:28:36,424 - INFO - Response status: 206
Response headers:
    'Content-Length': '548401'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:33 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F0F340DB"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '28829559-d01e-0089-5fc5-53ebb3000000'
    'x-ms-client-request-id': 'a054975d-bfb8-11ef-9fde-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:28:36 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk0su31e5.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  69%|██████▉   | 309/445 [38:03<16:24,  7.24s/it]2024-12-22 01:28:42,873 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p115.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a4a1d095-bfb8-11ef-81c2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpk0su31e5.pdf を削除しました。
310/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p115.pdf

2024-12-22 01:28:43,632 - INFO - Response status: 206
Response headers:
    'Content-Length': '553225'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:32 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F0748D42"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9a492292-c01e-001e-44c5-53887a000000'
    'x-ms-client-request-id': 'a4a1d095-bfb8-11ef-81c2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:28:43 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplm59r9dd.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  70%|██████▉   | 310/445 [38:11<16:18,  7.25s/it]2024-12-22 01:28:50,146 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p116.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a8f78b09-bfb8-11ef-b381-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplm59r9dd.pdf を削除しました。
311/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p116.pdf

2024-12-22 01:28:50,986 - INFO - Response status: 206
Response headers:
    'Content-Length': '77909'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:34 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F1AF7B90"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '7196f350-901e-000d-5bc5-53bd9b000000'
    'x-ms-client-request-id': 'a8f78b09-bfb8-11ef-b381-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:28:51 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmprl4g1me3.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  70%|██████▉   | 311/445 [38:17<15:48,  7.08s/it]2024-12-22 01:28:56,815 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p117.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'acf120c9-bfb8-11ef-bf6d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmprl4g1me3.pdf を削除しました。
312/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p117.pdf

2024-12-22 01:28:57,561 - INFO - Response status: 206
Response headers:
    'Content-Length': '189732'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:34 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F192297F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '0671c7ae-101e-0071-09c5-5320ae000000'
    'x-ms-client-request-id': 'acf120c9-bfb8-11ef-bf6d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:28:57 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp630gw_yu.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  70%|███████   | 312/445 [38:24<15:26,  6.97s/it]2024-12-22 01:29:03,530 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p118.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b0f1f51a-bfb8-11ef-aba7-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp630gw_yu.pdf を削除しました。
313/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p118.pdf

2024-12-22 01:29:04,299 - INFO - Response status: 206
Response headers:
    'Content-Length': '512506'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F8EF3087"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6ce6ecc8-f01e-00f8-4cc5-53998a000000'
    'x-ms-client-request-id': 'b0f1f51a-bfb8-11ef-aba7-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:29:03 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyc57kl0b.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  70%|███████   | 313/445 [38:31<15:32,  7.06s/it]2024-12-22 01:29:10,820 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p119.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b54a34d2-bfb8-11ef-826f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyc57kl0b.pdf を削除しました。
314/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p119.pdf

2024-12-22 01:29:11,541 - INFO - Response status: 206
Response headers:
    'Content-Length': '520024'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F8C2AD49"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ad532fdb-e01e-00c5-32c5-532cac000000'
    'x-ms-client-request-id': 'b54a34d2-bfb8-11ef-826f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:29:11 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2la1_hec.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  71%|███████   | 314/445 [38:38<15:22,  7.04s/it]2024-12-22 01:29:17,818 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p12.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b9761735-bfb8-11ef-aae6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2la1_hec.pdf を削除しました。
315/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p12.pdf

2024-12-22 01:29:18,554 - INFO - Response status: 206
Response headers:
    'Content-Length': '498746'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:29 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EEB26975"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '3348f2eb-301e-0066-5ac5-53e0cd000000'
    'x-ms-client-request-id': 'b9761735-bfb8-11ef-aae6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:29:18 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsf6ozllx.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  71%|███████   | 315/445 [38:46<15:22,  7.10s/it]2024-12-22 01:29:25,044 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p120.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'bdc496ab-bfb8-11ef-b62a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsf6ozllx.pdf を削除しました。
316/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p120.pdf

2024-12-22 01:29:25,820 - INFO - Response status: 206
Response headers:
    'Content-Length': '513117'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F9C0891F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '89f958f1-c01e-0096-6bc5-5330a3000000'
    'x-ms-client-request-id': 'bdc496ab-bfb8-11ef-b62a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:29:25 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmps5s06o89.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  71%|███████   | 316/445 [38:53<15:25,  7.17s/it]2024-12-22 01:29:32,388 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p121.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c2253f5b-bfb8-11ef-b02f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmps5s06o89.pdf を削除しました。
317/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p121.pdf

2024-12-22 01:29:33,122 - INFO - Response status: 206
Response headers:
    'Content-Length': '601728'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F9CBA03C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fbbc4eac-101e-00f2-47c5-538003000000'
    'x-ms-client-request-id': 'c2253f5b-bfb8-11ef-b02f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:29:32 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7_e0js0l.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  71%|███████   | 317/445 [39:00<15:19,  7.18s/it]2024-12-22 01:29:39,586 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p122.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c66fa930-bfb8-11ef-9573-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7_e0js0l.pdf を削除しました。
318/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p122.pdf

2024-12-22 01:29:40,317 - INFO - Response status: 206
Response headers:
    'Content-Length': '533770'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64FA834C2D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '81a5342b-601e-003a-6ec5-531134000000'
    'x-ms-client-request-id': 'c66fa930-bfb8-11ef-9573-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:29:39 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpx3g_232_.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  71%|███████▏  | 318/445 [39:07<15:12,  7.19s/it]2024-12-22 01:29:46,795 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p123.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'cabb9ffa-bfb8-11ef-a9b9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpx3g_232_.pdf を削除しました。
319/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p123.pdf

2024-12-22 01:29:47,566 - INFO - Response status: 206
Response headers:
    'Content-Length': '504933'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64FA5433BC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '966a13f2-201e-0036-1fc5-53ffc5000000'
    'x-ms-client-request-id': 'cabb9ffa-bfb8-11ef-a9b9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:29:46 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplvzpj2uh.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  72%|███████▏  | 319/445 [39:15<15:10,  7.23s/it]2024-12-22 01:29:54,110 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p124.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'cf17b5c6-bfb8-11ef-80e3-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplvzpj2uh.pdf を削除しました。
320/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p124.pdf

2024-12-22 01:29:54,891 - INFO - Response status: 206
Response headers:
    'Content-Length': '534562'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F90C5BBC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'fd726b4e-201e-009c-42c5-53292a000000'
    'x-ms-client-request-id': 'cf17b5c6-bfb8-11ef-80e3-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:29:54 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpz9n0m2om.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  72%|███████▏  | 320/445 [39:22<15:06,  7.25s/it]2024-12-22 01:30:01,429 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p125.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd374a5c2-bfb8-11ef-a933-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpz9n0m2om.pdf を削除しました。
321/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p125.pdf

2024-12-22 01:30:02,210 - INFO - Response status: 206
Response headers:
    'Content-Length': '598933'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F896EC87"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2366a379-401e-0062-52c5-53154f000000'
    'x-ms-client-request-id': 'd374a5c2-bfb8-11ef-a933-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:30:01 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwn29lcwp.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  72%|███████▏  | 321/445 [39:29<15:00,  7.27s/it]2024-12-22 01:30:08,719 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p126.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd7ccfdd6-bfb8-11ef-86b5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwn29lcwp.pdf を削除しました。
322/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p126.pdf

2024-12-22 01:30:09,478 - INFO - Response status: 206
Response headers:
    'Content-Length': '663069'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F85744F9"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'c80974d6-301e-000b-26c5-534ae3000000'
    'x-ms-client-request-id': 'd7ccfdd6-bfb8-11ef-86b5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:30:09 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmw0_j938.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  72%|███████▏  | 322/445 [39:37<14:53,  7.27s/it]2024-12-22 01:30:15,988 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p127.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'dc220e88-bfb8-11ef-b24e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmw0_j938.pdf を削除しました。
323/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p127.pdf

2024-12-22 01:30:16,737 - INFO - Response status: 206
Response headers:
    'Content-Length': '498148'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F8353D3B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '5df9a0e8-c01e-009d-01c5-5328d7000000'
    'x-ms-client-request-id': 'dc220e88-bfb8-11ef-b24e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:30:16 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpiipvfk7f.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  73%|███████▎  | 323/445 [39:44<14:45,  7.26s/it]2024-12-22 01:30:23,225 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p128.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e072683f-bfb8-11ef-9091-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpiipvfk7f.pdf を削除しました。
324/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p128.pdf

2024-12-22 01:30:23,950 - INFO - Response status: 206
Response headers:
    'Content-Length': '563812'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:33 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F13A80FF"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd93bc378-301e-00c7-39c5-532e56000000'
    'x-ms-client-request-id': 'e072683f-bfb8-11ef-9091-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:30:23 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4g3n737v.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  73%|███████▎  | 324/445 [39:51<14:33,  7.22s/it]2024-12-22 01:30:30,362 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p129.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e4b36bdc-bfb8-11ef-b06b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4g3n737v.pdf を削除しました。
325/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p129.pdf

2024-12-22 01:30:31,112 - INFO - Response status: 206
Response headers:
    'Content-Length': '540286'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:32 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F0383D4D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'be82b5a3-401e-000f-13c5-53bf61000000'
    'x-ms-client-request-id': 'e4b36bdc-bfb8-11ef-b06b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:30:31 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpasnta3t2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  73%|███████▎  | 325/445 [39:58<14:29,  7.25s/it]2024-12-22 01:30:37,667 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p13.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e90e11f6-bfb8-11ef-9e36-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpasnta3t2.pdf を削除しました。
326/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p13.pdf

2024-12-22 01:30:38,440 - INFO - Response status: 206
Response headers:
    'Content-Length': '360500'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:29 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EEAE0182"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ceb29d71-901e-002f-2fc5-53d3ad000000'
    'x-ms-client-request-id': 'e90e11f6-bfb8-11ef-9e36-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:30:38 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpcdjp5nf3.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  73%|███████▎  | 326/445 [40:05<14:15,  7.19s/it]2024-12-22 01:30:44,730 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p130.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ed43bb36-bfb8-11ef-b2ad-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpcdjp5nf3.pdf を削除しました。
327/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p130.pdf

2024-12-22 01:30:45,490 - INFO - Response status: 206
Response headers:
    'Content-Length': '679679'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F95803BF"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '5e7dc33c-001e-0065-2fc5-53e3ca000000'
    'x-ms-client-request-id': 'ed43bb36-bfb8-11ef-b2ad-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:30:45 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7t8gj57k.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  73%|███████▎  | 327/445 [40:13<14:12,  7.23s/it]2024-12-22 01:30:52,042 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p131.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f19f877c-bfb8-11ef-94a4-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7t8gj57k.pdf を削除しました。
328/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p131.pdf

2024-12-22 01:30:52,787 - INFO - Response status: 206
Response headers:
    'Content-Length': '609614'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F883A14B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9c7687a3-201e-00d3-36c5-53ed32000000'
    'x-ms-client-request-id': 'f19f877c-bfb8-11ef-94a4-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:30:53 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwuejynrm.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  74%|███████▎  | 328/445 [40:20<14:09,  7.26s/it]2024-12-22 01:30:59,392 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p132.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f600fb76-bfb8-11ef-b2e2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwuejynrm.pdf を削除しました。
329/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p132.pdf

2024-12-22 01:31:00,146 - INFO - Response status: 206
Response headers:
    'Content-Length': '464269'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F7B09CD5"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ef25c349-901e-006b-42c5-530fc1000000'
    'x-ms-client-request-id': 'f600fb76-bfb8-11ef-b2e2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:31:00 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2n9eh27t.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  74%|███████▍  | 329/445 [40:27<13:52,  7.18s/it]2024-12-22 01:31:06,376 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p133.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'fa2aa945-bfb8-11ef-821c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2n9eh27t.pdf を削除しました。
330/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p133.pdf

2024-12-22 01:31:07,128 - INFO - Response status: 206
Response headers:
    'Content-Length': '502931'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F82A4D03"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '482362d8-d01e-00e4-28c5-53419d000000'
    'x-ms-client-request-id': 'fa2aa945-bfb8-11ef-821c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:31:06 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpi8k_33c2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  74%|███████▍  | 330/445 [40:34<13:47,  7.20s/it]2024-12-22 01:31:13,606 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p134.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'fe79e77a-bfb8-11ef-bb61-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpi8k_33c2.pdf を削除しました。
331/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p134.pdf

2024-12-22 01:31:14,338 - INFO - Response status: 206
Response headers:
    'Content-Length': '595599'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F9B6824E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a432e2fc-f01e-009e-69c5-532bd0000000'
    'x-ms-client-request-id': 'fe79e77a-bfb8-11ef-bb61-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:31:14 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb10m3d0c.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  74%|███████▍  | 331/445 [40:41<13:44,  7.23s/it]2024-12-22 01:31:20,933 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p135.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '02d7ead3-bfb9-11ef-a869-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb10m3d0c.pdf を削除しました。
332/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p135.pdf

2024-12-22 01:31:21,700 - INFO - Response status: 206
Response headers:
    'Content-Length': '501600'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F9C4F0FD"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e86d50e5-601e-0057-30c5-53bb1a000000'
    'x-ms-client-request-id': '02d7ead3-bfb9-11ef-a869-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:31:21 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmph6jv0l1q.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  75%|███████▍  | 332/445 [40:49<13:40,  7.26s/it]2024-12-22 01:31:28,252 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p136.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '07349ef4-bfb9-11ef-a650-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmph6jv0l1q.pdf を削除しました。
333/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p136.pdf

2024-12-22 01:31:29,028 - INFO - Response status: 206
Response headers:
    'Content-Length': '735957'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64FA87663F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8e4a1e9e-601e-00b2-78c5-53a9ed000000'
    'x-ms-client-request-id': '07349ef4-bfb9-11ef-a650-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:31:28 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp15vttudr.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  75%|███████▍  | 333/445 [40:56<13:37,  7.30s/it]2024-12-22 01:31:35,657 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p137.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0b9eb062-bfb9-11ef-b36b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp15vttudr.pdf を削除しました。
334/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p137.pdf

2024-12-22 01:31:36,419 - INFO - Response status: 206
Response headers:
    'Content-Length': '466507'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64FA6206EB"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '93924e39-e01e-00e7-58c5-53429a000000'
    'x-ms-client-request-id': '0b9eb062-bfb9-11ef-b36b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:31:36 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpzwf1q1p_.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  75%|███████▌  | 334/445 [41:03<13:24,  7.24s/it]2024-12-22 01:31:42,761 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p138.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0fda9d71-bfb9-11ef-9823-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpzwf1q1p_.pdf を削除しました。
335/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p138.pdf

2024-12-22 01:31:43,522 - INFO - Response status: 206
Response headers:
    'Content-Length': '466879'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:30 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EF91952D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '89066f07-101e-0053-16c5-534e98000000'
    'x-ms-client-request-id': '0fda9d71-bfb9-11ef-9823-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:31:43 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpre1k8k8j.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  75%|███████▌  | 335/445 [41:10<13:12,  7.21s/it]2024-12-22 01:31:49,877 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p139.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '14187a63-bfb9-11ef-8773-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpre1k8k8j.pdf を削除しました。
336/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p139.pdf

2024-12-22 01:31:50,640 - INFO - Response status: 206
Response headers:
    'Content-Length': '569420'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:31 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EFDFAB7A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4f61968b-e01e-0081-7cc5-53f0c0000000'
    'x-ms-client-request-id': '14187a63-bfb9-11ef-8773-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:31:50 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpcnb1g4r2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  76%|███████▌  | 336/445 [41:18<13:08,  7.24s/it]2024-12-22 01:31:57,193 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p14.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1874bbb6-bfb9-11ef-9014-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpcnb1g4r2.pdf を削除しました。
337/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p14.pdf

2024-12-22 01:31:57,949 - INFO - Response status: 206
Response headers:
    'Content-Length': '498190'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:32 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F03B6E05"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '76d1869b-f01e-00f3-14c5-5381fe000000'
    'x-ms-client-request-id': '1874bbb6-bfb9-11ef-9014-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:31:57 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3u001hao.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  76%|███████▌  | 337/445 [41:25<13:05,  7.27s/it]2024-12-22 01:32:04,552 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p140.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1cd78e79-bfb9-11ef-ab26-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp3u001hao.pdf を削除しました。
338/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p140.pdf

2024-12-22 01:32:05,353 - INFO - Response status: 206
Response headers:
    'Content-Length': '611215'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F6E46E91"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f5b3c828-a01e-0063-49c5-5314b2000000'
    'x-ms-client-request-id': '1cd78e79-bfb9-11ef-ab26-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:32:04 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmph0yvstvz.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  76%|███████▌  | 338/445 [41:32<13:00,  7.29s/it]2024-12-22 01:32:11,893 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p141.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2137c3ab-bfb9-11ef-8b72-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmph0yvstvz.pdf を削除しました。
339/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p141.pdf

2024-12-22 01:32:12,633 - INFO - Response status: 206
Response headers:
    'Content-Length': '175605'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F76A6CEC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '92a169a2-801e-00de-39c5-53023e000000'
    'x-ms-client-request-id': '2137c3ab-bfb9-11ef-8b72-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:32:12 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbg5xr6vm.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  76%|███████▌  | 339/445 [41:39<12:35,  7.13s/it]2024-12-22 01:32:18,622 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p142.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '253a9fab-bfb9-11ef-81f1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbg5xr6vm.pdf を削除しました。
340/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p142.pdf

2024-12-22 01:32:19,366 - INFO - Response status: 206
Response headers:
    'Content-Length': '723381'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F68A57E0"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6ce92248-f01e-00f8-62c5-53998a000000'
    'x-ms-client-request-id': '253a9fab-bfb9-11ef-81f1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:32:19 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6fdc6vde.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  76%|███████▋  | 340/445 [41:47<12:36,  7.21s/it]2024-12-22 01:32:26,024 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p143.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '29a40a85-bfb9-11ef-b977-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6fdc6vde.pdf を削除しました。
341/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p143.pdf

2024-12-22 01:32:26,795 - INFO - Response status: 206
Response headers:
    'Content-Length': '848702'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F63C686D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '89c23216-101e-0094-44c5-533259000000'
    'x-ms-client-request-id': '29a40a85-bfb9-11ef-b977-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:32:26 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4rofkite.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  77%|███████▋  | 341/445 [41:54<12:40,  7.32s/it]2024-12-22 01:32:33,590 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p144.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2e266d76-bfb9-11ef-ab92-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4rofkite.pdf を削除しました。
342/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p144.pdf

2024-12-22 01:32:34,340 - INFO - Response status: 206
Response headers:
    'Content-Length': '705667'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F51D2075"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'efc7fc8c-901e-00ac-46c5-537300000000'
    'x-ms-client-request-id': '2e266d76-bfb9-11ef-ab92-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:32:34 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpubsa_d8u.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  77%|███████▋  | 342/445 [42:07<15:11,  8.85s/it]2024-12-22 01:32:46,017 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p145.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '358ea3d9-bfb9-11ef-84a5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpubsa_d8u.pdf を削除しました。
343/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p145.pdf

2024-12-22 01:32:46,778 - INFO - Response status: 206
Response headers:
    'Content-Length': '771765'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:38 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F41C3AB1"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f2b75326-201e-00be-27c5-53471c000000'
    'x-ms-client-request-id': '358ea3d9-bfb9-11ef-84a5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:32:46 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptp4rnpfh.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  77%|███████▋  | 343/445 [42:14<14:18,  8.42s/it]2024-12-22 01:32:53,440 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p146.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '39fb71f7-bfb9-11ef-81dc-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptp4rnpfh.pdf を削除しました。
344/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p146.pdf

2024-12-22 01:32:54,170 - INFO - Response status: 206
Response headers:
    'Content-Length': '506760'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F53B5BD7"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd3bfb472-d01e-0023-61c5-533d5c000000'
    'x-ms-client-request-id': '39fb71f7-bfb9-11ef-81dc-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:32:54 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpz6wuh3ci.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  77%|███████▋  | 344/445 [42:21<13:34,  8.06s/it]2024-12-22 01:33:00,656 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p147.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3e48798f-bfb9-11ef-83c2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpz6wuh3ci.pdf を削除しました。
345/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p147.pdf

2024-12-22 01:33:01,402 - INFO - Response status: 206
Response headers:
    'Content-Length': '897727'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F604CE1F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '05483225-901e-00a7-6ec6-536b74000000'
    'x-ms-client-request-id': '3e48798f-bfb9-11ef-83c2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:33:01 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmh2_1fds.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  78%|███████▊  | 345/445 [42:29<13:12,  7.93s/it]2024-12-22 01:33:08,270 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p148.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '42d232a4-bfb9-11ef-b69d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmh2_1fds.pdf を削除しました。
346/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p148.pdf

2024-12-22 01:33:09,045 - INFO - Response status: 206
Response headers:
    'Content-Length': '63345'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:38 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F4001FBB"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '45aed029-701e-008f-40c6-531ccb000000'
    'x-ms-client-request-id': '42d232a4-bfb9-11ef-b69d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:33:09 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2oe9oo_0.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  78%|███████▊  | 346/445 [42:35<12:23,  7.51s/it]2024-12-22 01:33:14,826 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p149.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '46ba8f26-bfb9-11ef-869a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2oe9oo_0.pdf を削除しました。
347/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p149.pdf

2024-12-22 01:33:15,557 - INFO - Response status: 206
Response headers:
    'Content-Length': '155892'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F3ADA194"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9b57bd6f-601e-0090-6bc6-53c7db000000'
    'x-ms-client-request-id': '46ba8f26-bfb9-11ef-869a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:33:15 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpoomf_br_.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  78%|███████▊  | 347/445 [42:42<11:54,  7.29s/it]2024-12-22 01:33:21,588 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p15.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4ac261fd-bfb9-11ef-880c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpoomf_br_.pdf を削除しました。
348/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p15.pdf

2024-12-22 01:33:22,329 - INFO - Response status: 206
Response headers:
    'Content-Length': '360724'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:33 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F1251550"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '700eaf27-f01e-003f-78c6-53e54b000000'
    'x-ms-client-request-id': '4ac261fd-bfb9-11ef-880c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:33:21 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpckv1bkx2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  78%|███████▊  | 348/445 [42:49<11:41,  7.23s/it]2024-12-22 01:33:28,671 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p150.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4efb345f-bfb9-11ef-bdf7-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpckv1bkx2.pdf を削除しました。
349/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p150.pdf

2024-12-22 01:33:29,447 - INFO - Response status: 206
Response headers:
    'Content-Length': '522708'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F50B5A19"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '73291d42-601e-0013-2bc6-536776000000'
    'x-ms-client-request-id': '4efb345f-bfb9-11ef-bdf7-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:33:29 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmj43ssbb.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  78%|███████▊  | 349/445 [42:56<11:32,  7.21s/it]2024-12-22 01:33:35,846 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p151.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '53421054-bfb9-11ef-b4bb-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpmj43ssbb.pdf を削除しました。
350/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p151.pdf

2024-12-22 01:33:36,744 - INFO - Response status: 206
Response headers:
    'Content-Length': '536761'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:38 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F44ADE68"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a06934c4-701e-0048-37c6-53600a000000'
    'x-ms-client-request-id': '53421054-bfb9-11ef-b4bb-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:33:36 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpzh1n4ifm.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  79%|███████▊  | 350/445 [43:04<11:30,  7.27s/it]2024-12-22 01:33:43,239 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p152.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '57aa0f2c-bfb9-11ef-936b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpzh1n4ifm.pdf を削除しました。
351/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p152.pdf

2024-12-22 01:33:44,020 - INFO - Response status: 206
Response headers:
    'Content-Length': '451481'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F5281098"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '698e3477-101e-007a-2fc6-5338da000000'
    'x-ms-client-request-id': '57aa0f2c-bfb9-11ef-936b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:33:43 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb0hj8ghm.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  79%|███████▉  | 351/445 [43:11<11:16,  7.19s/it]2024-12-22 01:33:50,256 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p153.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5bd8db2a-bfb9-11ef-819f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb0hj8ghm.pdf を削除しました。
352/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p153.pdf

2024-12-22 01:33:51,010 - INFO - Response status: 206
Response headers:
    'Content-Length': '499480'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F600663C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '896e60f1-b01e-0038-36c6-5313ce000000'
    'x-ms-client-request-id': '5bd8db2a-bfb9-11ef-819f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:33:50 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp14d5nidx.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  79%|███████▉  | 352/445 [43:18<11:04,  7.14s/it]2024-12-22 01:33:57,291 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p154.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '600a1294-bfb9-11ef-b676-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp14d5nidx.pdf を削除しました。
353/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p154.pdf

2024-12-22 01:33:58,036 - INFO - Response status: 206
Response headers:
    'Content-Length': '63184'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F70FE18D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4f698500-e01e-002b-32c6-53262f000000'
    'x-ms-client-request-id': '600a1294-bfb9-11ef-b676-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:33:58 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpd_dvzqp5.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  79%|███████▉  | 353/445 [43:24<10:41,  6.97s/it]2024-12-22 01:34:03,846 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p16.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '63f26860-bfb9-11ef-aad0-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpd_dvzqp5.pdf を削除しました。
354/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p16.pdf

2024-12-22 01:34:04,607 - INFO - Response status: 206
Response headers:
    'Content-Length': '496183'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:34 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F1BC6558"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8156ca66-b01e-005e-09c6-53a194000000'
    'x-ms-client-request-id': '63f26860-bfb9-11ef-aad0-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:34:04 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptma5ndcn.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  80%|███████▉  | 354/445 [43:31<10:35,  6.98s/it]2024-12-22 01:34:10,859 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p17.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '68208e56-bfb9-11ef-89be-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptma5ndcn.pdf を削除しました。
355/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p17.pdf

2024-12-22 01:34:11,709 - INFO - Response status: 206
Response headers:
    'Content-Length': '358811'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:34 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F164E3DF"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '39525fd8-d01e-00cd-34c6-5337df000000'
    'x-ms-client-request-id': '68208e56-bfb9-11ef-89be-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:34:11 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdehk1kj1.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  80%|███████▉  | 355/445 [43:39<10:34,  7.05s/it]2024-12-22 01:34:18,056 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p18.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6c6abd4c-bfb9-11ef-b7ae-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpdehk1kj1.pdf を削除しました。
356/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p18.pdf

2024-12-22 01:34:18,803 - INFO - Response status: 206
Response headers:
    'Content-Length': '498069'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F88D3376"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f7ebb83b-901e-00e8-61c6-53af6c000000'
    'x-ms-client-request-id': '6c6abd4c-bfb9-11ef-b7ae-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:34:18 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpq2su4qk0.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  80%|████████  | 356/445 [43:46<10:28,  7.06s/it]2024-12-22 01:34:25,150 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p19.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '70a52d71-bfb9-11ef-91a9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpq2su4qk0.pdf を削除しました。
357/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p19.pdf

2024-12-22 01:34:25,921 - INFO - Response status: 206
Response headers:
    'Content-Length': '360779'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F91B65F1"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '10381a3e-301e-0022-3bc6-533ca1000000'
    'x-ms-client-request-id': '70a52d71-bfb9-11ef-91a9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:34:25 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpopg4v_o2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  80%|████████  | 357/445 [43:53<10:23,  7.08s/it]2024-12-22 01:34:32,288 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p2.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '74e6441a-bfb9-11ef-930b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpopg4v_o2.pdf を削除しました。
358/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p2.pdf

2024-12-22 01:34:33,091 - INFO - Response status: 206
Response headers:
    'Content-Length': '801760'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F95D071E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '5053df5b-501e-0054-0cc6-53b81d000000'
    'x-ms-client-request-id': '74e6441a-bfb9-11ef-930b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:34:32 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgguxlsdk.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  80%|████████  | 358/445 [44:00<10:28,  7.22s/it]2024-12-22 01:34:39,823 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p20.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '79640ea8-bfb9-11ef-8525-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgguxlsdk.pdf を削除しました。
359/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p20.pdf

2024-12-22 01:34:40,609 - INFO - Response status: 206
Response headers:
    'Content-Length': '496105'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F9EC22FE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b09936f0-601e-00d4-1bc6-531bb7000000'
    'x-ms-client-request-id': '79640ea8-bfb9-11ef-8525-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:34:40 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxu89jqu1.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  81%|████████  | 359/445 [44:08<10:23,  7.24s/it]2024-12-22 01:34:47,126 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p21.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7dbe6c8b-bfb9-11ef-b87b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpxu89jqu1.pdf を削除しました。
360/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p21.pdf

2024-12-22 01:34:47,896 - INFO - Response status: 206
Response headers:
    'Content-Length': '359261'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F9A5A557"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '335c02d6-401e-00c8-6dc6-53c3a0000000'
    'x-ms-client-request-id': '7dbe6c8b-bfb9-11ef-b87b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:34:47 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpso_7zblo.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  81%|████████  | 360/445 [44:15<10:12,  7.20s/it]2024-12-22 01:34:54,235 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p22.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '81fb4ac1-bfb9-11ef-8a1d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpso_7zblo.pdf を削除しました。
361/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p22.pdf

2024-12-22 01:34:55,024 - INFO - Response status: 206
Response headers:
    'Content-Length': '497842'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64FA30327A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9d574498-401e-002d-71c6-53d157000000'
    'x-ms-client-request-id': '81fb4ac1-bfb9-11ef-8a1d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:34:54 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9t7oo34v.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  81%|████████  | 361/445 [44:22<10:09,  7.25s/it]2024-12-22 01:35:01,600 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p23.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '865f17da-bfb9-11ef-aa16-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9t7oo34v.pdf を削除しました。
362/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p23.pdf

2024-12-22 01:35:02,387 - INFO - Response status: 206
Response headers:
    'Content-Length': '361527'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64FAAC77CC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '36913f6f-901e-0102-4dc6-531638000000'
    'x-ms-client-request-id': '865f17da-bfb9-11ef-aa16-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:35:02 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbiji2ue_.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  81%|████████▏ | 362/445 [44:29<10:01,  7.24s/it]2024-12-22 01:35:08,825 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p24.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8aad877f-bfb9-11ef-9507-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbiji2ue_.pdf を削除しました。
363/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p24.pdf

2024-12-22 01:35:09,617 - INFO - Response status: 206
Response headers:
    'Content-Length': '494722'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F8D6BAFE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ceb3f89d-901e-002f-2bc6-53d3ad000000'
    'x-ms-client-request-id': '8aad877f-bfb9-11ef-9507-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:35:09 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpurws9qnf.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  82%|████████▏ | 363/445 [44:37<09:53,  7.24s/it]2024-12-22 01:35:16,043 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p25.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8efab140-bfb9-11ef-961f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpurws9qnf.pdf を削除しました。
364/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p25.pdf

2024-12-22 01:35:16,847 - INFO - Response status: 206
Response headers:
    'Content-Length': '358227'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F8F040C3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '7532f8f5-701e-000c-51c6-53bc66000000'
    'x-ms-client-request-id': '8efab140-bfb9-11ef-961f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:35:16 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfqznbvux.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  82%|████████▏ | 364/445 [44:44<09:42,  7.20s/it]2024-12-22 01:35:23,147 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p26.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9336e609-bfb9-11ef-b4a9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfqznbvux.pdf を削除しました。
365/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p26.pdf

2024-12-22 01:35:23,872 - INFO - Response status: 206
Response headers:
    'Content-Length': '496041'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F7F9AFB6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a79f21de-601e-009b-50c6-53dfaf000000'
    'x-ms-client-request-id': '9336e609-bfb9-11ef-b4a9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:35:23 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpum5eyyps.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  82%|████████▏ | 365/445 [44:51<09:32,  7.16s/it]2024-12-22 01:35:30,207 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p27.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '976c10c1-bfb9-11ef-99b1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpum5eyyps.pdf を削除しました。
366/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p27.pdf

2024-12-22 01:35:30,950 - INFO - Response status: 206
Response headers:
    'Content-Length': '358837'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F7DF4094"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '923059b1-401e-00ea-13c6-53ad96000000'
    'x-ms-client-request-id': '976c10c1-bfb9-11ef-99b1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:35:30 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmps4do3tfj.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  82%|████████▏ | 366/445 [44:58<09:20,  7.10s/it]2024-12-22 01:35:37,178 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p28.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9b93d189-bfb9-11ef-8599-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmps4do3tfj.pdf を削除しました。
367/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p28.pdf

2024-12-22 01:35:37,931 - INFO - Response status: 206
Response headers:
    'Content-Length': '308291'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:32 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F053BCB4"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4825b2da-d01e-00e4-7cc6-53419d000000'
    'x-ms-client-request-id': '9b93d189-bfb9-11ef-8599-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:35:38 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb21vgzor.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  82%|████████▏ | 367/445 [45:05<09:10,  7.05s/it]2024-12-22 01:35:44,125 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p29.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9fb7e13e-bfb9-11ef-8b4b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb21vgzor.pdf を削除しました。
368/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p29.pdf

2024-12-22 01:35:44,887 - INFO - Response status: 206
Response headers:
    'Content-Length': '224000'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:33 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F0EFE942"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e6216c5c-201e-0072-4ec6-5323a9000000'
    'x-ms-client-request-id': '9fb7e13e-bfb9-11ef-8b4b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:35:45 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpz9wt2iao.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  83%|████████▎ | 368/445 [45:11<08:56,  6.97s/it]2024-12-22 01:35:50,895 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p3.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a3c0d18a-bfb9-11ef-afc5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpz9wt2iao.pdf を削除しました。
369/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p3.pdf

2024-12-22 01:35:51,628 - INFO - Response status: 206
Response headers:
    'Content-Length': '837185'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64FA2A6C94"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '43689b11-001e-00a9-0bc6-53877f000000'
    'x-ms-client-request-id': 'a3c0d18a-bfb9-11ef-afc5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:35:51 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6h56b_t4.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  83%|████████▎ | 369/445 [45:19<08:54,  7.04s/it]2024-12-22 01:35:58,089 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p30.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a80a85f6-bfb9-11ef-bda8-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6h56b_t4.pdf を削除しました。
370/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p30.pdf

2024-12-22 01:35:58,883 - INFO - Response status: 206
Response headers:
    'Content-Length': '309356'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F89BEFF0"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd51f4a7e-001e-0047-12c6-538dfc000000'
    'x-ms-client-request-id': 'a80a85f6-bfb9-11ef-bda8-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:35:58 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpompl1n64.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  83%|████████▎ | 370/445 [45:26<08:47,  7.04s/it]2024-12-22 01:36:05,137 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p31.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ac3dfb21-bfb9-11ef-89f6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpompl1n64.pdf を削除しました。
371/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p31.pdf

2024-12-22 01:36:05,884 - INFO - Response status: 206
Response headers:
    'Content-Length': '223638'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:46 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F8EDF95E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '39d236bb-501e-0098-71c6-53dca8000000'
    'x-ms-client-request-id': 'ac3dfb21-bfb9-11ef-89f6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:36:05 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpo3npy1nw.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  83%|████████▎ | 371/445 [45:32<08:34,  6.95s/it]2024-12-22 01:36:11,893 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p32.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b044dbb8-bfb9-11ef-b819-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpo3npy1nw.pdf を削除しました。
372/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p32.pdf

2024-12-22 01:36:12,620 - INFO - Response status: 206
Response headers:
    'Content-Length': '309849'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F7E726F1"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b1c4dd6d-001e-00e6-5bc6-534367000000'
    'x-ms-client-request-id': 'b044dbb8-bfb9-11ef-b819-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:36:12 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpavxdo0yr.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  84%|████████▎ | 372/445 [45:39<08:27,  6.95s/it]2024-12-22 01:36:18,831 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p33.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b467816e-bfb9-11ef-81c8-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpavxdo0yr.pdf を削除しました。
373/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p33.pdf

2024-12-22 01:36:19,594 - INFO - Response status: 206
Response headers:
    'Content-Length': '226160'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F7E0030B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e86f478a-601e-0057-1dc6-53bb1a000000'
    'x-ms-client-request-id': 'b467816e-bfb9-11ef-81c8-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:36:19 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6l7yki3x.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  84%|████████▍ | 373/445 [45:46<08:16,  6.89s/it]2024-12-22 01:36:25,590 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p34.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b86eefe9-bfb9-11ef-81f6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp6l7yki3x.pdf を削除しました。
374/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p34.pdf

2024-12-22 01:36:26,312 - INFO - Response status: 206
Response headers:
    'Content-Length': '207321'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64FA07C94B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '30d5f0aa-d01e-0082-46c6-53f3c7000000'
    'x-ms-client-request-id': 'b86eefe9-bfb9-11ef-81f6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:36:25 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbaenemeb.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  84%|████████▍ | 374/445 [45:53<08:05,  6.84s/it]2024-12-22 01:36:32,313 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p35.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'bc70bade-bfb9-11ef-970e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbaenemeb.pdf を削除しました。
375/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p35.pdf

2024-12-22 01:36:33,057 - INFO - Response status: 206
Response headers:
    'Content-Length': '306861'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F9578F16"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '3083622e-c01e-00fb-23c6-539a8d000000'
    'x-ms-client-request-id': 'bc70bade-bfb9-11ef-970e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:36:32 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpm4lwdg7v.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  84%|████████▍ | 375/445 [46:00<08:02,  6.89s/it]2024-12-22 01:36:39,319 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p36.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c09dd8a1-bfb9-11ef-8efe-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpm4lwdg7v.pdf を削除しました。
376/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p36.pdf

2024-12-22 01:36:40,056 - INFO - Response status: 206
Response headers:
    'Content-Length': '479142'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:48 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64FA474A01"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '306e7527-b01e-00b0-11c6-53ab17000000'
    'x-ms-client-request-id': 'c09dd8a1-bfb9-11ef-8efe-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:36:39 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjpgpg1ui.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  84%|████████▍ | 376/445 [46:07<08:02,  6.99s/it]2024-12-22 01:36:46,532 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p37.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c4ea5f3b-bfb9-11ef-881f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjpgpg1ui.pdf を削除しました。
377/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p37.pdf

2024-12-22 01:36:47,272 - INFO - Response status: 206
Response headers:
    'Content-Length': '640996'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:49 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64FA914627"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e9dbb40e-701e-00ad-07c6-5372fd000000'
    'x-ms-client-request-id': 'c4ea5f3b-bfb9-11ef-881f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:36:47 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_4nta616.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  85%|████████▍ | 377/445 [46:14<08:00,  7.07s/it]2024-12-22 01:36:53,778 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p38.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c93bed94-bfb9-11ef-91a9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_4nta616.pdf を削除しました。
378/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p38.pdf

2024-12-22 01:36:54,535 - INFO - Response status: 206
Response headers:
    'Content-Length': '505180'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:31 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EFF9CCD6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '442e67c0-201e-005b-22c6-5355eb000000'
    'x-ms-client-request-id': 'c93bed94-bfb9-11ef-91a9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:36:54 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpc3do2hhu.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  85%|████████▍ | 378/445 [46:27<09:39,  8.65s/it]2024-12-22 01:37:06,138 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p39.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd09a16a1-bfb9-11ef-a4a2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpc3do2hhu.pdf を削除しました。
379/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p39.pdf

2024-12-22 01:37:06,865 - INFO - Response status: 206
Response headers:
    'Content-Length': '476543'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:30 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64EF59D3FB"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8e4cfa70-601e-00b2-6dc6-53a9ed000000'
    'x-ms-client-request-id': 'd09a16a1-bfb9-11ef-a4a2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:37:06 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplxn870mk.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  85%|████████▌ | 379/445 [46:34<08:59,  8.17s/it]2024-12-22 01:37:13,181 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p4.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd4cca906-bfb9-11ef-af23-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplxn870mk.pdf を削除しました。
380/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p4.pdf

2024-12-22 01:37:13,925 - INFO - Response status: 206
Response headers:
    'Content-Length': '544773'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F79D03D3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6fd3205f-f01e-007b-19c6-533927000000'
    'x-ms-client-request-id': 'd4cca906-bfb9-11ef-af23-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:37:13 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphl6w56mh.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  85%|████████▌ | 380/445 [46:41<08:30,  7.86s/it]2024-12-22 01:37:20,320 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p40.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd90e0ad9-bfb9-11ef-8933-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphl6w56mh.pdf を削除しました。
381/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p40.pdf

2024-12-22 01:37:21,086 - INFO - Response status: 206
Response headers:
    'Content-Length': '527428'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F792616B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '0549fcc1-901e-00a7-55c6-536b74000000'
    'x-ms-client-request-id': 'd90e0ad9-bfb9-11ef-8933-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:37:21 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0h8ildv8.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  86%|████████▌ | 381/445 [46:48<08:11,  7.67s/it]2024-12-22 01:37:27,554 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p41.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'dd5de71b-bfb9-11ef-a5c8-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp0h8ildv8.pdf を削除しました。
382/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p41.pdf

2024-12-22 01:37:28,278 - INFO - Response status: 206
Response headers:
    'Content-Length': '642038'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F6D5D8F3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9a4e3fe3-c01e-001e-3ac6-53887a000000'
    'x-ms-client-request-id': 'dd5de71b-bfb9-11ef-a5c8-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:37:28 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp21triqbn.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  86%|████████▌ | 382/445 [46:55<07:56,  7.56s/it]2024-12-22 01:37:34,857 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p42.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e1b82905-bfb9-11ef-8bc1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp21triqbn.pdf を削除しました。
383/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p42.pdf

2024-12-22 01:37:35,598 - INFO - Response status: 206
Response headers:
    'Content-Length': '416862'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F60F499F"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e363dacd-301e-00aa-05c6-538478000000'
    'x-ms-client-request-id': 'e1b82905-bfb9-11ef-8bc1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:37:35 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpm7jleq6f.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  86%|████████▌ | 383/445 [47:02<07:39,  7.41s/it]2024-12-22 01:37:41,902 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p43.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e5eb3810-bfb9-11ef-9ed2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpm7jleq6f.pdf を削除しました。
384/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p43.pdf

2024-12-22 01:37:42,625 - INFO - Response status: 206
Response headers:
    'Content-Length': '468039'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F6B41F01"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'df1a2e45-a01e-0005-1cc6-53a6e8000000'
    'x-ms-client-request-id': 'e5eb3810-bfb9-11ef-9ed2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:37:42 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpg4h9e3x8.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  86%|████████▋ | 384/445 [47:09<07:23,  7.26s/it]2024-12-22 01:37:48,835 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p44.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ea0d22b1-bfb9-11ef-9656-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpg4h9e3x8.pdf を削除しました。
385/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p44.pdf

2024-12-22 01:37:49,560 - INFO - Response status: 206
Response headers:
    'Content-Length': '605714'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F46DA89C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '42b4c0ca-a01e-0068-67c6-530cc6000000'
    'x-ms-client-request-id': 'ea0d22b1-bfb9-11ef-9656-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:37:49 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpukf6l83g.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  87%|████████▋ | 385/445 [47:17<07:15,  7.26s/it]2024-12-22 01:37:56,090 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p45.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ee600980-bfb9-11ef-b800-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpukf6l83g.pdf を削除しました。
386/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p45.pdf

2024-12-22 01:37:56,839 - INFO - Response status: 206
Response headers:
    'Content-Length': '529551'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F4EEA392"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4d1378b6-101e-001c-16c6-538a80000000'
    'x-ms-client-request-id': 'ee600980-bfb9-11ef-b800-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:37:56 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpoc75iurq.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  87%|████████▋ | 386/445 [47:24<07:05,  7.21s/it]2024-12-22 01:38:03,170 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p46.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f29870c6-bfb9-11ef-9f33-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpoc75iurq.pdf を削除しました。
387/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p46.pdf

2024-12-22 01:38:03,890 - INFO - Response status: 206
Response headers:
    'Content-Length': '503675'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F5C7E28E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '569146bb-101e-00db-4ac6-53f641000000'
    'x-ms-client-request-id': 'f29870c6-bfb9-11ef-9f33-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:38:04 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgamx_36e.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  87%|████████▋ | 387/445 [47:31<06:57,  7.20s/it]2024-12-22 01:38:10,369 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p47.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f6e2c4f6-bfb9-11ef-8997-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgamx_36e.pdf を削除しました。
388/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p47.pdf

2024-12-22 01:38:11,121 - INFO - Response status: 206
Response headers:
    'Content-Length': '479615'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F574A1F9"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd94061e4-301e-00c7-39c6-532e56000000'
    'x-ms-client-request-id': 'f6e2c4f6-bfb9-11ef-8997-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:38:11 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2uzoy6o_.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  87%|████████▋ | 388/445 [47:38<06:51,  7.22s/it]2024-12-22 01:38:17,617 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p48.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'fb34ec17-bfb9-11ef-8f37-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2uzoy6o_.pdf を削除しました。
389/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p48.pdf

2024-12-22 01:38:18,343 - INFO - Response status: 206
Response headers:
    'Content-Length': '636833'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:38 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F3CD3B07"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cad6eecb-d01e-0045-6cc6-538f06000000'
    'x-ms-client-request-id': 'fb34ec17-bfb9-11ef-8f37-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:38:18 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpv7cj148b.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  87%|████████▋ | 389/445 [47:45<06:44,  7.23s/it]2024-12-22 01:38:24,868 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p49.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ff871f43-bfb9-11ef-9768-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpv7cj148b.pdf を削除しました。
390/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p49.pdf

2024-12-22 01:38:25,629 - INFO - Response status: 206
Response headers:
    'Content-Length': '411452'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:38 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F3F1B105"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'c8ed2c75-301e-0029-67c6-5324d5000000'
    'x-ms-client-request-id': 'ff871f43-bfb9-11ef-9768-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:38:25 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpcfe7iqi2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  88%|████████▊ | 390/445 [47:58<07:58,  8.71s/it]2024-12-22 01:38:37,026 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p5.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '06c6655d-bfba-11ef-8a3d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpcfe7iqi2.pdf を削除しました。
391/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p5.pdf

2024-12-22 01:38:37,781 - INFO - Response status: 206
Response headers:
    'Content-Length': '460331'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F83EF64E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e25b394f-301e-00cc-14c6-533622000000'
    'x-ms-client-request-id': '06c6655d-bfba-11ef-8a3d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:38:37 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpymy5b7z1.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  88%|████████▊ | 391/445 [48:05<07:22,  8.20s/it]2024-12-22 01:38:44,041 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p50.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0af4e53a-bfba-11ef-b3fc-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpymy5b7z1.pdf を削除しました。
392/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p50.pdf

2024-12-22 01:38:44,775 - INFO - Response status: 206
Response headers:
    'Content-Length': '521047'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F47AB94A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f7edbef9-901e-00e8-2dc6-53af6c000000'
    'x-ms-client-request-id': '0af4e53a-bfba-11ef-b3fc-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:38:44 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptkfpv28u.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  88%|████████▊ | 392/445 [48:12<06:57,  7.88s/it]2024-12-22 01:38:51,184 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p51.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0f36c510-bfba-11ef-b56d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmptkfpv28u.pdf を削除しました。
393/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p51.pdf

2024-12-22 01:38:51,926 - INFO - Response status: 206
Response headers:
    'Content-Length': '471357'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F4DB584D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '97ea0794-601e-007e-24c6-53cd58000000'
    'x-ms-client-request-id': '0f36c510-bfba-11ef-b56d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:38:51 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgyl4805t.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  88%|████████▊ | 393/445 [48:24<07:56,  9.17s/it]2024-12-22 01:39:03,364 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p52.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '16794dfd-bfba-11ef-82cd-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpgyl4805t.pdf を削除しました。
394/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p52.pdf

2024-12-22 01:39:04,145 - INFO - Response status: 206
Response headers:
    'Content-Length': '622646'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F5E72E42"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '15f74d52-f01e-0070-4bc6-532153000000'
    'x-ms-client-request-id': '16794dfd-bfba-11ef-82cd-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:39:04 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsm477iys.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  89%|████████▊ | 394/445 [48:31<07:17,  8.58s/it]2024-12-22 01:39:10,553 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p53.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1ac24927-bfba-11ef-b9e9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsm477iys.pdf を削除しました。
395/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p53.pdf

2024-12-22 01:39:11,342 - INFO - Response status: 206
Response headers:
    'Content-Length': '502674'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F55CEEE0"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a0df143a-e01e-00ce-1bc6-5334d8000000'
    'x-ms-client-request-id': '1ac24927-bfba-11ef-b9e9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:39:11 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpq0b0134d.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  89%|████████▉ | 395/445 [48:38<06:45,  8.12s/it]2024-12-22 01:39:17,601 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p54.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1ef5b188-bfba-11ef-9813-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpq0b0134d.pdf を削除しました。
396/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p54.pdf

2024-12-22 01:39:18,343 - INFO - Response status: 206
Response headers:
    'Content-Length': '508473'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F78FA563"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6db1f04b-201e-00d8-7fc6-53f546000000'
    'x-ms-client-request-id': '1ef5b188-bfba-11ef-9813-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:39:18 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2v8kz3ru.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  89%|████████▉ | 396/445 [48:50<07:37,  9.33s/it]2024-12-22 01:39:29,753 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p55.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2633f30b-bfba-11ef-95e5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp2v8kz3ru.pdf を削除しました。
397/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p55.pdf

2024-12-22 01:39:30,533 - INFO - Response status: 206
Response headers:
    'Content-Length': '686973'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F6D7D28C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'da85fbaa-c01e-0078-3cc6-533a20000000'
    'x-ms-client-request-id': '2633f30b-bfba-11ef-95e5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:39:30 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9koi3082.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  89%|████████▉ | 397/445 [48:58<06:57,  8.70s/it]2024-12-22 01:39:36,981 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p56.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2a82daf7-bfba-11ef-88c8-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp9koi3082.pdf を削除しました。
398/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p56.pdf

2024-12-22 01:39:37,724 - INFO - Response status: 206
Response headers:
    'Content-Length': '564426'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F602FB6A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cda477d3-301e-006d-65c6-53f8b9000000'
    'x-ms-client-request-id': '2a82daf7-bfba-11ef-88c8-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:39:37 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpp2y2luzp.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  89%|████████▉ | 398/445 [49:05<06:27,  8.24s/it]2024-12-22 01:39:44,153 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p57.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2ec92b53-bfba-11ef-91d6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpp2y2luzp.pdf を削除しました。
399/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p57.pdf

2024-12-22 01:39:44,867 - INFO - Response status: 206
Response headers:
    'Content-Length': '497792'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F6CC1FEE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '966d0293-201e-0036-70c6-53ffc5000000'
    'x-ms-client-request-id': '2ec92b53-bfba-11ef-91d6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:39:44 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpn64i9je6.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  90%|████████▉ | 399/445 [49:12<06:01,  7.87s/it]2024-12-22 01:39:51,154 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p58.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '32f575a2-bfba-11ef-bf1e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpn64i9je6.pdf を削除しました。
400/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p58.pdf

2024-12-22 01:39:51,884 - INFO - Response status: 206
Response headers:
    'Content-Length': '487419'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:36 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F2A302E4"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '442fa9f7-201e-005b-31c6-5355eb000000'
    'x-ms-client-request-id': '32f575a2-bfba-11ef-bf1e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:39:51 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyaotix2i.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  90%|████████▉ | 400/445 [49:19<05:42,  7.62s/it]2024-12-22 01:39:58,179 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p59.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '37253029-bfba-11ef-8e7b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpyaotix2i.pdf を削除しました。
401/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p59.pdf

2024-12-22 01:39:58,918 - INFO - Response status: 206
Response headers:
    'Content-Length': '658134'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:35 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F2553A55"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a06bc49d-701e-0048-6dc6-53600a000000'
    'x-ms-client-request-id': '37253029-bfba-11ef-8e7b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:39:58 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpygite9ll.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  90%|█████████ | 401/445 [49:26<05:31,  7.53s/it]2024-12-22 01:40:05,499 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p6.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3b82456b-bfba-11ef-9878-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpygite9ll.pdf を削除しました。
402/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p6.pdf

2024-12-22 01:40:06,251 - INFO - Response status: 206
Response headers:
    'Content-Length': '461028'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:47 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F951F00B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8f9b5822-701e-006a-1cc6-530e3c000000'
    'x-ms-client-request-id': '3b82456b-bfba-11ef-9878-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:40:05 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpiju_03f1.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  90%|█████████ | 402/445 [49:33<05:16,  7.36s/it]2024-12-22 01:40:12,456 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p60.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3fa7ec8b-bfba-11ef-835e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpiju_03f1.pdf を削除しました。
403/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p60.pdf

2024-12-22 01:40:13,232 - INFO - Response status: 206
Response headers:
    'Content-Length': '444941'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F3A67DB2"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e62c2325-801e-0091-50c7-53c626000000'
    'x-ms-client-request-id': '3fa7ec8b-bfba-11ef-835e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:40:12 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbapf3zkb.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  91%|█████████ | 403/445 [49:40<05:04,  7.25s/it]2024-12-22 01:40:19,463 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p61.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '43d502fe-bfba-11ef-aea1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbapf3zkb.pdf を削除しました。
404/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p61.pdf

2024-12-22 01:40:20,218 - INFO - Response status: 206
Response headers:
    'Content-Length': '521359'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:38 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F413441A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd6e4a051-401e-004b-42c7-53630d000000'
    'x-ms-client-request-id': '43d502fe-bfba-11ef-aea1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:40:19 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwhu1d31v.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  91%|█████████ | 404/445 [49:47<04:57,  7.25s/it]2024-12-22 01:40:26,711 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p62.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '482707f6-bfba-11ef-a11a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpwhu1d31v.pdf を削除しました。
405/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p62.pdf

2024-12-22 01:40:27,457 - INFO - Response status: 206
Response headers:
    'Content-Length': '531723'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F35FD915"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a0fa2649-901e-0085-26c7-530542000000'
    'x-ms-client-request-id': '482707f6-bfba-11ef-a11a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:40:27 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpey5h75js.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  91%|█████████ | 405/445 [49:54<04:48,  7.21s/it]2024-12-22 01:40:33,827 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p63.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4c64cb81-bfba-11ef-8f29-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpey5h75js.pdf を削除しました。
406/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p63.pdf

2024-12-22 01:40:34,564 - INFO - Response status: 206
Response headers:
    'Content-Length': '533515'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F3440BEF"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '7402bd88-b01e-00d6-35c7-53194d000000'
    'x-ms-client-request-id': '4c64cb81-bfba-11ef-8f29-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:40:34 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4r1v6m2w.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  91%|█████████ | 406/445 [50:01<04:38,  7.14s/it]2024-12-22 01:40:40,810 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p64.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '508e4f4f-bfba-11ef-a30f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4r1v6m2w.pdf を削除しました。
407/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p64.pdf

2024-12-22 01:40:41,537 - INFO - Response status: 206
Response headers:
    'Content-Length': '522245'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:35 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F261888C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '822619d9-a01e-002c-41c7-53d0aa000000'
    'x-ms-client-request-id': '508e4f4f-bfba-11ef-a30f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:40:41 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmprom5ccio.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  91%|█████████▏| 407/445 [50:08<04:30,  7.12s/it]2024-12-22 01:40:47,868 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p65.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '54c36628-bfba-11ef-95c0-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmprom5ccio.pdf を削除しました。
408/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p65.pdf

2024-12-22 01:40:48,597 - INFO - Response status: 206
Response headers:
    'Content-Length': '517762'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:35 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F219ACD2"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f2ba7dff-201e-00be-69c7-53471c000000'
    'x-ms-client-request-id': '54c36628-bfba-11ef-95c0-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:40:48 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvgrds6m9.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  92%|█████████▏| 408/445 [50:15<04:21,  7.08s/it]2024-12-22 01:40:54,850 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p66.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '58ecbb56-bfba-11ef-bfed-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpvgrds6m9.pdf を削除しました。
409/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p66.pdf

2024-12-22 01:40:55,577 - INFO - Response status: 206
Response headers:
    'Content-Length': '607184'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:36 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F2BF9275"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e623c605-201e-0072-79c7-5323a9000000'
    'x-ms-client-request-id': '58ecbb56-bfba-11ef-bfed-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:40:55 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpuem106xc.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  92%|█████████▏| 409/445 [50:23<04:16,  7.13s/it]2024-12-22 01:41:02,092 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p67.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5d3dc288-bfba-11ef-aab6-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpuem106xc.pdf を削除しました。
410/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p67.pdf

2024-12-22 01:41:02,850 - INFO - Response status: 206
Response headers:
    'Content-Length': '529171'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:36 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F30B1394"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f40a4c1a-a01e-004a-79c7-5362f0000000'
    'x-ms-client-request-id': '5d3dc288-bfba-11ef-aab6-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:41:02 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5dpn84pp.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  92%|█████████▏| 410/445 [50:30<04:10,  7.14s/it]2024-12-22 01:41:09,275 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p68.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6185b74a-bfba-11ef-bef8-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5dpn84pp.pdf を削除しました。
411/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p68.pdf

2024-12-22 01:41:10,035 - INFO - Response status: 206
Response headers:
    'Content-Length': '455545'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:44 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F75C251D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6ba98c8f-e01e-008a-60c7-53e8b4000000'
    'x-ms-client-request-id': '6185b74a-bfba-11ef-bef8-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:41:09 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpix_v5kfb.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  92%|█████████▏| 411/445 [50:37<04:02,  7.13s/it]2024-12-22 01:41:16,365 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p69.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '65bf96f5-bfba-11ef-9a4d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpix_v5kfb.pdf を削除しました。
412/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p69.pdf

2024-12-22 01:41:17,115 - INFO - Response status: 206
Response headers:
    'Content-Length': '135027'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F6F241AE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9d59e8de-401e-002d-30c7-53d157000000'
    'x-ms-client-request-id': '65bf96f5-bfba-11ef-9a4d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:41:16 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpa8n1ek3m.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  93%|█████████▎| 412/445 [50:44<03:51,  7.02s/it]2024-12-22 01:41:23,145 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p7.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '69ca2a8f-bfba-11ef-beae-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpa8n1ek3m.pdf を削除しました。
413/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p7.pdf

2024-12-22 01:41:23,945 - INFO - Response status: 206
Response headers:
    'Content-Length': '460728'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:45 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F87925B8"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '732c5e0b-601e-0013-70c7-536776000000'
    'x-ms-client-request-id': '69ca2a8f-bfba-11ef-beae-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:41:23 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphgjeplvo.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  93%|█████████▎| 413/445 [50:51<03:45,  7.04s/it]2024-12-22 01:41:30,211 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p70.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6e006104-bfba-11ef-ad03-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphgjeplvo.pdf を削除しました。
414/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p70.pdf

2024-12-22 01:41:30,946 - INFO - Response status: 206
Response headers:
    'Content-Length': '510672'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:35 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F22CD12E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '355dd2f5-d01e-006c-2bc7-53f944000000'
    'x-ms-client-request-id': '6e006104-bfba-11ef-ad03-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:41:30 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsqnt84xd.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  93%|█████████▎| 414/445 [50:58<03:38,  7.05s/it]2024-12-22 01:41:37,301 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p71.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '723a358d-bfba-11ef-bb4e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpsqnt84xd.pdf を削除しました。
415/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p71.pdf

2024-12-22 01:41:38,068 - INFO - Response status: 206
Response headers:
    'Content-Length': '537439'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:35 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F22AFE6C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '03d8400a-801e-0012-47c7-53668b000000'
    'x-ms-client-request-id': '723a358d-bfba-11ef-bb4e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:41:37 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjeabpp9d.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  93%|█████████▎| 415/445 [51:05<03:33,  7.10s/it]2024-12-22 01:41:44,520 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p72.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7687bdbf-bfba-11ef-bd19-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjeabpp9d.pdf を削除しました。
416/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p72.pdf

2024-12-22 01:41:45,284 - INFO - Response status: 206
Response headers:
    'Content-Length': '592608'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:36 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F2ADA540"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ebbffe11-001e-00c4-68c7-532d51000000'
    'x-ms-client-request-id': '7687bdbf-bfba-11ef-bd19-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:41:44 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5zavg2o4.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  93%|█████████▎| 416/445 [51:12<03:26,  7.12s/it]2024-12-22 01:41:51,678 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p73.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7acbf2e0-bfba-11ef-8701-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp5zavg2o4.pdf を削除しました。
417/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p73.pdf

2024-12-22 01:41:52,397 - INFO - Response status: 206
Response headers:
    'Content-Length': '679029'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:36 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F316C640"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '435c7274-301e-004f-49c7-53968f000000'
    'x-ms-client-request-id': '7acbf2e0-bfba-11ef-8701-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:41:52 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp73y9jg7w.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  94%|█████████▎| 417/445 [51:19<03:19,  7.14s/it]2024-12-22 01:41:58,854 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p74.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '7f12e75a-bfba-11ef-85bf-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp73y9jg7w.pdf を削除しました。
418/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p74.pdf

2024-12-22 01:41:59,614 - INFO - Response status: 206
Response headers:
    'Content-Length': '419228'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F3AE1645"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '990c2e38-c01e-0037-14c7-53fe38000000'
    'x-ms-client-request-id': '7f12e75a-bfba-11ef-85bf-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:41:59 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpv3jjgwsg.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  94%|█████████▍| 418/445 [51:26<03:11,  7.11s/it]2024-12-22 01:42:05,894 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p75.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '83451469-bfba-11ef-868d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpv3jjgwsg.pdf を削除しました。
419/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p75.pdf

2024-12-22 01:42:06,651 - INFO - Response status: 206
Response headers:
    'Content-Length': '640849'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:38 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F4125ABF"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '36f5a654-001e-0080-2fc7-53f13d000000'
    'x-ms-client-request-id': '83451469-bfba-11ef-868d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:42:06 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpv2wda9xr.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  94%|█████████▍| 419/445 [51:34<03:05,  7.15s/it]2024-12-22 01:42:13,147 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p76.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8797b50c-bfba-11ef-99b2-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpv2wda9xr.pdf を削除しました。
420/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p76.pdf

2024-12-22 01:42:13,969 - INFO - Response status: 206
Response headers:
    'Content-Length': '610337'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F39C2912"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e2a7073c-601e-00f6-67c7-537581000000'
    'x-ms-client-request-id': '8797b50c-bfba-11ef-99b2-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:42:14 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpapunbb4z.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  94%|█████████▍| 420/445 [51:41<03:00,  7.20s/it]2024-12-22 01:42:20,472 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p77.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8bf5a180-bfba-11ef-818e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpapunbb4z.pdf を削除しました。
421/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p77.pdf

2024-12-22 01:42:21,309 - INFO - Response status: 206
Response headers:
    'Content-Length': '563290'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F34176CC"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd5249054-001e-0047-6dc7-538dfc000000'
    'x-ms-client-request-id': '8bf5a180-bfba-11ef-818e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:42:20 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpl2kpmepv.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  95%|█████████▍| 421/445 [51:48<02:54,  7.26s/it]2024-12-22 01:42:27,868 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p78.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '905e0f5f-bfba-11ef-a52e-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpl2kpmepv.pdf を削除しました。
422/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p78.pdf

2024-12-22 01:42:28,638 - INFO - Response status: 206
Response headers:
    'Content-Length': '597549'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:38 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F43DCDB3"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '048da2e9-c01e-005a-18c7-535416000000'
    'x-ms-client-request-id': '905e0f5f-bfba-11ef-a52e-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:42:28 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpuhpuvvtt.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  95%|█████████▍| 422/445 [51:56<02:48,  7.32s/it]2024-12-22 01:42:35,311 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p79.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '94cdea70-bfba-11ef-93e9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpuhpuvvtt.pdf を削除しました。
423/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p79.pdf

2024-12-22 01:42:36,090 - INFO - Response status: 206
Response headers:
    'Content-Length': '570921'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F51A3D77"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8e617eb8-501e-0010-7dc7-536471000000'
    'x-ms-client-request-id': '94cdea70-bfba-11ef-93e9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:42:36 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplrvwhudd.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  95%|█████████▌| 423/445 [52:03<02:40,  7.31s/it]2024-12-22 01:42:42,596 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p8.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9925833f-bfba-11ef-9ad7-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmplrvwhudd.pdf を削除しました。
424/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p8.pdf

2024-12-22 01:42:43,358 - INFO - Response status: 206
Response headers:
    'Content-Length': '461601'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:33 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F1593122"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '844d755f-501e-00ba-6bc7-53b29e000000'
    'x-ms-client-request-id': '9925833f-bfba-11ef-9ad7-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:42:43 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfnsbdbl9.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  95%|█████████▌| 424/445 [52:10<02:31,  7.23s/it]2024-12-22 01:42:49,661 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p80.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9d5b68cf-bfba-11ef-b1f1-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfnsbdbl9.pdf を削除しました。
425/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p80.pdf

2024-12-22 01:42:50,418 - INFO - Response status: 206
Response headers:
    'Content-Length': '490320'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F6700F95"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6db3e1d7-201e-00d8-1fc7-53f546000000'
    'x-ms-client-request-id': '9d5b68cf-bfba-11ef-b1f1-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:42:50 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjr1owkf2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  96%|█████████▌| 425/445 [52:17<02:24,  7.23s/it]2024-12-22 01:42:56,886 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p81.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a1a9dcb5-bfba-11ef-a8c7-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpjr1owkf2.pdf を削除しました。
426/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p81.pdf

2024-12-22 01:42:57,660 - INFO - Response status: 206
Response headers:
    'Content-Length': '521314'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F670367B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '076c1077-101e-0058-34c7-5356ec000000'
    'x-ms-client-request-id': 'a1a9dcb5-bfba-11ef-a8c7-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:42:57 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpx5nu9349.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  96%|█████████▌| 426/445 [52:25<02:17,  7.24s/it]2024-12-22 01:43:04,143 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p82.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a5fd2fed-bfba-11ef-a58c-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpx5nu9349.pdf を削除しました。
427/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p82.pdf

2024-12-22 01:43:04,881 - INFO - Response status: 206
Response headers:
    'Content-Length': '576255'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F72B3A05"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cda5fef7-301e-006d-22c7-53f8b9000000'
    'x-ms-client-request-id': 'a5fd2fed-bfba-11ef-a58c-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:43:04 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpchlzcrq1.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  96%|█████████▌| 427/445 [52:32<02:10,  7.27s/it]2024-12-22 01:43:11,468 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p83.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'aa5ae33b-bfba-11ef-af1a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpchlzcrq1.pdf を削除しました。
428/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p83.pdf

2024-12-22 01:43:12,201 - INFO - Response status: 206
Response headers:
    'Content-Length': '549534'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F73FBC72"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '6633b783-a01e-0027-08c7-53c8de000000'
    'x-ms-client-request-id': 'aa5ae33b-bfba-11ef-af1a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:43:11 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpm98ugh9e.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  96%|█████████▌| 428/445 [52:39<02:03,  7.26s/it]2024-12-22 01:43:18,725 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p84.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'aeae503f-bfba-11ef-b05a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpm98ugh9e.pdf を削除しました。
429/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p84.pdf

2024-12-22 01:43:19,474 - INFO - Response status: 206
Response headers:
    'Content-Length': '546082'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F57D9899"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '238e4278-301e-00e5-41c7-534060000000'
    'x-ms-client-request-id': 'aeae503f-bfba-11ef-b05a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:43:19 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpboo4og_a.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  96%|█████████▋| 429/445 [52:47<01:56,  7.29s/it]2024-12-22 01:43:26,090 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p85.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b311e429-bfba-11ef-833f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpboo4og_a.pdf を削除しました。
430/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p85.pdf

2024-12-22 01:43:26,837 - INFO - Response status: 206
Response headers:
    'Content-Length': '457235'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F5838558"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '24aae1b5-a01e-00e0-22c7-53b41f000000'
    'x-ms-client-request-id': 'b311e429-bfba-11ef-833f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:43:26 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpm66yq10b.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  97%|█████████▋| 430/445 [52:54<01:48,  7.23s/it]2024-12-22 01:43:33,173 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p86.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b74ae3a7-bfba-11ef-b377-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpm66yq10b.pdf を削除しました。
431/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p86.pdf

2024-12-22 01:43:34,024 - INFO - Response status: 206
Response headers:
    'Content-Length': '686250'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F4C79874"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cfbddee2-701e-00cb-4dc7-53c0a7000000'
    'x-ms-client-request-id': 'b74ae3a7-bfba-11ef-b377-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:43:33 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpaucknuh3.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  97%|█████████▋| 431/445 [53:06<02:04,  8.87s/it]2024-12-22 01:43:45,859 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p87.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'beda9fd6-bfba-11ef-a6b5-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpaucknuh3.pdf を削除しました。
432/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p87.pdf

2024-12-22 01:43:46,621 - INFO - Response status: 206
Response headers:
    'Content-Length': '401214'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F472D2E1"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '197c648f-d01e-004e-14c7-539772000000'
    'x-ms-client-request-id': 'beda9fd6-bfba-11ef-a6b5-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:43:46 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfd0ewrkt.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  97%|█████████▋| 432/445 [53:13<01:48,  8.34s/it]2024-12-22 01:43:52,963 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p88.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c3169c02-bfba-11ef-821b-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpfd0ewrkt.pdf を削除しました。
433/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p88.pdf

2024-12-22 01:43:53,726 - INFO - Response status: 206
Response headers:
    'Content-Length': '476211'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F33A79C6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ad596f86-e01e-00c5-41c7-532cac000000'
    'x-ms-client-request-id': 'c3169c02-bfba-11ef-821b-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:43:53 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_bn84rkp.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  97%|█████████▋| 433/445 [53:21<01:37,  8.09s/it]2024-12-22 01:44:00,458 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p89.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c78e3c8d-bfba-11ef-a35f-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp_bn84rkp.pdf を削除しました。
434/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p89.pdf

2024-12-22 01:44:01,222 - INFO - Response status: 206
Response headers:
    'Content-Length': '463924'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:37 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F355849A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '335f0416-401e-00c8-17c7-53c3a0000000'
    'x-ms-client-request-id': 'c78e3c8d-bfba-11ef-a35f-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:44:00 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpt9t_b99r.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  98%|█████████▊| 434/445 [53:28<01:25,  7.80s/it]2024-12-22 01:44:07,598 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p9.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'cbcfc067-bfba-11ef-b262-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpt9t_b99r.pdf を削除しました。
435/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p9.pdf

2024-12-22 01:44:08,404 - INFO - Response status: 206
Response headers:
    'Content-Length': '460626'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:34 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F1D8F4F6"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '335f0b69-401e-00c8-5bc7-53c3a0000000'
    'x-ms-client-request-id': 'cbcfc067-bfba-11ef-b262-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:44:08 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4lei9zql.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  98%|█████████▊| 435/445 [53:35<01:15,  7.59s/it]2024-12-22 01:44:14,685 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p90.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd00914d3-bfba-11ef-bb60-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4lei9zql.pdf を削除しました。
436/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p90.pdf

2024-12-22 01:44:15,522 - INFO - Response status: 206
Response headers:
    'Content-Length': '594466'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:40 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F5802DBE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cfbe2075-701e-00cb-58c7-53c0a7000000'
    'x-ms-client-request-id': 'd00914d3-bfba-11ef-bb60-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:44:15 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7632460f.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  98%|█████████▊| 436/445 [53:43<01:07,  7.54s/it]2024-12-22 01:44:22,108 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p91.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd475c0e9-bfba-11ef-b630-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp7632460f.pdf を削除しました。
437/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p91.pdf

2024-12-22 01:44:22,841 - INFO - Response status: 206
Response headers:
    'Content-Length': '189562'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:41 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F5A3937A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '68a2f0e7-001e-00cf-18c7-533525000000'
    'x-ms-client-request-id': 'd475c0e9-bfba-11ef-b630-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:44:22 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb_4hl1iz.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  98%|█████████▊| 437/445 [53:49<00:58,  7.28s/it]2024-12-22 01:44:28,801 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p92.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd872d784-bfba-11ef-be60-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpb_4hl1iz.pdf を削除しました。
438/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p92.pdf

2024-12-22 01:44:29,532 - INFO - Response status: 206
Response headers:
    'Content-Length': '524906'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F4AE397C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '70e2e084-c01e-0051-3fc7-534c62000000'
    'x-ms-client-request-id': 'd872d784-bfba-11ef-be60-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:44:29 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbf7ko1u2.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  98%|█████████▊| 438/445 [53:57<00:50,  7.26s/it]2024-12-22 01:44:36,003 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p93.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'dcbdeeac-bfba-11ef-85d9-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpbf7ko1u2.pdf を削除しました。
439/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p93.pdf

2024-12-22 01:44:36,721 - INFO - Response status: 206
Response headers:
    'Content-Length': '658645'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:39 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F49F7D15"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '436c3a12-001e-00a9-3ec7-53877f000000'
    'x-ms-client-request-id': 'dcbdeeac-bfba-11ef-85d9-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:44:36 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphvpdmari.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  99%|█████████▊| 439/445 [54:04<00:43,  7.23s/it]2024-12-22 01:44:43,168 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p94.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e1033252-bfba-11ef-944a-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmphvpdmari.pdf を削除しました。
440/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p94.pdf

2024-12-22 01:44:43,912 - INFO - Response status: 206
Response headers:
    'Content-Length': '440005'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F66EB18E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8af3f5c8-401e-00a5-62c7-53698e000000'
    'x-ms-client-request-id': 'e1033252-bfba-11ef-944a-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:44:43 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpqae3vb6o.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  99%|█████████▉| 440/445 [54:11<00:35,  7.18s/it]2024-12-22 01:44:50,267 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p95.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e53e6586-bfba-11ef-a96d-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpqae3vb6o.pdf を削除しました。
441/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p95.pdf

2024-12-22 01:44:51,057 - INFO - Response status: 206
Response headers:
    'Content-Length': '699466'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:42 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F6689DDE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'e588b120-c01e-003c-25c7-53e64c000000'
    'x-ms-client-request-id': 'e53e6586-bfba-11ef-a96d-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:44:50 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4dqwqne7.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  99%|█████████▉| 441/445 [54:18<00:29,  7.27s/it]2024-12-22 01:44:57,721 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p96.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e9afc41c-bfba-11ef-a428-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmp4dqwqne7.pdf を削除しました。
442/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p96.pdf

2024-12-22 01:44:58,488 - INFO - Response status: 206
Response headers:
    'Content-Length': '412277'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F751A99C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '30d9cfa5-d01e-0082-2cc7-53f3c7000000'
    'x-ms-client-request-id': 'e9afc41c-bfba-11ef-a428-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:44:57 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpkisjftt5.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR:  99%|█████████▉| 442/445 [54:25<00:21,  7.19s/it]2024-12-22 01:45:04,723 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p97.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'eddc4385-bfba-11ef-9d27-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpkisjftt5.pdf を削除しました。
443/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p97.pdf

2024-12-22 01:45:05,485 - INFO - Response status: 206
Response headers:
    'Content-Length': '674952'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:43 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F73DE9AF"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9b5e970d-601e-0090-75c7-53c7db000000'
    'x-ms-client-request-id': 'eddc4385-bfba-11ef-9d27-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:45:05 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpp_nxpaeh.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR: 100%|█████████▉| 443/445 [54:33<00:14,  7.21s/it]2024-12-22 01:45:11,989 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p98.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f230eea7-bfba-11ef-b837-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpp_nxpaeh.pdf を削除しました。
444/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p98.pdf

2024-12-22 01:45:12,788 - INFO - Response status: 206
Response headers:
    'Content-Length': '803844'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:36 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F2CF8613"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '81ad6915-601e-003a-08c7-531134000000'
    'x-ms-client-request-id': 'f230eea7-bfba-11ef-b837-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:45:12 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpx8fwh14w.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR: 100%|█████████▉| 444/445 [54:40<00:07,  7.26s/it]2024-12-22 01:45:19,350 - INFO - Request URL: 'https://pdfalldata.blob.core.windows.net/rag-pdf/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_/3%E5%B9%B4_%E4%B8%AD%E5%AD%A6%E6%A0%A1%E7%90%86%E7%A7%91_%E6%8C%87%E5%B0%8E%E6%9B%B8_%E6%9D%BF%E6%9B%B8%E4%BE%8B_p99.pdf'
Request method: 'GET'
Request headers:
    'x-ms-range': 'REDACTED'
    'x-ms-version': 'REDACTED'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.16.0 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f6943aa4-bfba-11ef-a3ae-30894aa4d14c'
No body was attached to the request

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpx8fwh14w.pdf を削除しました。
445/445 処理中
コンテナ名: rag-pdf, Blob名: 3年_中学校理科_指導書_板書例_/3年_中学校理科_指導書_板書例_p99.pdf

2024-12-22 01:45:20,129 - INFO - Response status: 206
Response headers:
    'Content-Length': '825398'
    'Content-Type': 'application/pdf'
    'Content-Range': 'REDACTED'
    'Last-Modified': 'Mon, 16 Dec 2024 00:02:36 GMT'
    'Accept-Ranges': 'REDACTED'
    'ETag': '"0x8DD1D64F2C8622D"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '11f4e1c2-801e-00d5-06c7-531a4a000000'
    'x-ms-client-request-id': 'f6943aa4-bfba-11ef-a3ae-30894aa4d14c'
    'x-ms-version': 'REDACTED'
    'x-ms-creation-time': 'REDACTED'
    'x-ms-blob-content-md5': 'REDACTED'
    'x-ms-lease-status': 'REDACTED'
    'x-ms-lease-state': 'REDACTED'
    'x-ms-blob-type': 'REDACTED'
    'x-ms-server-encrypted': 'REDACTED'
    'Access-Control-Expose-Headers': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Date': 'Sat, 21 Dec 2024 16:45:19 GMT'

一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpzoq6wp60.pdf を作成しました。
Total pages in PDF: 1
OCR開始

Processing OCR: 100%|██████████| 445/445 [54:47<00:00,  7.39s/it]

OCR終了
1ページ処理開始
一時ファイル C:\Users\banqu\AppData\Local\Temp\tmpzoq6wp60.pdf を削除しました。

,filename,title,content,tableinfo,graphinfo
0,1_08-39_1章_元.pdf,"[{'id': 5, 'file_name': '1_08-39_1章_元.pdf', 'f...","[{'id': 3, 'file_name': '1_08-39_1章_元.pdf', 'f...","[{'id': 46, 'file_name': '1_08-39_1章_元.pdf', '...","[{'id': 1, 'file_name': '1_08-39_1章_元.pdf', 'f..."
1,1年_中学校理科_指導書_板書例_p1.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...","[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...",[]
2,1年_中学校理科_指導書_板書例_p10.pdf,"[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p10....","[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p10....","[{'id': 4, 'file_name': '1年_中学校理科_指導書_板書例_p10....",[]
3,1年_中学校理科_指導書_板書例_p100.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p100...","[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p100...",[],"[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p100..."
4,1年_中学校理科_指導書_板書例_p101.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p101...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p101...",[],"[{'id': 23, 'file_name': '1年_中学校理科_指導書_板書例_p10..."
...,...,...,...,...,...
440,3年_中学校理科_指導書_板書例_p95.pdf,"[{'id': 3, 'file_name': '3年_中学校理科_指導書_板書例_p95....","[{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p95....",[],"[{'id': 2, 'file_name': '3年_中学校理科_指導書_板書例_p95...."
441,3年_中学校理科_指導書_板書例_p96.pdf,"[{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p96....","[{'id': 2, 'file_name': '3年_中学校理科_指導書_板書例_p96....",[],"[{'id': 4, 'file_name': '3年_中学校理科_指導書_板書例_p96...."
442,3年_中学校理科_指導書_板書例_p97.pdf,"[{'id': 4, 'file_name': '3年_中学校理科_指導書_板書例_p97....","[{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p97....",[],"[{'id': 3, 'file_name': '3年_中学校理科_指導書_板書例_p97...."
443,3年_中学校理科_指導書_板書例_p98.pdf,"[{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p98....","[{'id': 2, 'file_name': '3年_中学校理科_指導書_板書例_p98....",[],"[{'id': 4, 'file_name': '3年_中学校理科_指導書_板書例_p98...."
444,3年_中学校理科_指導書_板書例_p99.pdf,"[{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p99....","[{'id': 2, 'file_name': '3年_中学校理科_指導書_板書例_p99....",[],"[{'id': 4, 'file_name': '3年_中学校理科_指導書_板書例_p99...."

In [19]:
# dfをpickleで保存しておく
# df.to_pickle(r"./OCR_Processed_DF/20241222_all_ocr_processed_df.pkl")

import pandas as pd
# dfをpickleで読み込む
df = pd.read_pickle(r"./OCR_Processed_DF/20241222_all_ocr_processed_df.pkl")
display(df)

,filename,title,content,tableinfo,graphinfo
0,1_08-39_1章_元.pdf,"[{'id': 5, 'file_name': '1_08-39_1章_元.pdf', 'f...","[{'id': 3, 'file_name': '1_08-39_1章_元.pdf', 'f...","[{'id': 46, 'file_name': '1_08-39_1章_元.pdf', '...","[{'id': 1, 'file_name': '1_08-39_1章_元.pdf', 'f..."
1,1年_中学校理科_指導書_板書例_p1.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...","[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...",[]
2,1年_中学校理科_指導書_板書例_p10.pdf,"[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p10....","[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p10....","[{'id': 4, 'file_name': '1年_中学校理科_指導書_板書例_p10....",[]
3,1年_中学校理科_指導書_板書例_p100.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p100...","[{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p100...",[],"[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p100..."
4,1年_中学校理科_指導書_板書例_p101.pdf,"[{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p101...","[{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p101...",[],"[{'id': 23, 'file_name': '1年_中学校理科_指導書_板書例_p10..."
...,...,...,...,...,...
440,3年_中学校理科_指導書_板書例_p95.pdf,"[{'id': 3, 'file_name': '3年_中学校理科_指導書_板書例_p95....","[{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p95....",[],"[{'id': 2, 'file_name': '3年_中学校理科_指導書_板書例_p95...."
441,3年_中学校理科_指導書_板書例_p96.pdf,"[{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p96....","[{'id': 2, 'file_name': '3年_中学校理科_指導書_板書例_p96....",[],"[{'id': 4, 'file_name': '3年_中学校理科_指導書_板書例_p96...."
442,3年_中学校理科_指導書_板書例_p97.pdf,"[{'id': 4, 'file_name': '3年_中学校理科_指導書_板書例_p97....","[{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p97....",[],"[{'id': 3, 'file_name': '3年_中学校理科_指導書_板書例_p97...."
443,3年_中学校理科_指導書_板書例_p98.pdf,"[{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p98....","[{'id': 2, 'file_name': '3年_中学校理科_指導書_板書例_p98....",[],"[{'id': 4, 'file_name': '3年_中学校理科_指導書_板書例_p98...."
444,3年_中学校理科_指導書_板書例_p99.pdf,"[{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p99....","[{'id': 2, 'file_name': '3年_中学校理科_指導書_板書例_p99....",[],"[{'id': 4, 'file_name': '3年_中学校理科_指導書_板書例_p99...."

In [21]:
# 内容確認
df.loc[:, 'title']

0      [{'id': 5, 'file_name': '1_08-39_1章_元.pdf', 'f...
1      [{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...
2      [{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p10....
3      [{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p100...
4      [{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p101...
                             ...
440    [{'id': 3, 'file_name': '3年_中学校理科_指導書_板書例_p95....
441    [{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p96....
442    [{'id': 4, 'file_name': '3年_中学校理科_指導書_板書例_p97....
443    [{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p98....
444    [{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p99....
Name: title, Length: 445, dtype: object

In [22]:
df.loc[:, 'content']

0      [{'id': 3, 'file_name': '1_08-39_1章_元.pdf', 'f...
1      [{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p1.p...
2      [{'id': 1, 'file_name': '1年_中学校理科_指導書_板書例_p10....
3      [{'id': 3, 'file_name': '1年_中学校理科_指導書_板書例_p100...
4      [{'id': 2, 'file_name': '1年_中学校理科_指導書_板書例_p101...
                             ...
440    [{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p95....
441    [{'id': 2, 'file_name': '3年_中学校理科_指導書_板書例_p96....
442    [{'id': 1, 'file_name': '3年_中学校理科_指導書_板書例_p97....
443    [{'id': 2, 'file_name': '3年_中学校理科_指導書_板書例_p98....
444    [{'id': 2, 'file_name': '3年_中学校理科_指導書_板書例_p99....
Name: content, Length: 445, dtype: object

# 以下はとりあえず要らないと思われる

In [1]:
"""
This code sample shows Prebuilt Document operations with the Azure Form Recognizer client library. 
The async versions of the samples require Python 3.6 or later.

To learn more, please visit the documentation - Quickstart: Form Recognizer Python client library SDKs
https://learn.microsoft.com/azure/applied-ai-services/form-recognizer/quickstarts/get-started-v3-sdk-rest-api?view=doc-intel-3.1.0&pivots=programming-language-python
"""

from azure.core.credentials import AzureKeyCredential
from azure.ai.formrecognizer import DocumentAnalysisClient

"""
Remember to remove the key from your code when you're done, and never post it publicly. For production, use
secure methods to store and access your credentials. For more information, see 
https://docs.microsoft.com/en-us/azure/cognitive-services/cognitive-services-security?tabs=command-line%2Ccsharp#environment-variables-and-application-configuration
"""

endpoint = "https://test20240928-kmakici.cognitiveservices.azure.com/"
key = "6b4bc8ebcb10472aa517a7f04c7fa594"

# sample document
formUrl = "https://kmakicistrage2.blob.core.windows.net/20240928-rag-test-container/CONVENTION/オーストラリアシドニー.pdf"

document_analysis_client = DocumentAnalysisClient(
        endpoint=endpoint, credential=AzureKeyCredential(key)
    )
    
poller = document_analysis_client.begin_analyze_document_from_url("prebuilt-document", formUrl)
result = poller.result()

print("----Key-value pairs found in document----")
for kv_pair in result.key_value_pairs:
    if kv_pair.key and kv_pair.value:
        print("Key '{}': Value: '{}'".format(kv_pair.key.content, kv_pair.value.content))
    else:
        print("Key '{}': Value:".format(kv_pair.key.content))

print("----------------------------------------")

----Key-value pairs found in document----
Key 'コ': Value:
Key 'URL': Value: 'http://www. scec. com. au/'
Key 'TEL': Value: '+61 2 9282 5000'
Key 'FAX': Value: '+61 2 9282 5041'
Key 'email': Value: 'info@scec. com. au'
Key 'URL': Value: 'http://www. scec. com. au/'
Key '建設費': Value: '2億8700万
+5700 万
ル(1999
2009
5000 万オ
1988年5月4日'
Key 'TEL': Value: '+61 2 9282 5000'
Key 'FAX': Value: '+61 2 9282 5041'
Key 'ema i l': Value: 'info@scec. com. au'
Key 'URL': Value: 'http://www. sydneyshowground. com. au/home. html'
Key 'TEL': Value: '+61 2 9704 1111'
Key 'FAX': Value: '+61 2 9704 1173'
Key 'email': Value: 'operations@sydneyshowground. com. au'
Key '企業名': Value: 'Australia
Ltd.'
Key 'URL': Value: 'http://www. aec. net. au/'
Key '住所': Value: '267 Collins Street Melbourne Vic 3000 Australia'
Key 'TEL': Value: '+613 9654 7773'
Key 'FAX': Value: '+613 9654 5596'
Key 'email': Value: 'mail@aec. net. au'
Key '企業名': Value: 'Exhibition Management Pty Ltd'
Key 'URL': Value: 'http://www. exhibitionmanagement. com. au/cpa/htm/htm_home. a'
Key '設立': Value: '1979 年'
Key '住所': Value: '179 Park Street (PO Box 1192) South Melbourne Vic 3205'
Key 'TEL': Value: '03 9699 4699'
Key 'FAX': Value: '03 9690 9333'
Key 'ema i l': Value: 'info@exhibitionmanagement. com'
Key '企業名': Value: 'Reed Exhibitions Australia'
Key 'URL': Value: 'http://www. reedexhibitions. com. au/'
Key '住所': Value: 'Tower 2 475 Victoria Avenue Chatswood NSW 2067 Australia'
Key 'TEL': Value: '+ 61 2 9422 2500'
Key 'FAX': Value: '+ 61 2 9422 2555'
Key 'ema i l': Value: 'ask@reedexpo. com. au'
Key '企業名': Value: 'Exhibition
Australasia'
Key 'URL': Value: 'http://www. eeaa. com. au/ index. php
Level 11'
Key '住所': Value: '809 Pacific Highway
CHATSWOOD NSW 2067'
Key 'TEL': Value: '+61 2 9413 9520'
Key 'FAX': Value: '+61 2 8088 1325'
Key '。': Value:
Key '、': Value: '173.6'
Key '電話': Value: ':132 878'
Key '2': Value: '6213 6711'
Key 'Hotel Ibis': Value: ':unselected:'
Key '電話:': Value: '+61 2 9969 1400'
Key 'Ex-JL:': Value: 'elizabethrich@a1. com. au'
Key '電話:': Value: '+61 2 9452 7538'
Key 'Eメール:': Value: 'info@eeaa. com. au'
Key '電話:': Value: '+61 2 9967 8240'
Key 'Eメール:': Value: 'hub@ises. org. au'
Key '電話:': Value: '+61 2 9929 5400'
Key 'Ex': Value: 'mea@mea. org. au'
Key '電話:': Value: '+61 2 9240 2000'
Key 'Eメール:': Value: 'contact@ttf. org. au'
----------------------------------------

# 以下はDataBricks特有の処理のため割愛

In [0]:
# スキーマを再帰的に削除
# spark.sql("DROP SCHEMA IF EXISTS poc2 CASCADE")

# 新しいスキーマを作成
# spark.sql("CREATE SCHEMA poc2")

# データフレームを指定されたスキーマに保存 
# spark.createDataFrame(final_df).write.mode("overwrite").saveAsTable("poc2.mateq_orijinal_data_0911")

In [39]:
# original_df = spark.table("poc2.mateq_orijinal_data_0911").toPandas()
# filtered_df = original_df[original_df['title'] == 'NEL017_製法.pdf']
# display(original_df)

In [0]:
# import pprint
# path = "/dbfs/mnt/rag-poc-q2-container/pdfs/ノウハウ_機密事項あり取り扱い注意/接着/NAD058_接着剤の車両への適用例⑩.pdf"
# result = perform_ocr(path, split_f_path="/dbfs/mnt/rag-poc-q2-container/pdfs/splits/",
#                                  extract_f_path="/dbfs/mnt/rag-poc-q2-container/pdfs/extracts/",
#                                  chunk_size=1000, extract_keywords=[], new_file_name="file_name")
# result = process_ocr_results(result)
# pprint.pprint(result)

In [0]:
# !pip install azure-ai-documentintelligence==1.0.0b2 python-dotenv==1.0.0 requests==2.31.0

In [0]:
# import os

# from azure.ai.documentintelligence import DocumentIntelligenceClient
# from azure.core.credentials import AzureKeyCredential
# from dotenv import load_dotenv

# load_dotenv()

# # create document intelligence client
# AI_SERVICES_ENDPOINT = "https://20240525test.cognitiveservices.azure.com/"
# AI_SERVICES_API_KEY = "242dc7331a484ecdae1f15ec90c957a8"
# di_client = DocumentIntelligenceClient(
#     credential=AzureKeyCredential(AI_SERVICES_API_KEY),
#     endpoint=AI_SERVICES_ENDPOINT,
# )

# # load document
# path_to_sample_documents = "/dbfs/mnt/rag-poc-q2-container/pdfs/ノウハウ_機密事項あり取り扱い注意/におい/NSM003_発生シーンマップ.pdf"

# # analyze document
# with open(path_to_sample_documents, "rb") as doc:
#     poller = di_client.begin_analyze_document(
#         "prebuilt-layout",
#         analyze_request=doc,
#         output_content_format="markdown",
#         content_type="application/octet-stream",
#     )
# result = poller.result()

# print(result.content)